hiero-ledger/hiero-mirror-node-explorer

src/components/AxiosStatus.vue
src/components/SearchBar.vue
src/pages/NoSearchResult.vue
src/router/index.ts
src/utils/AxiosMonitor.ts
src/utils/SearchRequest.ts

The changes below improve diagnostic message displayed by Explorer when server returns error.
In particular, it better detects if server is overloaded (busy) or if internet connection is faulty.
Search bar also makes some error analysis et may now reports « search error » when:
1) no match has been found
2) some calls to server did fail
Fixes #00027
**Checklist**

00027 error diagnostic misleading

---

src/components/account/AccountTable.vue
src/components/account/BalanceTable.vue
src/components/token/TokenBalanceTable.vue
src/components/transfer_graphs/TokenTransferGraphC.vue
src/components/transfer_graphs/TokenTransferGraphF.vue
src/components/values/TokenAmount.vue
src/pages/AccountDetails.vue
src/pages/TokenDetails.vue
tests/unit/token/TokenBalanceTable.spec.ts
tests/unit/values/TokenAmount.spec.ts

With the changes below, Explorer now computes  amount of tokens using the row amount number and the number of decimals specified in TokenInfo.decimals.
For token 00.731861, detail page now displays:
- Total supply: 20,000,002
- Max supply: 1,000,000
This new behavior applies across all places when token amounts are displayed.
Fixes #37
See instructions in issue #37 to experiment those changes.
**Checklist**

TokenAmount component now takes TokenInfo.decimals into account.

---

src/App.vue
src/assets/styles/explorer.scss
src/components/Footer.vue
src/components/SearchBar.vue
src/components/TopNavBar.vue
src/pages/AccountBalances.vue
src/pages/AccountDetails.vue
src/pages/Accounts.vue
src/pages/ContractDetails.vue
src/pages/Contracts.vue
src/pages/MainDashboard.vue
src/pages/MobileMenu.vue
src/pages/MobileSearch.vue
src/pages/NoSearchResult.vue
src/pages/TokenDetails.vue
src/pages/Tokens.vue
src/pages/TopicDetails.vue
src/pages/Topics.vue
src/pages/TransactionDetails.vue
src/pages/Transactions.vue
src/pages/TransactionsById.vue

This PR:
- makes a Footer component and inserts it into each page (instead of into App)
- makes each page control the background color of its content and footer (instead of App)
- fixes the layout of the network selector on iPad
- slightly reduces the size of the sponsor logo
Related to #35
Reducing the size of the (NoSearchResult, MobileMenu, MobileSearch) pages on the desktop should not change their background color, and the network selector should match.
Menu and Search on mobile/tablet should not display background color mismatch.
**Checklist**

00035 improve mobile

---

src/App.vue
src/assets/styles/explorer.scss
src/components/TopNavBar.vue
src/pages/MobileMenu.vue
src/pages/MobileSearch.vue
src/router/index.ts
src/schemas/NetworkRegistry.ts
tests/e2e/specs/TopNavigationBar.spec.ts
tests/unit/App.spec.ts
tests/unit/TopNavBar.spec.ts

This PR adds the support for PREVIEWNET network. It also:
- Changes the network selector to always use the dropdown version (this is yet to be vetted).
(note the code for the original 'flat' version of the selector is still there).
- Moves network-related logic to NetworkRegistry.ts
Fixes #11
This is still a draft PR, not ready for merge.
**Checklist**

Add support for PREVIEWNET

---

src/pages/TokenDetails.vue
src/utils/EntityID.ts
tests/unit/token/TokenDetails.spec.ts

With the changes below, Explorer now displays new field named Ethereum Address in token details page.
Fixes #52
**Checklist**

00052 display ethereum address

---

.env
README.md
docker-compose.yml
src/schemas/NetworkRegistry.ts

This PR modifies the NetworkRegistry such that a custom NetworkEntry is added when 2 environment variables are set in the .env file located at the root of the repository. These variables define the url and displayName of the additional NetworkEntry. This will result in a custom menu item added to the network selector pull-down menu.
Fixes #10
Note the variables in the .env file are taken into account by Webpack at build time, and available to the code in all
environments:
- in development (ex: 'npm run serve'
- in a production build (ex: 'npm build && npm serve')
- or in a Docker container (ex: 'docker-compose up -d')
This PR can be squashed.
**Checklist**

Add support for local network

---

src/components/NotificationBanner.vue
src/pages/ContractDetails.vue
src/pages/TransactionDetails.vue
tests/unit/Mocks.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

This PR:
- extracts the notification banner from the TransactionDetails template to make a very simple NotificationBanner component which is destined to be used potentially by every details page.
- uses NotificationBanner in ContractDetails to notify the user:
- when the contract is in grace period (expiration_timestamp ≤ now and deleted == false )
- when the contract is deleted
There is no notion of grace period duration yet (we could notify the user of the grace time remaining) because the design for that has not been finalized in the infrastructure.
Fixes #26
There is currently no "live" contract in grace period to exercise this. It has been unit tested only.
This can be squashed.
**Checklist**

Added grace period notif

---

src/App.vue
src/components/Property.vue
src/components/values/HexaValue.vue
src/components/values/TokenAmount.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/TokenDetails.vue
src/pages/TransactionDetails.vue
tests/e2e/specs/CopyHexaToClipboard.spec.ts
tests/e2e/specs/DashboardNavigation.spec.ts
tests/e2e/specs/TokenNavigation.spec.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/token/TokenDetails.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/values/HexaValue.spec.ts
tests/unit/values/KeyValue.spec.ts

This PR essentially introduces a small component ('Property') and its use by entity details pages which need to display (key, value) for each of the entity properties.
The Property component currently offers 2 different layouts:
- column based (like previously) above the SMALL_SCREEN breakpoint 
- flexbox based below the SMALL_SCREEN breakpoint
Fixes #35
Can be squashed (and branch deleted).
**Checklist**

Modify layout of property key-values on mobile.

---

src/utils/EntityDescriptor.ts
src/utils/TransactionTools.ts

With this PR, the entity_id property in transactions of type TOKENASSOCIATE & TOKENDISSOCIATE is now interpreted as an Account ID instead of a TOKEN ID.
Fixes #65
Can be squashed and branch deleted.
**Checklist**

Interpret Entity ID as Account ID in TOKENASSOCIATE & TOKENDISSOCIATE

---

.env
public/index.html
src/App.vue
src/assets/branding/install-branding.sh
src/assets/styles/brand-theme.scss
src/components/AxiosStatus.vue
src/components/Footer.vue
src/components/ModalDialog.vue
src/components/TopNavBar.vue
src/pages/TokenDetails.vue
tests/unit/App.spec.ts
tests/unit/TopNavBar.spec.ts

This PR:
* adds an about dialog, displayed when clicking on the (top-left) product logo, which mentions the build date
* adds 2 environment variables, allowing to customize the product name and the URL visited when clicking on the (bottom-right) sponsor logo and includes the .env file in the branding
* slightly modifies ModalDialog to pass icon class as a prop.
Fixes #55
- A couple of cosmetic changes have sneaked in...
- This can be squashed-merged and branch deleted.
**Checklist**

Display build date

---

src/components/transfer_graphs/HbarTransferGraphF.vue
src/components/transfer_graphs/layout/HbarTransferLayout.ts
src/components/values/AccountLink.vue
src/pages/AccountDetails.vue
src/schemas/OperatorRegistry.ts
src/utils/EntityID.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/transfer_graphs/layout/HbarTransferLayout.spec.ts
tests/unit/values/AccountLink.spec.ts

With the changes below, Explorer now displays node owners of mainnet only when mainnet is selected.
When testnet or previewnet are selected, node < 100 are simply labeled « Node ».
Fixes #54
Can be squashed and branch deleted.
**Checklist**

00054 node owners incorrect

---

src/components/transaction/TransactionByIdTable.vue
src/components/values/AccountLink.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/TransactionDetails.vue
src/pages/TransactionsById.vue
src/utils/TransactionTools.ts
tests/e2e/specs/AccountNavigation.spec.ts
tests/e2e/specs/SearchBar.spec.ts
tests/e2e/specs/TransactionNavigation.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

This PR mostly touches TransactionDetails and TransactionByIdTable in order to:
* handle relationships between transactions:
* Parent transaction and child transactions
* Scheduling transaction and scheduled transaction
* display nature of relationship in the table listing transactions with same ID (result of search)
Fixes #68
Related to #9
Search for the following transactions (on TESTNET) to visualize the changes, and then navigate between the details of individual transaction:
* 0.0.6036@1652787852.826165451
* 0.0.2812286@1653665235.098465576
I removed the link "Show all transactions..." and then changed my mind. I think we might still find useful to display the table showing all transactions involved in a relationship, so …

Handle transaction relationships

---

package-lock.json
package.json
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/NoSearchResult.vue
src/schemas/HederaUtils.ts
src/utils/B64Utils.ts
src/utils/EntityID.ts
src/utils/SearchRequest.ts
tests/unit/utils/B64Utils.spec.ts
tests/unit/utils/EntityID.spec.ts
tests/unit/utils/SearchRequest.spec.ts

Changes below enable Explorer to search an account using its alias.
User may now enter an account alias in hexadecimal form (with or without 0x prefix).
Fixes #8
On mainnet, the following accounts have an alias:
- 0.0.721838 / 0x12200000fc0634e2ab455eff393f04819efa262fe5e6ab1c7ed1d4f85fbcd8e6e296
- 0.0.714669 / 0x1220fe7c4f2fbb892f9d494a168b0efcd5f4f06424c622474149d4f49308e6a84be6
**Checklist**

00008 support account alias

---

src/components/values/HexaValue.vue
src/pages/ContractDetails.vue
src/schemas/HederaSchemas.ts
src/utils/SearchRequest.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/utils/SearchRequest.spec.ts
tests/unit/values/HexaValue.spec.ts

With the changes below, explorer:
1) displays EVM address in contract detail page
2) enables to search a contract using its EVM address
Fixes #30
On mainnet, contract 0.0.749775 can be used for testing.
This can be squashed-merged and the branch can be deleted.
**Checklist**

Support EVM address in Search and Contract Details (#30)

---

src/components/values/TokenExtra.vue
src/pages/TokenDetails.vue
src/schemas/HederaUtils.ts

This is a follow-up for PR #72 which make sure the token symbol provided for importing into Metamask is no longer than 11 char. Use best effort to derive this from the actual token symbol or name.
Follow-up for #63 
Squash-merge and delete branch.
**Checklist**

00063 token symbol for metamask

---

.env
.github/workflows/explorer-e2e-tests.yml
.github/workflows/explorer-unit-tests.yml
package-lock.json
package.json
src/router.ts

* Bump Bulma to 0.9.4
* Replace 'npm ci' by 'npm install' in GitHub actions to avoid current build failure until we figure out why 'npm ci' believes our package.json and package-lock.json are not in sync, even after a fresh npm install...
* Control document title prefix with environment variable
PR can be squashed-merged and branch can be deleted.
**Checklist**

Bump bulma dependency from 0.9.3 to 0.9.4

---

src/assets/styles/explorer-bulma.sass

1 line change to remove unused SCSS definition clashing with upcoming use of CSS variables for theming.
Branch can be squashed and deleted.
**Checklist**

Remove unused SCSS definition

---

src/components/Footer.vue
src/components/TopNavBar.vue
tests/unit/App.spec.ts
tests/unit/TopNavBar.spec.ts

The build date is now shown in the Footer and a click on the top left product logo navigates to the MainDashboard page (as it used to do prior to the "about" dialog).
Fixes #102
This branch may be squashed-merged and deleted.
**Checklist**

00102 Remove about dialog and show build date in Footer

---

src/pages/AccountDetails.vue
src/pages/Nodes.vue
src/schemas/HederaSchemas.ts
tests/unit/Mocks.ts
tests/unit/account/AccountDetails.spec.ts

Add additional info to the AccountDetails page:
- Account or Node staked to
- Start of stake period
- Decline Reward
The current approach is to always show these fields (hence displaying None when they are null). A slight shuffling of the properties is also done to balance them between the 2 columns.
As usual, it may be arguable to completely hide these 3 properties when there is no staking for the account.
Fixes #120 
These properties are currently only exercised by unit tests, since preview and testnet always return null staking info.
Branch may be squashed-merged and deleted.
**Checklist**

120 - Add staking information in AccountDetails.

---

src/components/node/NodeTable.vue
src/pages/NodeDetails.vue
src/pages/Nodes.vue

*Description**:
With these trivial changes, the display of information related to staking in the Nodes and NodeDetails page is no longer subject to the environment variable VUE_APP_ENABLE_STAKING being set to true.
This branch may be squashed-merged and then deleted.
**Checklist**

Activate staking information on Nodes and NodeDetails page.

---

src/components/node/NodeTable.vue
src/pages/NodeDetails.vue
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

This PR fixes various issues in the display of data related to Node staking:
- number of decimals of percentages
- actually show percentages instead of ratios
- fix confusion between the values for one node and the totals for all nodes.
Fixes #138 
PreviewNet now shows certains Nodes which are staked. The numbers do not make any sense without the fixes...
**Checklist**

00138 Fix bugs and number of decimals shown in Node staking info.

---

src/components/node/NodeTable.vue
src/pages/NodeDetails.vue
src/pages/Nodes.vue
tests/unit/node/NodeTable.spec.ts

Previous PR for #138 left values in tinybars instead of hbars in Network section of Nodes.
Follow-up for #138 
Branch can be squashed and deleted.
**Checklist**

000138 Follow-up to fix for

---

src/components/node/NodeTable.vue
src/pages/AccountDetails.vue
src/pages/NodeDetails.vue
src/schemas/HederaSchemas.ts
src/utils/Duration.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/node/NodeDetails.spec.ts
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/utils/Duration.spec.ts
tests/unit/values/DurationValue.spec.ts

These changes add the display of Last Period Reward Rate (actually its approx. yearly equivalent) in:
- the NodeTable
- the NodeDetails page
PR also brings an unrelated shortening of time units when displaying a duration:
'1 day 2 hours 10 minutes 45 seconds' --> '1d 2h 10min 45s'
Fixes #142
**Checklist**

000142 last reward rate

---

src/pages/AccountDetails.vue
src/pages/ContractDetails.vue

This PR fixes the filtering of transactions shown in the details of a contract.
The contractId passed to the transaction cache  was not computed correctly, so it was not available for the first REST call, hence filtering was not happening.
Fixes #144 #145
**Checklist**

000144 contract txn filter

---

src/components/node/NodeTable.vue
src/components/staking/RewardsCalculator.vue
src/components/staking/StakingDialog.vue
src/pages/Nodes.vue
src/pages/Staking.vue
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

This PR mainly adds a new column in the Node Table which represents the Staking progress of a node compared to the minimum and maximum stake. This initial implementation is based on the standard _progress_ component and the layout of the min/max scale is CSS-based. This implies that, initially, all nodes share the same min and max stake.
Also included:
- A few trivial terminology changes (earning -> rewards)
- A disclaimer at the bottom of the RewardsCalculator (trivial)
- An explanatory note in the Staking dialog (less trivial, the layout had to be adjusted)
Fixes #122 
Branch may be squashed + deleted 
**Checklist**

00122 stake range

---

src/assets/styles/explorer-bulma.sass
src/components/staking/RewardsCalculator.vue
src/components/staking/StakingDialog.vue
src/utils/EntityID.ts
tests/unit/utils/EntityID.spec.ts

This brings on the fly input validation (and error messages) for the "Stake To Account" field of the StakingDialog. We wait 500ms after the last user input and go query the REST API to check that account exists.
The PR also brings a cosmetics change in RewardsCalcutator disclaimer notice.
Follow-up for #75
**Checklist**

Stake input validation

---

src/components/staking/RewardsCalculator.vue
src/pages/Staking.vue

Take the user balance as default value (instead of 100) for the amount staked, in the RewardsCalculator.
Fixes #153
**Checklist**

#153 - user balance as default in the RewardsCalculator

---

src/pages/Staking.vue
src/utils/wallet/WalletManager.ts
tests/unit/staking/Staking.spec.ts

Changes below 
- rename "Disconnect Wallet" button as "Disconnect [wallet name]".
- add validation logic to Staking vue unit test
Fixes #157
Branch can be squashed and deleted
**Checklist**

00157 should display connected wallet

---

src/components/staking/RewardsCalculator.vue

Changes below adds extra logic to #153 implementation.
This ensures that sequence below correctly:
1) Goto Staking page
2) Connect to Wallet A
=> user balance is used as default value for reward calculator : OK
3) Disconnect A
4) Connect to Wallet A (or B)
=> without this fix: user balance is no longer used as default (100 is) : KO
=> with this fix: user balance is used as default value for reward calculator : OK
Fixes #153 
Branch can be squashed and deleted.
**Checklist**

#153 follow-up: added some missing logic in RewardsCalculator

---

src/components/node/NodeTable.vue
src/components/values/HbarAmount.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/NodeDetails.vue
src/pages/Nodes.vue
src/pages/Staking.vue
tests/unit/Mocks.ts
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

These changes:
- Fix the stake range progress bars in the Nodes page. Values should be correct and the progress bars should show up in all cases, even with no staking.
- Address a couple of unrelated issues:
- get rid of recent warnings in unit tests
- display all amounts with thousands separators
Fixes #162
Branch may be squashed and deleted
**Checklist**

00162 fix stake range progress

---

src/App.vue
src/assets/styles/explorer-bulma.sass
src/assets/styles/explorer.scss
src/components/TopNavBar.vue
src/components/dashboard/DashboardItem.vue
src/pages/MobileMenu.vue
tests/unit/App.spec.ts
tests/unit/TopNavBar.spec.ts

With the following changes:
- Several responsiveness issues are fixed -- most important one being the TopNavBar just above the 1140 breakpoint, messed up on Safari
- The top-right 'Built-on-Hedera' logo is gone (at the request of mkt) -- the bottom-left one is still there of course
Fixes #92 
Responsiveness on Safari remains a bit sub-optimal compared to Chrome, since the media queries do not behave the same way. Painful.
**Checklist**

00092 topnavbar responsiveness

---

src/components/staking/RewardsCalculator.vue
src/components/staking/StakingDialog.vue
src/pages/AccountDetails.vue
src/pages/NodeDetails.vue
tests/unit/account/AccountDetails.spec.ts

These changes bring miscellaneous fixes and cosmetics changes around the Staking functionality:
- Fix unrewarded percentage in NodeDetails (was off)
- Fix node staking info displayed in node selector in RewardsCalculator and StakingDialog
- Display 'Stake for Consensus' amount with thousands separator in NodeDetails
- Show 'Rewards' property in AccountDetails only when staking to a Node
**Checklist**

Staking fixes and cosmetic changes

---

src/assets/styles/explorer.scss
src/components/node/NodeTable.vue
src/components/staking/RewardsCalculator.vue
src/pages/Staking.vue

This PR brings a set of unrelated fixes and cosmetic changes related to Staking:
- fix of opacity on Staking page (Txn table and Reward Estimator disabled in case of indirect staking)
- rename Rewards Calculator --> Rewards Estimator
- normalize transactionID received from wallet before querying the REST API with it
- indicate when node stake is < min instead of displaying 0% as its consensus weight
- these changes are deployed on staging server
- branch may be squashed and deleted
**Checklist**

Staking fixes

---

src/pages/NodeDetails.vue

1 line follow-up change for PR #167
Indicating Stake is '<Min' instead of '0% of total' also applies to NodeDetails page.
Branch may be deleted.
**Checklist**

Indicate node stake below min (instead of 0%) also in NodeDetails

---

src/components/node/NodeTable.vue
src/pages/NodeDetails.vue
src/pages/Nodes.vue
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

These changes:
- fix the computation of the "Total Rewarded" data on the Nodes page, now a sum of the `reward_rate_start` field for all nodes (instead of `stake_rewarded` field).
- do a bit of renaming
- start introducing tooltips for certain columns in the NodeTable.
Related to #177 (more to come in that chapter)
**Checklist**

Fix Last Period Reward on Nodes page.

---

src/utils/SearchRequest.ts
tests/unit/utils/SearchRequest.spec.ts

When:
- an hexadecimal value is entered in search  bar
- this value does not match any existing account alias
- number of bytes in this value is not 20 (ie evm address length)
then Explorer reports an error in place of "nothing found" message
Changes below:
- fix the issue above
- improve unit search unit tests
Fixes #00164
You can experiment with:
- https://hashscan.io
- 0102030405060708090102030405060708
**Checklist**

00164 improve search by account alias

---

src/AppStorage.ts
src/utils/wallet/WalletDriver_Hashpack.ts

When HashScan connects to HashPack, it currently saves some pairing data in browser's local storage.
The changes below disable this saving operation and pairing data are only preserved in memory until next page reload.
Although saving pairing data in Local Storage is the recommended way from HashPack API guide, this is an issue for HashScan's current UI design (we're missing a "clear pairing" button somewhere). 
So we propose to disable this persistence and come back later on this (with a new UI design).
With persistence disabled, connection UI flow remains unchanged.
However user has to choose target account in HashPack extension window each time she connects HashScan to HashPack.
**Checklist**

Stateless connect to hashpack

---

src/components/staking/RewardsTransactionCache.ts
tests/unit/Mocks.ts
tests/unit/staking/RewardsTransactionTable.spec.ts

This PR fixes the filtering of transactions which are paying rewards to the user.
Among all transactions related to the user account, we select those which have:
- an amount coming from 0.0.800
- and the same amount paid to the user account
That amount is considered the rewards amount.
**Checklist**

Fix filtering of rewards transactions

---

src/pages/Staking.vue
src/pages/TransactionDetails.vue

The Rewards Estimator was previously shown on the Staking page only once the user had connected a wallet.
And when the user had chosen to stake to another account, the RE was disabled.
With these changes, the RE is always shown and always enabled.
There is also an unrelated renaming of Transaction property: 'Node Account' -> 'Node Submitted To'
Fixes #179
These changes are currently deployed on the staging server.
**Checklist**

00179 rewards estimator always on

---

.env
src/components/staking/RewardsCalculator.vue

Signed-off-by: Simon Viénot <simon.vienot@icloud.com>
Title almost says everything...
With this change, the HTML content of the disclaimer notice shown at the bottom of the Rewards Estimator is now part of the branding, and empty by default.
Fixes #
Get an updated branding content to get back the initial notice.
**Checklist**

Make Rewards Estimator disclaimer notice part of branding.

---

src/components/node/NodeTable.vue
src/components/staking/StakeLoader.ts
src/pages/NodeDetails.vue
src/pages/Nodes.vue
src/schemas/HederaSchemas.ts
tests/unit/Mocks.ts
tests/unit/node/NodeDetails.spec.ts
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

- the new `api/v1/network/stake` REST API is used to obtain `stake_total` when available on a mirror-node. Otherwise this data is obtained from the node ( `api/v1/network/stake/node?node.id=:id` ) as was done previously.
- the code related to staking is refactored to always pass and manipulate tinybar (not hbar) amounts. Amounts staked are rounded down to the hbar, but only at the time of display.
- augment unit tests related to Node staking.
Fixes #186 
Branch may be deleted.
**Checklist**

00186 Adapt to new network/stake REST API

---

src/utils/EntityDescriptor.ts
src/utils/TransactionTools.ts

This PR modifies transactions list and transaction detail pages to fix `AccountID` mistaken for `TokenID`.
#191 
To see this, go to <https://hashscan.io/#/testnet/transaction/0.0.2032637-1659717478-488793135>, click the Token ID link `0.0.47848342`, result `Token with ID 0.0.47848342 was not found`. This is because that is an AccountID.
Same problem in the transaction list <https://hashscan.io/#/testnet/transactions>.
**Checklist**

Fixed AccountID mistaken for TokenID

---

.env
src/AppStorage.ts
src/assets/styles/explorer.scss
src/components/Footer.vue
src/components/ModalDialog.vue
src/components/staking/OptOutDialog.vue
src/components/staking/WalletChooser.vue
src/pages/Staking.vue
src/utils/EntityDescriptor.ts
src/utils/TransactionTools.ts
tests/unit/App.spec.ts
tests/unit/TopNavBar.spec.ts
tests/unit/staking/Staking.spec.ts

This PR mostly addresses modifications requested by legal team:
- Disclaimer popup shown before connecting a wallet. This is shown only when the envt variable VUE_APP_WALLET_CHOOSER_DISCLAIMER_POPUP (which contains the HTML content of the disclaimer message) is set.
- Display a mention on the Staking page related to the current phase of the staking deployment and the way it works
- Display a link to the static terms-of-use document in the footer, using the value of the envt variable VUE_APP_TERMS_OF_USE_URL (and only when it is set)
Also modifies the WalletChooser dialog to base it on selection + CANCEL/CONNECT buttons (double-click also works).
Fixes #
Currently deployed on staging server.
**Checklist**

Implement requests from legal team

---

src/assets/styles/explorer.scss
src/components/node/NodeLoader.ts
src/components/node/NodeTable.vue
src/pages/Nodes.vue
tests/unit/Mocks.ts
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

This PR changes the way we interpret the `reward_rate_start` field returned by `/api/v1/network/node` REST call.
It is currently interpreted as an amount served for 24h while it is in fact a rate served for 24h ( = number of tinybars rewarded per hbar staked).
Also fixes the tooltip for 'Stake' column in NodeTable.
Fixes #197
Without fix: ` <url>/testnet/nodes` shows 0% last reward rates for all nodes.
With fix: ` <url>/testnet/nodes` shows 6.5% instead.
**Checklist**

00197 reward rate is wrong

---

src/components/node/NodeCursor.ts
src/components/node/NodesLoader.ts
src/components/staking/RewardsCalculator.vue
src/components/staking/StakingDialog.vue
src/pages/NodeDetails.vue
src/pages/Nodes.vue
src/pages/Staking.vue
src/schemas/HederaSchemas.ts
src/utils/EntityBatchLoader.ts

Changes below complete code refactoring of fetchNodes() methods.
All vues having a fetchNodes() method now re-uses NodesLoader class.
Fixes #00196
**Checklist**

Code refactoring : replace fetchNodes() methods by NodesLoader class

---

src/components/node/NodeTable.vue
src/pages/AccountDetails.vue
tests/unit/Mocks.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

This simple PR uses the notification banner of the AccountDetails page to show when an account is deleted, identical to what is done in ContractDetails.
Also adds unit tests.
Fixes #204 
Look at <url>/#/testnet/contract/0.0.48170264 for instance. It says that the contract is deleted.
Follow the link to "Show the associated account". It does not mention the account is deleted.
With the fix, a similar banner is shown is both cases.
**Checklist**

00204 show account deleted

---

src/pages/TransactionDetails.vue
src/schemas/SystemContractRegistry.ts
tests/unit/Mocks.ts
tests/unit/transaction/TransactionDetails.spec.ts

In TransactionDetails, when the transaction is a CONTRACT CALL, we now check whether its entityID is one of the system contracts we know about (via SystemContractRegistry) and then display the system contract name instead of the ID with a (broken) link.
Fixes #215 
See: <url>#/mainnet/transaction/0.0.1107000-1662624593-105662235?t=1662624607.129656008
(fix deployed on staging)
**Checklist**

00215 system contract name

---

src/components/transaction/TransactionLoader.ts
src/pages/TransactionDetails.vue
src/utils/PathParam.ts
src/utils/SearchRequest.ts
tests/e2e/specs/SearchBar.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/utils/SearchRequest.spec.ts

Code changes below enables two features:
1) transaction hash can be used in search bar to display transaction details
2) transaction details page is now accessible using the following url:
`{url}/#/{network}/transaction/{transactionHash}`
Changes also include a refactoring : TransactionDetails.vue now delegates loading logic to TransactionLoader class.
Fixes #173
These two features relies on mirror node capability to search transaction using its hash.
At time of writing, this only works on previewnet.
To test search bar:
1) Go to [hashscan latest](https://hashscan-latest.hedera-devops.com)
2) Select `previewnet`
3) Paste the following transaction hash in search bar and press return: …

00173 search tx by hash

---

src/utils/PathParam.ts
tests/e2e/specs/AccountNavigation.spec.ts
tests/unit/utils/PathParam.spec.ts

With the changes below Explorer recognizes url with the following form:
`{url}/#/{network}/account/{account-alias-in-hex}`
Changes also include unit and e2e matching test cases.
Fixes #223
Test account on mainnet
Account ID: `0.0.1133968`
Account alias in base32: `CIQEN25ORE2F73TRYSYMMBVPR2HU4PPFGTQENJTIGVLLELP4PZ2M76A`
Account alias in hex: `0x122046ebae89345fee71c4b0c606af8e8f4e3de534e046a6683556b22dfc7e74cff8`
**Checklist**

#223 Display account details using {url}/#/{network}/account/{account-alias-in-hex}

---

src/components/Property.vue
src/components/values/AliasValue.vue
src/pages/AccountDetails.vue
tests/unit/account/AccountDetails.spec.ts
tests/unit/values/AliasValue.spec.ts

This PR adds a new AliasValue component, now used by AccountDetails, which displays both the base32 encoding and the hexadecimal forms of the alias value, on 2 successive lines.
The Property component is also enhanced to be used when there is a single column of properties taking the whole width.
This fixes the previous alias layout issue ("in the middle of the page")
Fixes #225 
**Checklist**

00225 display hex form of account alias

---

src/pages/ContractDetails.vue

This PR modifies the _Code_ label to _Initcode_ (thanks @steven-sheehy).
Advantages:
* _Code_ can be mistaken by the actual deployed bytecode. Currently, you cannot recover the deployed bytecode via REST API. That bytecode is the actual [`initcode`](https://github.com/hashgraph/hedera-protobufs/blob/71e0b20b25aee4369c19c66eacdf5a97e5ca61bd/streams/contract_bytecode.proto#L39)
* We use consistent terminology across Hedera's applications
N/A
N/A
**Checklist**

Updated Code label

---

src/components/node/NodeTable.vue
src/components/staking/RewardsCalculator.vue
src/components/staking/StakingDialog.vue
src/schemas/OperatorRegistry.ts
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

This merges the `Hosted By` and `Location` columns of the Node table into a single one name `Description`.
The `Description` column will eventually display raw content from NetworkNode.description field (obtained via `/api/v1/network/nodes` call) once that data is populated. The Node description is currently fetched from the local, static information provided by OperatorRegistry.
Fixes #132
**Checklist**

00132 merge node hostedby and location

---

README.md

Update README to describe how setting `VUE_APP_ENABLE_STAKING=true` in `.env` file will activate the Staking page and corresponding TopNavBar menu item.
Fixes #230

00230 Update README for Staking.

---

.env
package.json
src/components/TopNavBar.vue
src/pages/MobileMenu.vue
src/router.ts
tests/unit/App.spec.ts
tests/unit/TopNavBar.spec.ts

With these simple changes, we remove the .env variable VUE_APP_ENABLE_BLOCKS and the code which depended upon it to conditionally activate the Blocks pages, TopNavBar menu item, and route.
None.
**Checklist**

Remove code for conditional activation of Blocks pages.

---

src/components/staking/RewardsCalculator.vue
tests/unit/staking/RewardsCalculator.spec.ts

- Fix regression in RewardsCalculator caused by the fact the recent refactoring around the use of NodesLoader/NodeCursor was not complete.
- Add a unit test for RewardsCalculator.
Fixes #234
Have a look at <url>/#/testnet/staking page and try to select a node in the Rewards Estimator section
-> without the fix (on staging): the options of the select are broken, all Reward values are zero.
-> with the fix: the 7 node descriptions are listed, and once a node selected, the Reward values should be non zero.
**Checklist**

00234 regressions in rewards estimator

---

src/pages/BlockDetails.vue
tests/unit/Mocks.ts
tests/unit/block/BlockDetails.spec.ts
tests/unit/block/Blocks.spec.ts

- Disable the PREV.BLOCK and NEXT BLOCK buttons on the BlockDetails page when the block was not found or when the block locator is invalid
- Add unit tests for Blocks and BlockDetails components
Fixes #238
Load "<url>/#/testnet/block/12"
then load "<url>/#/testnet/block/555555555555555"
with the fix, PREV/NEXT buttons should be disabled
**Checklist**

00238 disable prev/next block buttons when block not loaded

---

src/components/staking/StakingDialog.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/TokenDetails.vue
src/pages/TopicDetails.vue
src/schemas/NetworkRegistry.ts
src/utils/EntityID.ts
tests/unit/staking/Staking.spec.ts
tests/unit/staking/StakingDialog.spec.ts
tests/unit/token/TokenDetails.spec.ts

- Details pages for Account/Contract/Token/Topic display a with-checksum form of the entity ID (per HIP-15).
- The StakingDialog will accept both with- and without-checksum forms of the stakedTo account ID.
Fixes #209 
**Checklist**

209 Publish checksum of addresses

---

src/components/account/AccountLoader.ts
src/components/transaction/TransactionByTimestampLoader.ts
src/pages/AccountDetails.vue
src/schemas/HederaSchemas.ts
src/utils/TransactionID.ts
tests/e2e/specs/TransactionNavigation.spec.ts
tests/unit/Mocks.ts
tests/unit/account/AccountDetails.spec.ts

With these changes, the new `created-timestamp` property of `AccountInfo` is used to query the corresponding `ACCOUNT CREATE` or `CONTRACT CREATE` transaction. To that end, a new `TransactionByTimestampLoader` is introduced.
Fixes #135 
This only works for now on a local mirror node. Otherwise (in the absence of `created-timestamp` property) we display `None`. 
**Checklist**

00135 show create transaction

---

src/components/transaction/TransactionTableControllerXL.ts
src/utils/table/TableController.ts
tests/unit/transaction/TransactionTableController.spec.ts
tests/unit/utils/TableController.spec.ts

AccountDetails calls TransactionTableController.mount() and then initializes TransactionTableController.accountId.
TransactionTableController does not handle this flow correctly.
Changes below:
- fix TransactionTableController logic in charge of watching accountId
- add a unit test for TransactionTableController
Fixes #260
#260 provides instructions for reproducing the problem.
**Checklist**

00260 Last Transactions table in Account details does not preserve selected page

---

src/pages/TokenDetails.vue
src/utils/EntityID.ts
tests/unit/utils/EntityID.spec.ts

Changes below complete the work related to EIP 3090.
- http 400 reported when displaying token details using `{url}/token/{TOKEN_ADDRESS}` is fixed
- parsing of `TokenDetails.prop.tokenId` is now performed using `EntityID.parse()` and `EntityID.fromAddress()` methods
- new unit tests are available for `EntityID.fromAddress()`
Fixes #62
Sample URL for testing:
https://localhost:8080/#/testnet/token/0x0000000000000000000000000000000002e615e7
**Checklist**

00062 Add EIP 3091 Support

---

src/router.ts
tests/e2e/specs/AccountNavigation.spec.ts
tests/e2e/specs/BlockNavigation.spec.ts
tests/e2e/specs/BlocksResponseCollector.spec.ts
tests/e2e/specs/ContractNavigation.spec.ts
tests/e2e/specs/CopyHexaToClipboard.spec.ts
tests/e2e/specs/NodeNavigation.spec.ts
tests/e2e/specs/PageNotFound.spec.ts
tests/e2e/specs/SearchBar.spec.ts
tests/e2e/specs/TokenInfoCollector.spec.ts
tests/e2e/specs/TokenNavigation.spec.ts
tests/e2e/specs/TopicNavigation.spec.ts
tests/e2e/specs/TransactionNavigation.spec.ts
tests/e2e/specs/TransferGraphs.spec.ts

- the 'history' mode of Vue Router is used instead of the 'hash' mode.
- a rewrite of the old hash-based routes is temporarily in place for compatibility
- the e2e tests are adjusted to the
Fixes #264 
**Checklist**

00264 router html5 history

---

src/pages/Staking.vue
tests/e2e/specs/NodeNavigation.spec.ts

- Adjust e2e test following temporary removal of link allowing to navigate to NodeDetails from AccountDetails (when on a node's account).
- (unrelated:) Remove a couple bindings for static props.
Follow-up for #269 
**Checklist**

00269 follow up

---

src/components/staking/RewardsCalculator.vue
src/components/staking/RewardsTransactionTableController.ts
src/components/staking/StakingDialog.vue
src/pages/Staking.vue
src/schemas/HederaSchemas.ts
tests/unit/staking/RewardsCalculator.spec.ts

With these changes, the description of the nodes provided in the node selectors (StakingDialog and RewardEstimator) now includes the number of hbars staked which have declined reward.
Also in this PR (and unrelated):
- Fix bug when staked to (or trying to stake to) Node 0
- Remove placeholder mention of transaction cost
- Disable auto-refresh of RewardsTransactionTable and remove related PlayPauseButton control. 
Fixes #275 
**Checklist**

00275 indicate staked with no reward

---

src/components/transaction/TransactionLoader.ts
src/pages/TransactionDetails.vue

With this simple fix, we now try to get the contract result related to the currently displayed transaction **only when** the type of the transaction is one of { CONTRACT CREATE, CONTRACT CALL, ETHEREUM TRANSACTIOn }.
None.
Without the fix, the following page:
`<url>/mainnet/transaction/0.0.706113-1666377820-433121761?t=1666377870.801135355`
triggers an error 500 (which itself is likely an issue in mirror-node) caused by the unduly call to `api/v1/contracts/results/0.0.706113-1666377820-433121761`
**Checklist**

Do not query contract results when not needed

---

src/pages/NoSearchResult.vue
src/schemas/HederaSchemas.ts
src/utils/SearchRequest.ts
tests/unit/utils/SearchRequest.spec.ts

Changes below implement #280.
Fixes #280 
Account `0.0.1133968` (on mainnet) can be searched using its:
id : `0.0.1133968`
ethereum address: `0x0000000000000000000000000000000000114d90`
alias: `CIQEN25ORE2F73TRYSYMMBVPR2HU4PPFGTQENJTIGVLLELP4PZ2M76A`
public key: `0x46ebae89345fee71c4b0c606af8e8f4e3de534e046a6683556b22dfc7e74cff8`
**Checklist**

00280 Explorer should enable to search an account using its public key

---

src/components/staking/StakingDialog.vue
src/components/transaction/TransactionByIdTable.vue
src/components/transaction/TransactionLoader.ts
src/components/values/TimestampValue.vue
src/pages/NoSearchResult.vue
src/pages/TransactionDetails.vue
src/schemas/HederaSchemas.ts
src/utils/SearchRequest.ts
src/utils/TransactionTools.ts
tests/e2e/specs/SearchBar.spec.ts
tests/e2e/specs/TransactionNavigation.spec.ts
tests/unit/Mocks.ts
tests/unit/transaction/TransactionByIdTable.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/utils/SearchRequest.spec.ts

With these changes, we clarify the way transaction relationship (parent/child, scheduling/scheduled) are presented.
In particular for parent/child, we come back to a traditional `Scheduled: True/False` property display, but with an underline link to navigate to the related transaction.
We also fix the detection of parent/child relationship: A transaction needs a `parent_consensus_timestamp` property to be considered a child.
Fixes #279 #256 
This is deployed on the staging server.
Example of scheduling/scheduled transactions:
<url>/mainnet/transaction/0.0.503733-1666754898-238965661
Example of parent/child transactions:
<url>/mainnet/transaction/0.0.846260-1666766635-282429759
Example of unrelated transactions (but same ID) …

00279 clarify transaction relationships

---

src/components/transfer_graphs/NftTransferGraph.vue

Changes below fix layout issue reported in #208.
This bug affects NFT transfer diagrams displayed in « compact mode » (ie displayed in table, not in detail page).
Fixes #208
Samples for testing:
- https://hashscan-latest.hedera-devops.com/mainnet/transactionsById/0.0.1112484-1666801627-219198139
- https://hashscan-latest.hedera-devops.com/testnet/transactionsById/0.0.11495-1662470792-231322900
**Checklist**

00208 Transfer diagram with a strange (ugly) layout).

---

src/components/transfer_graphs/HbarTransferGraphF.vue
src/components/transfer_graphs/layout/HbarTransferLayout.ts
tests/unit/transfer_graphs/layout/HbarTransferLayout.spec.ts

Changes below implement enhancement reported in #285 and extend unit tests.
See #285 for details and spec.
Fixes #285
Some transactions for testing:
- /mainnet/transaction/0.0.705448-1666863985-824064119
- /testnet/transaction/0.0.47623543-1666885169-874712610
**Checklist**

00285 Improve Hbar Transfer graph when destinations are all 'fee collector accounts'

---

src/components/token/FixedFeeTable.vue
tests/unit/Mocks.ts
tests/unit/token/TokenDetails.spec.ts
tests/unit/utils/Collector.spec.ts

Fix for the case where token custom fixed fees are collected in hbar instead of another fungible token. The amount has to be displayed as a number of hbars instead of a plain amount.
Fixes #288 
Instructions to reproduce in issue #288 
**Checklist**

00288 fixed fee amount in hbar

---

src/utils/table/TableController.ts
tests/unit/utils/TableController.spec.ts

Changes below fix issue #292. See issue for details.
Fixes #292.
See #292.
**Checklist**

00292 Setting a transaction type in Transactions table triggers duplicated api/v1/transactions requests

---

src/router.ts
tests/e2e/specs/HomePage.spec.ts

All is said in the title...
Fixes #290 
Try to navigate to `{url}/#/testnet/token/0.0.48789573` (or any other page).
- Before this change (with the compat. code) there is a redirect to: `{url}/testnet/token/0.0.48789573`
- With this change, (compat. code removed) the redirect is to:  `{url}/testnet/dashboard`
**Checklist**

00290 Remove compatibility with previous hash-based URL structure

---

package-lock.json
package.json
src/components/values/ComplexKeyValue.vue
src/components/values/KeyValue.vue
src/utils/ComplexKeyLine.ts
tests/unit/utils/ComplexKeyLine.spec.ts
tests/unit/values/ComplexKeyValue.spec.ts

Changes below enable Explorer to decode and display complex keys (aka protobuf encoded keys).
Fixes #131 
Sample accounts with complex keys (on mainnet):
- [0.0.2](https://hashscan-latest.hedera-devops.com/mainnet/account/0.0.2) // The big one
- [0.0.4](https://hashscan-latest.hedera-devops.com/mainnet/account/0.0.4?p3=1&k3=1667487924.110982197&p2=1&k2=1667488019.986301071&p1=1&k1=1667488019.743429090&p=1&k=1667488037.609174426)
- [0.0.88](https://hashscan-latest.hedera-devops.com/mainnet/account/0.0.88)
- [0.0.800](https://hashscan-latest.hedera-devops.com/mainnet/account/0.0.800) // The strange one
**Checklist**

00131 HashScan should display the structure of complex keys

---

src/components/transaction/TransactionTableControllerXL.ts
src/pages/AccountDetails.vue
tests/unit/transaction/TransactionTableControllerXL.spec.ts

Changes below override previous fix for #307 which is not working correctly.
#307 cannot be fixed correctly at TableController level.
It is now fixed at AccountDetails page level.
Fixes #307
Fix is deployed on staging server:
https://hashscan-latest.hedera-devops.com/mainnet/account/0.0.21
**Checklist**

00307 Navigating back from Transaction details to Account details does not preserve pagination (Take #2)

---

.env
src/router.ts

The following changes make use of new environment variables to control the meta tags:
- `property="og:url"` 
- `name="description"`
They also rework the structure of the document title and set the meta tag `property="og:title"` with the same value.
Fixes #305

00305 fix html meta tags

---

.run/serve_https with branding.run.xml
src/components/values/TransactionLink.vue
src/pages/AccountDetails.vue
src/pages/Staking.vue
tests/unit/Mocks.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/staking/Staking.spec.ts

With these changes, the AccountDetails view will display one of the following:
- `Staked to Node ........... NN hosted by XYZ`
- `Staked to Account ........ 0.0.12345`
- `Staked to ................ None`
Also, the stake_period_start is now displayed including its UTC time in addition to the date.
Fixes #317 
Examples:
- [account staking to node](https://hashscan-latest.hedera-devops.com/testnet/account/0.0.47813131)
- [account staking to another account](https://hashscan-latest.hedera-devops.com/testnet/account/0.0.15818224)
- [account not staking](https://hashscan-latest.hedera-devops.com/testnet/account/0.0.3)
**Checklist**

00317 staking fixes

---

src/components/SearchBar.vue
src/pages/NoSearchResult.vue
src/utils/SearchRequest.ts
tests/unit/utils/SearchRequest.spec.ts

Changes below re-enable searching account using alias in hexadecimal form and add extra unit test.
Fixes #331
Account `0.0.1133968` (on _mainnet_) can now be searched using:
- its entity id : `0.0.1133968`
- its short entity id : `1133968`
- its alias : `CIQEN25ORE2F73TRYSYMMBVPR2HU4PPFGTQENJTIGVLLELP4PZ2M76A`
- its alias in hex form: `0x122046ebae89345fee71c4b0c606af8e8f4e3de534e046a6683556b22dfc7e74cff8`
- its public key: `0x46ebae89345fee71c4b0c606af8e8f4e3de534e046a6683556b22dfc7e74cff8`
**Checklist**

00331 (re-enable search using hex form of alias)

---

src/pages/NoSearchResult.vue
src/utils/SearchRequest.ts
tests/e2e/specs/SearchBar.spec.ts

These changes allow to search transactions using their timestamp using the Hedera format:  "seconds.nanoseconds"
Fixes #314 
**Checklist**

00314 search txn using timestamp

---

src/components/Footer.vue
tests/e2e/specs/LegalNotices.spec.ts

Simple fix to make the link to the terms-of-use.tml notice absolute . The relative link was working with the hash mode of the router, but no longer with html history mode.
Also add an e2e test for the legal notices.
Fixes #334 
**Checklist**

00334 fix footer link to terms-of-use.html

---

src/App.vue
src/assets/styles/explorer.scss
src/components/topic/TopicMessage.vue
src/components/topic/TopicMessageLoader.ts
src/components/topic/TopicMessageTable.vue
src/components/values/BlobValue.vue
src/pages/TransactionDetails.vue
src/schemas/HederaSchemas.ts
tests/e2e/specs/TopicNavigation.spec.ts

- the TransactionDetails view includes the details of the Topic Message when the type of the transaction is `CONSENSUSSUBMITMESSAGE`.
- the TopicMessageTable allows to navigate to the details of the corresponding transaction.
Fixes #16 
Deployed to staging environment (or should be in a short while...)
**Checklist**

00016 display message content in HCS SUBMIT MESSAGE transaction

---

src/pages/AccountDetails.vue
tests/e2e/specs/AccountNavigation.spec.ts

This is a one-line fix for the broken link from AccountDetails view to ContractDetails view when the initial navigation to the account used an EVM address.
Relates to #338 
**Checklist**

00338 fix navigation from account to contract with evm address

---

src/components/contract/ContractResult.vue
src/components/contract/ContractResultDetailsLoader.ts
src/components/transaction/TransactionLoader.ts
src/pages/TransactionDetails.vue
tests/e2e/specs/ContractResultDetails.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

- With these changes, the `TransactionDetails` view now displays the contract result (if any exists) in all cases, whatever the type of the transaction.
- Furthermore, we pick up the result based on the consensus timestamp of the transaction, whereas we were previously picking up the result based on the transactionId. This means that in the case of a child transaction, we show its corresponding contract result, whereas we were previously always showing the result corresponding to the parent transaction.
- Note that when getting a contract result based on timestamp only (i.e. `transaction.entity_id` is not a contractId) we first make a synchronous call to `/api/contracts/results?timestamp={timestamp}` to retrieve the contractId and then call …

00340 contract result for child transactions

---

src/utils/EntityID.ts
tests/unit/utils/EntityID.spec.ts

Fix and unit test for #351.
Fixes #351
On staging server:
1) search for transaction 1669904326.061513245 (on mainnet)
2) look for sender argument in Contract Result section 
=> account id 0.0.-563671129890724300 is displayed (it should not)
**Checklist**

Fix for #351 (EntityID.fromAddress() should be more robust).

---

src/components/transfer_graphs/HbarTransferGraphC.vue

One line fix: HbarTransferGraphC.setup() forgot to pass "false" value to HbarTransferLayout.
Fixes #353
See #353 for instructions.
**Checklist**

Fix for #353 (Broken transfer diagram).

---

src/components/staking/RewardsTransactionTable.vue
src/components/staking/RewardsTransactionTableController.ts
src/schemas/HederaSchemas.ts
src/utils/downloader/EntityDownloader.ts
src/utils/downloader/RewardDownloader.ts
src/utils/downloader/TransactionDownloader.ts

With changes below, Explorer now uses `api/v1/account/{accountId}/rewards` to fill `Recent Staking Rewards` table in `Staking` tab.
This API is available on preview net only for now.
When testnet or mainnet are selected, Explorer fallback using `api/v1/transactions`.
Fixes #313
**Checklist**

00313 use reward api

---

.env
src/components/TopNavBar.vue
src/pages/MobileMenu.vue
src/utils/RouteManager.ts

With these changes, the route logic currently still in TopNavBar and MobileMenu is moved to RouteManager.
This will later allow RouteManager to centralise logic related to network switching (i.e clearing the contents of Collectors and reloading the contents of NodesLoader singleton).
Fixes #371 
Should be deployed shortly to staging server.
**Checklist**

00371 move route logic to RouteManager

---

src/components/TopNavBar.vue
src/pages/MobileMenu.vue
src/utils/RouteManager.ts
src/utils/collector/Collector.ts

With these simple changes, the contents of `TransactionCollector`, `TransactionByHashCollector` , `TokenInfoCollector` and `BlockResponseCollector` is cleared by `RouteManager` when switching networks.
Fixes #369 
**Checklist**

00369 clear collectors when switching

---

src/components/staking/StakingRewardsTableController.ts
src/pages/AccountDetails.vue
src/utils/downloader/RewardDownloader.ts
src/utils/table/TableController.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/node/NodeDetails.spec.ts
tests/unit/staking/Staking.spec.ts

Changes below:
- display staking rewards in account details page (if `api/v1/accounts/{accountId}/rewards`  is available)
- remove logic emulating reward collection using `api/v1/transactions`
Fixes #276
**Checklist**

00276 show rewards in accountdetails

---

src/pages/AccountDetails.vue
src/pages/TokenDetails.vue
tests/unit/Mocks.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/token/TokenDetails.spec.ts

- the AccountDetails view now displays the _Ethereum Nonce_ property
- the property _Ethereum Address_ has been renamed _EVM Address_ in the AccountDetails view, for consistency with the ContractDetails view and to avoid any confusion with a real Ethereum Address.
Fixes #385 
**Checklist**

00385 display ethereum nonce

---

.run/serve_https with branding.run.xml
src/components/values/AliasValuev2.vue
src/pages/AccountDetails.vue
src/pages/NoSearchResult.vue
tests/unit/account/AccountDetails.spec.ts

- the "no search result" inline help now provides examples of all supported search patterns
- the "no search result" inline help now gives length in “characters” instead of "bytes"
- in the "no search result" page as well as the "account details" view, the following terminology is used:
-  “public-key-format alias” instead of "alias"
-  “Ethereum-format alias” instead of "EVM Address"
- in the "account details" view, the _public-key-format alias_ is made less prominent, and displayed in hexa, next to the _Admin Key_
Note it is still possible to search using base32 and hexa forms of _public-key-format alias_
Fixes #389 
This is currently being deployed on staging.
**Checklist**

00389 improve help text

---

src/components/account/AccountLoader.ts
src/components/token/TokenRelationshipLoader.ts
src/components/transaction/TransactionSummary.vue
src/pages/TransactionDetails.vue
src/schemas/HederaSchemas.ts
src/utils/TransactionTools.ts
src/utils/loader/EntityBatchLoader.ts
tests/unit/Mocks.ts
tests/unit/dashboard/MainDashboard.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

With the following changes, the TransactionDetails view displays the ID of the token(s) associated to an account when the transaction type is TOKEN ASSOCIATE. The recent /api/v1/accounts/{id}/tokens API is used to retrieve all tokens associated with that account, and those with a created_timestamp matching the consensus_timestamp of the transaction are picked up.
Fixes #136
This is a best effort approach. An account may have a very large number of tokens associated, so we only get the associated tokens up to 1000 to keep things reasonable.
Another limit to this approach is that /api/v1/accounts/{id}/tokens describes the current situation. If the TOKEN ASSOCIATE has been followed by a TOKEN DISSOCIATE before we try to display …

00136 token associate txn info

---

src/components/contract/ContractLoader.ts
src/pages/ContractDetails.vue
src/schemas/HederaSchemas.ts
tests/unit/Mocks.ts
tests/unit/contract/ContractDetails.spec.ts

This PR brings the following changes to the ContractDetails view:
- add the display of these properties:
- _Auto Renew Account_ (specific to contract)
- _Create Transaction_ (aligning with AccountDetails view)
- _Max. Auto. Association_ (aligning with AccountDetails view)
- remove the property _Alias_ (not a contract property)
Fixes #399 
**Checklist**

00399 add auto renew account property to contracts

---

src/pages/TransactionDetails.vue
tests/unit/Mocks.ts
tests/unit/transaction/TransactionDetails.spec.ts

One-line fix to make sure DurationValue displays none when the value is null.
Fixes #400
**Checklist**

Display None when transaction duration value is null.

---

src/components/transaction/TransactionSummary.vue
src/utils/TransactionTools.ts

With these simple changes, we cover a number of transaction types for which TransactionSummary has not yet been updated:
- `ETHEREUMTRANSACTION`
- `CRYPTOADDLIVEHASH`
- `CRYPTODELETELIVEHASH`
- `TOKENWIPE`
- `CRYPTOAPPROVEALLOWANCE`
- `CRYPTODELETEALLOWANCE`
Fixes #408
**Checklist**

00408 Complete TransactionSummary for missing types.

---

src/components/contract/ContractResultDetailsLoader.ts

This PR fixes the logic for getting the contract result corresponding to an ETHEREUM TRANSACTION with no corresponding contractId provided by the API.
Fixes #411 
Without the fix, we fail to retrieve the contract result for this transaction:
https://hashscan.io/testnet/transaction/1673808122.180036003
**Checklist**

00411 Fix fetch logic for contract result in case of ETHEREUM TX

---

src/components/staking/StakingDialog.vue
src/components/token/FixedFeeTable.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue

This µPR removes  a few undue v-bind used with constant timestamp props.
None.
**Checklist**

Remove undue v-bind for constant timestamp props.

---

src/components/values/DurationValue.vue
src/components/values/TimestampValue.vue
src/schemas/HederaSchemas.ts
src/utils/Duration.ts
tests/unit/values/DurationValue.spec.ts
tests/unit/values/TimestampValue.spec.ts

With the following changes:
- We specify the number of years for very large durations.
- We interpret very large durations as _infinite_ and very remote timestamp as _never_
Fixes #366 
Currently deploying on staging server.
Example of account with large `auto-renew-period` (in years): `{server}/mainnet/account/0.0.200`
Example of account with infinite `auto-renew-period` and `expiry-timestamp`: `{server}/mainnet/account/0.0.400`
**Checklist**

00366 auto renew period unit

---

src/pages/ContractDetails.vue
tests/unit/contract/ContractDetails.spec.ts

Trivial change to disable the "grace period"  message displayed when an account is past `expiration-timestamp` and not yet deleted -- until this behaviour is deployed on mainnet in February.
Fixes #420 
Temporarily disables corresponding unit test and adds a test to check the message does not show up.
**Checklist**

00420 Temporarily disable notification of contract in grace period.

---

tests/e2e/specs/AccountNavigation.spec.ts
tests/e2e/specs/AdminKeyDetailsNavigation.spec.ts
tests/e2e/specs/BlockNavigation.spec.ts
tests/e2e/specs/BlocksResponseCollector.spec.ts
tests/e2e/specs/ContractNavigation.spec.ts
tests/e2e/specs/ContractResultDetails.spec.ts
tests/e2e/specs/SearchBar.spec.ts
tests/e2e/specs/TokenInfoCollector.spec.ts
tests/e2e/specs/TokenNavigation.spec.ts
tests/e2e/specs/TopicNavigation.spec.ts
tests/e2e/specs/TransactionNavigation.spec.ts

This updates the end-to-end tests such that they no longer depend upon specific testnet entities, which causes them to break after a reset of testnet. When a specific entity _has to_ be hardcoded in the tests we use one from mainnet.
None.
A few tests are still skipped. We still need to find a couple example of accounts such as: auto-created or associated to a very limited number of tokens.
**Checklist**

Update e2e tests after testnet reset

---

src/pages/NoSearchResult.vue

Trivial 1-line change to disable the related help text on NoSearchResult view.
Fixes #435

00435 Temporarily disable help text related to searching by tx hash

---

src/pages/MainDashboard.vue

Changes below make sure that Dashboard tab re-enables auto-refresh after network switch.
Fixes #446
See instructions to reproduce issue in #446.
**Checklist**

00446 switching network when Dashboard tab is displayed does not update tables correctly 

---

.env
.env.docker
README.md
package.json
public/networks-config.json
src/App.vue
src/components/TopNavBar.vue
src/pages/MainDashboard.vue
src/pages/MobileMenu.vue
src/schemas/NetworkRegistry.ts
tests/unit/App.spec.ts

With the following changes, the configuration of the available networks is now provided by the `networks-config.json` configuration file located at the root of the distribution (next to index.html). This file contains by default the configuration for using mainnet/testnet/previewnet, which can be completed/replaced as needed.
The `VUE_APP_LOCAL_MIRROR_NODE_URL/VUE_APP_LOCAL_MIRROR_NODE_NAME` environment variables are still supported but their use is deprecated.
Fixes #439 
Details of the behaviour/limitations in the README.
**Checklist**

00439 custom network configuration

---

src/components/staking/ProgressDialog.vue
src/pages/Staking.vue
src/utils/wallet/WalletDriver_Blade.ts
src/utils/wallet/WalletDriver_Hashpack.ts
tests/unit/staking/Staking.spec.ts
tests/unit/staking/WalletDriver_Mock.ts

With changes below, **Change/Stop Staking** actions now use `api/v1/transactions/{transactionId}` to poll mirror node.
Fixes #451 
See #451
**Checklist**

00451 change and Stop Staking actions should not invoke api/v1/transactions/{transactionHash}

---

src/pages/AddressDetails.vue
src/pages/ContractDetails.vue
src/router.ts
src/utils/PathParam.ts
src/utils/RouteManager.ts
tests/e2e/specs/AccountNavigation.spec.ts

Changes below modify Explorer behavior when interpreting `{network}/address/{evmAddress}` URL (see [EIP 3091](https://eips.ethereum.org/EIPS/eip-3091)).
Explorer now first checks if `evmAddress` matches a contract and routes to `Contract Details` page in priority.
Fixes #454
Uses the following URL:
https://localhost:8080/mainnet/address/0x00000000000000000000000000000000001e1b47
Without changes below, it displays `Account Details` for 0.0.1973063.
With the changes, it shows `Contract Details` for 0.0.1973063.

Fix for #454 (compatibility with MetaMask).

---

src/components/SearchBar.vue
src/pages/NoSearchResult.vue
src/utils/PathParam.ts
src/utils/SearchRequest.ts
tests/unit/utils/SearchRequest.spec.ts

The changes below add support for:
- navigating to `:network/blocks/:32-byte-hash-prefix`
- searching blocks by block hash (48 bytes) or block hash prefix (32 bytes)
Fixes #426
**Checklist**

426 search blocks by hash

---

src/components/contract/ContractResult.vue
src/components/contract/ContractResultDetailsLoader.ts
tests/unit/Mocks.ts
tests/unit/contract/ContractResult.spec.ts

With the following changes, the error message returned by a contract that reverts is decoded and displayed in a human readable manner when it contains a string.
Fixes #434 
**Checklist**

00434 decode contract error message if string

---

src/components/contract/ContractActionDetails.vue
src/components/contract/ContractResultDetailsLoader.ts
src/schemas/HederaUtils.ts

- Contract revert error message is decoded also for elements of the Call Trace
- We decode Panic(uint256) as well as Error(String)
Fixes #434 (follow-up)
UI shown in comments of issue #434.
**Checklist**

00434 Decode error message in contract call trace.

---

src/pages/AddressDetails.vue

Changes below modify logic in AddressDetails so that AccountDetails is displayed even if account does not exist.
Then the following page is displayed:
Fixes #478 471
Sample URL:
https://localhost:8080/testnet/account/0xcd6c43084c8b9db93545213ae24f1d51e2b1e878

00471 show an account page for not yet created accounts

---

src/components/node/NodeTable.vue
src/schemas/HederaSchemas.ts
tests/unit/staking/RewardsCalculator.spec.ts

This fixes the % of stake displayed in the node selector.
- if total-stake < min we display `Not Rewarding (total stake is X% of min)` with X = total-stake/min*100
- otherwise we display  `Rewarding (stake rewarded is Y% of max)` with Y = rewarded-stake/max*100
Fixes #490 
**Checklist**

00490 misleading stake percentage

---

src/pages/AccountDetails.vue
src/pages/TokenDetails.vue
tests/unit/account/AccountDetails.spec.ts
tests/unit/node/NodeDetails.spec.ts
tests/unit/token/TokenDetails.spec.ts

For entities (Token, Account) which do not yet have the auto-renew feature enabled, we replace the values of properties _Auto Renew Period_ & _Auto Renew Account_ by the mention `Not yet enabled`.
Fixes #442
See screenshots in issue #442
**Checklist**

00442 remove auto renew where not yet enabled

---

src/components/transaction/TransactionLoader.ts
src/components/transaction/TransactionSummary.vue
src/components/transfer_graphs/NftTransferGraph.vue
src/components/transfer_graphs/TransferGraphSection.vue
src/components/transfer_graphs/layout/NFTTransferLayout.ts
src/schemas/HederaSchemas.ts
tests/unit/transfer_graphs/NftTransferGraph.spec.ts

Following changes are housekeeping.
`Transaction` declaration in `HederaSchema.ts` does actually match `TransactionDetail` declaration from [Mirror Node API](https://previewnet.mirrornode.hedera.com/api/v1/docs/).
This PR splits `Transaction` into `Transaction` and `TransactionDetail` and makes `TransactionDetail` extends `Transaction`.

Housekeeping: Transaction vs TransactionDetail

---

src/components/values/AccountLink.vue
tests/e2e/specs/NodeNavigation.spec.ts

This is a fix for AccountLink -- props.accountId not always defined at mount, so it must be watched.
E2E tests also need a fix since AccountLink has async logic.
None.
**Checklist**

Fix account link

---

src/components/allowances/ApproveAllowanceDialog.vue
src/components/contracts/ContractResultsSection.vue
src/components/transaction/TransactionAnalyzer.ts
src/components/values/TokenAmount.vue
src/components/values/TokenExtra.vue
src/pages/ContractDetails.vue
src/pages/TokenDetails.vue
src/pages/TransactionDetails.vue
src/router.ts
src/utils/EntityDescriptor.ts
src/utils/cache/TokenInfoCache.ts
tests/e2e/specs/TokenNavigation.spec.ts
tests/unit/token/TokenDetails.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

- we check whether the entity ID in a CONTRACT CALL transaction is a contract ID or a token ID and adjust the property label and router link accordingly
- we display a table of recent call results in TokenDetails (when they exist -- i.e. the token has been proxied as a contract)
Unrelated house-keeping:
- rename TransactionDetailsV2 to TransactionDetails 
Fixes #494
Feature currently deployed on staging.
**Checklist**

00494  Entity ID in Contract Call transactions is in certain cases a token ID

---

src/pages/ContractDetails.vue
src/pages/TokenDetails.vue
src/utils/cache/base/EntityCache.ts

Changes below are refactoring. No semantic change.
`ContractDetails` and `TokenDetails` views now using `Lookup.isLoaded()` routine to avoid transient error banner.

Refactoring

---

src/components/node/NodeTable.vue
src/pages/NodeDetails.vue
src/schemas/HederaSchemas.ts
tests/unit/node/NodeDetails.spec.ts
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts
tests/unit/staking/RewardsCalculator.spec.ts
tests/unit/utils/AccountLocParser.spec.ts

This changes the staking terminology across UI as follows:
- stake rewarded --> staked for reward
- stake not rewarded --> staked for no reward
(bonus: unrelated unit test fix)
Fixes #551
**Checklist**

00551 Confusion on labeling for stake

---

src/pages/TokenDetails.vue
tests/unit/Mocks.ts
tests/unit/token/TokenDetails.spec.ts

With this 1-line change, the token memo string is displayed as is and no longer base64 decoded.
Fixes #554
**Checklist**

00554 Token memo wrongly interpreted as base64 encoding

---

src/pages/ContractDetails.vue
tests/unit/contract/ContractDetails.spec.ts

With this trivial change, the runtime byte code is displayed in lieu of the initcode in the ContractDetails view.
Fixes #549
Deployed on staging.
**Checklist**

00549 replace initcode by runtime bytecode

---

src/schemas/SystemContractRegistry.ts
src/utils/ContractAnalyzer.ts
src/utils/FunctionCallAnalyzer.ts
src/utils/cache/AssetCache.ts
src/utils/cache/CacheUtils.ts
tests/unit/utils/FunctionCallAnalyzer.spec.ts

Changes below are refactoring. No semantic changes.
`FunctionCallAnalyzer` now delegates to `ContractAnalyzer` and `AssetCache`.
Use testnet transaction `1676977337.514767623` to check `FunctionCallAnalyzer` behavior.

Refactoring: FunctionCallAnalyzer now delegates to ContractAnalyzer and AssetCache

---

src/components/values/HbarExtra.vue
tests/unit/account/AccountDetails.spec.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/staking/Staking.spec.ts
tests/unit/staking/StakingDialog.spec.ts
tests/unit/token/TokenDetails.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/values/HbarAmount.spec.ts

With changes below, `HbarExtra` now rounds dollar value to 5 digits (in place of 4).
Fixes #562
See sample data provided in #562.
**Checklist**

00562 Incorrect fee for CryptoUpdate transaction

---

jest.config.js
tests/unit/account/AccountDetails.spec.ts
tests/unit/globalSetup.js
tests/unit/token/TokenDetails.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

Changed below disabled `AccountDetails` unit test and enabled test suite to complete.

Fix unit test memory overflow happening in pipeline

---

src/components/token/MetaMaskImport.vue

Trivial 1-line change to adjust the label of the button to `IMPORT TO METAMASK`
Fixes #558 
**Checklist**

New label for "IMPORT TO METAMASK" button.

---

src/pages/AddressDetails.vue
src/utils/cache/CacheUtils.ts
src/utils/cache/ContractByAddressCache.ts
src/utils/cache/NetworkCache.ts
tests/unit/utils/cache/ContractByAddressCache.spec.ts
tests/unit/utils/cache/ContractByIdCache.spec.ts

Changes below are refactoring. No semantic change.
`AddressDetails` vue now re-uses `AccountByAddressCache` and `ContractByAddressCache` in place of inlined rest calls.

Refactoring: AddressDetails now uses AccountByAddressCache and ContractByAddressCache

---

src/pages/TokenDetails.vue
tests/unit/token/TokenDetails.spec.ts

Changes below show the `Decimals` field in `Token Details` page and update unit tests.
Fixes #587 
On mainnet:
- Token `0.0.2302966` has 10 decimals.
- Token `0.0.2303594` has 8 decimals.
**Checklist**

00587  show fungible token decimals on detailed token page

---

tests/unit/contract/ContractResult.spec.ts
tests/unit/dashboard/HbarMarketDashboard.spec.ts
tests/unit/dashboard/MainDashboard.spec.ts
tests/unit/staking/RewardsCalculator.spec.ts
tests/unit/staking/StakingDialog.spec.ts
tests/unit/transaction/TransactionByIdTable.spec.ts
tests/unit/transaction/Transactions.spec.ts
tests/unit/transfer_graphs/NftTransferGraph.spec.ts
tests/unit/transfer_graphs/TokenTransferGraphC.spec.ts
tests/unit/transfer_graphs/TokenTransferGraphF.spec.ts

Change below add some `Wrapper.unmount()` calls in unit tests.
This should (hopefully) fix remaining memory overflows happening randomly during unit tests with coverage.
None

Added missing wrapper.unmount() in unit tests

---

src/components/values/BlobValue.vue

1-line change to force BlobValue to wrap even in the absence of natural word break.
Fixes #566

Force BlobValue to wrap.

---

tests/e2e/specs/CopyHexaToClipboard.cy.ts

Changes below adapt and re-enable `CopyToHexaClipboard` e2e test.
This one was temporarily disabled when migrating to Cypress 12.
None
**Checklist**

Re-enabled CopyToHexaClipboard e2e test

---

src/components/transfer_graphs/HbarTransferGraphC.vue
src/components/transfer_graphs/layout/HbarTransferLayout.ts
src/schemas/HederaUtils.ts
tests/unit/transfer_graphs/layout/HbarTransferLayout.spec.ts

Changes below implement suggestion proposed in #497.
To make compact version of hbar transfer diagram, explorer now applies the following logic.
It excludes Transfer objects satisfying the following conditions:
- `Transfer.amount` > 0
- `Transfer.account` is an operator account (ie `0.0.98` or a comity member account)
Fixes #497
Look at the following page:
https://hashscan.io/mainnet/account/0.0.55954?p1=1&k1=1679579112.950568003&p2=1
Without the fix, this [page](https://hashscan.io/mainnet/account/0.0.55954?p1=1&k1=1679579112.950568003&p2=1) looks like this (rows 3 and 6 do not show transfer diagram in `Content` column):
With the fix, rows 3 and 6 now have show a transfer diagram:
Note: rows 1 and 4 do not show transfer …

00497 revisit compact transfer diagram

---

src/components/contract/ContractActionDetails.vue
src/utils/analyzer/ContractActionAnalyzer.ts

Changes below fix #609.
They also include some refactoring : `ContractActionDetails` vue now delegates some logic to `ContractActionAnalyzer` class.
Fixes #609
Use transaction [0.0.1093@1684933051.154776111](https://hashscan.io/previewnet/transaction/1684933063.077913506) (on `previewnet`) for testing.

00609 Output Result field missing in Call Trace section

---

src/components/contract/ContractActionDetails.vue
src/components/contract/ContractResult.vue
src/components/values/FunctionError.vue
src/components/values/FunctionInput.vue
src/components/values/FunctionResult.vue
src/schemas/HederaUtils.ts
src/utils/analyzer/ContractActionAnalyzer.ts
src/utils/analyzer/ContractAnalyzer.ts
src/utils/analyzer/ContractResultAnalyzer.ts
src/utils/analyzer/FunctionCallAnalyzer.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/utils/FunctionCallAnalyzer.spec.ts

Changes logic add required logic to Contract and Action errors ie bytes from Mirror Node fields:
- `ContractResult.error_message`
- `ContractAction.result_data` (when  result_data_type == ERROR)
They also modifies field ordering in Contract Result section: Input and Output are now presented first and Error is the last.
Fixes #613
Field re-ordering can be visualized on transaction `1685115468.045782003`.
Error decoding will be visible once custom contract verification is enabled.
**Checklist**

00613 Add logic to decode Contract and Action errors

---

src/components/InfoTooltip.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/TokenDetails.vue
tests/unit/account/AccountDetails.spec.ts
tests/unit/node/NodeDetails.spec.ts
tests/unit/token/TokenDetails.spec.ts

This PR add a small InfoTooltip component (explanatory tooltip attached to a circle-info icon) and makes use of it in Account/Contract/Token details pages to clarify the following properties:
- `Expires at`
- `Auto Renew Period`
- `Auto Renew Account`
Fixes #612
Also deployed on staging server.
**Checklist**

00612 Expiration date is confusing until account expiry is turned in

---

src/components/transaction/TransactionAnalyzer.ts
src/pages/TransactionDetails.vue
tests/unit/Mocks.ts
tests/unit/transaction/TransactionDetails.spec.ts

This displays an InfoTooltip on the `Max Fee` property when `Charged Fee > Max Fee`
Fixes #617 
(examples of such transactions in issue #617)
**Checklist**

00617 Add tooltip to explain why transaction fee may exceed 'max fee'

---

src/pages/TransactionDetails.vue
src/utils/cache/ContractByAddressCache.ts
src/utils/cache/ContractResultByTsCache.ts
tests/e2e/specs/AccountNavigation.cy.ts
tests/e2e/specs/TokenNavigation.cy.ts
tests/unit/Mocks.ts
tests/unit/utils/cache/ContractResultByTsCache.spec.ts

Root cause of this issue is located in `ContractResultByTsCache`.
This class fetches contract result details for a given transaction timestamp. It does this in two steps:
1) first it uses `api/v1/contracts/results/?timestamp=TTT` to retrieve contract id
2) next it uses `api/v1/contracts/{contractId}/results/TTT` to retrieve full details of contract result
In the case of transaction [1685737274.278536163](https://hashscan.io/previewnet/transaction/1685737274.278536163), first call returns `contract_id == null` and causes fetching to stop.
Changes below enhance logic above: when first call returns `contract_id == null`, `ContractResultByTsCache` checks if `hash` value is available and uses it to retrieve contract result details.
Changes below also include:
- extra unit test …

00622 Ethereum transaction details may fail to display contract result

---

src/components/transaction/TransactionGroupAnalyzer.ts
src/pages/TransactionDetails.vue
tests/unit/transaction/TransactionDetails.spec.ts

Simple change to make sure that a random transaction with nonce=0 is not considered a 'parent' transaction. To be a parent, it also needs to have at least one child (i.e. transaction with same ID and parent_consensus_timestamp property set).
Fixes #602
Without this fix, the following transaction wrongly displays a parent transaction:
https://hashscan.io/mainnet/transaction/1684345315.068887004
**Checklist**

00602 Transaction wrongly shows a parent transaction property

---

src/components/contract/ContractResult.vue
src/pages/TransactionDetails.vue
src/utils/analyzer/ContractResultAnalyzer.ts
tests/unit/Mocks.ts
tests/unit/contract/ContractResult.spec.ts

- _Nonce_ property in TransactionDetails view is renamed _Transaction Nonce_
- _Ethereum Nonce_ property in added to Contract Result section.
Fixes #626
Deployed on staging.
**Checklist**

00626 Clarify nonce and ethereum nonce fields

---

src/components/values/EVMAddress.vue
src/components/values/InnerSenderEVMAddress.vue
src/utils/EthereumAddress.ts
tests/unit/Mocks.ts
tests/unit/utils/AccountLocParser.spec.ts
tests/unit/utils/EVMAddress.spec.ts
tests/unit/utils/EthereumAddress.spec.ts

This PR refactors the logic of EVMAddress and enhances it such that when the evmAddress argument is a long-zero address, we systematically fetch the corresponding Account information to retrieve its native EVM address in case it holds one.
The compact display now shows 1 byte (instead of 1 digit) before the ellipsis.
Related to #629. 
It is not confirmed at this point that we want to duplicate the _from_ property found in the _Contract Result_ to show a _Sender_ property in the top section. But in any case we want to make sure the _from_ (and other EVM addresses) show the native EVM address when there is one.
**Checklist**

00629 Show native EVM address when possible.

---

src/components/transfer_graphs/TransferGraphSection.vue

In transaction [1686467061.803821702](https://hashscan.io/mainnet/transaction/1686467061.803821702), net amount (ie sum of all positive hbar transfers - charged fee) is negative.
So far, `TransferGraphSection` vue assumed that net amount was always positive and simply skip`Hbar / Fee Transfer `diagram in the case above.
With the changes below, `TransferGraphSection` vue now displays transfers as a fee diagram when net amount is negative.
Fixes #639 
Uses transaction  [1686467061.803821702](https://hashscan.io/mainnet/transaction/1686467061.803821702) to experiment. Without the fix, `Transfer Section` does not contain `Hbar/Fee Transfer` subsection. With the fix, `Fee Transfer` subsection is displayed.
**Checklist**

00639 HBAR transfer diagram for 1686467061.803821702 is missing

---

src/assets/styles/explorer.scss
src/pages/TransactionDetails.vue

With this simple change, we make sure the title of the top section in TransactionDetails wraps, and also reduce its font size at the MEDIUM_BREAKPOINT.
With the wrapping of BlobValue already brought by previous PR #590, this resolves the issue brought up by #557
Fixes #557 

00557 Make sure transaction title + result pill wrap.

---

public/abi/IHederaTokenService.json
src/components/values/FunctionError.vue
src/components/values/FunctionInput.vue
src/components/values/FunctionResult.vue
src/utils/analyzer/FunctionCallAnalyzer.ts
tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts

Changes below:
- update Hedera Token Service ABI embedded in Explorer (`IHederaTokenService.json`)
- enhanced error processing when decoding input / output / error values from contract call transactions.
When a decoding error is reported by `etherjs`, Explorer now displays an error message as below:
Fixes #600
Uses `mainnet` transaction [1684236107.179110285](https://hashscan.io/mainnet/transaction/1684236107.179110285) to visualize error message reported when decoding error happens.
**Checklist**

00600 Explorer fails to decode call to system contract

---

src/components/values/TokenAmount.vue
tests/unit/Mocks.ts
tests/unit/values/TokenAmount.spec.ts

This PR modifies TokenAmount value to deal with cases where token has a decimalCount > 20:
- display "?" in place of the amount
- display a (i) icon with explanatory tooltip
Fixes #616 
In the token balances:
In the token details:
**Checklist**

00616 HashScan fails to display token balance when token has very large number of decimals

---

src/components/values/FunctionError.vue
src/schemas/HederaUtils.ts
src/utils/analyzer/FunctionCallAnalyzer.ts

Changes below:
- implement requested feature
- fix bug related to `Output Result` field (see comments in issue)
`HederaUtils.decodeSolidityErrorMessage()` now fallbacks to string decoding using `TextDecoder` class.
Error message in transaction [1686939577.451858743](https://hashscan.io/previewnet/transaction/1686939577.451858743)  is now displayed as:
Fixes #646
Use previewnet transaction transaction [1686939577.451858743](https://hashscan.io/previewnet/transaction/1686939577.451858743) to see feature and fix in action.
**Checklist**
- [] Documented (Code comments, README, etc.)
- [] Tested (unit, integration, etc.)

00646 Contract error returns should be decoded if they are ASCII

---

package.json

In some cases, CI/CD fails to complete properly because of memory issues with NodeJS. For example [here](https://github.com/hashgraph/hedera-mirror-node-explorer/actions/runs/5022631216/jobs/9006323434):
```
<--- Last few GCs --->
[3543:0x56a2ae0]   120384 ms: Mark-Compact 4042.3 (4137.9) -> 4030.0 (4141.9) MB, 1999.0 / 0.0 ms  (average mu = 0.520, current mu = 0.039) allocation failure; scavenge might not succeed
[3543:0x56a2ae0]   123710 ms: Mark-Compact 4046.6 (4142.1) -> 4034.3 (4146.1) MB, 3250.0 / 0.0 ms  (average mu = 0.282, current mu = 0.023) allocation failure; scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```
This PR sets a maximum heap size before freeing the memory, so that …

Fixes 'JavaScript heap out of memory' issues with Github CI/CD

---

src/components/contract/ContractTransactionTable.vue
src/components/transaction/TransactionAnalyzer.ts
src/components/transfer_graphs/HbarTransferGraphF.vue
src/components/transfer_graphs/NftTransferGraph.vue
src/components/transfer_graphs/RewardTransferGraph.vue
src/components/transfer_graphs/TokenTransferGraphC.vue
src/components/transfer_graphs/TokenTransferGraphF.vue
src/components/transfer_graphs/TransferGraphSection.vue
src/components/transfer_graphs/layout/HbarTransferLayout.ts
src/components/transfer_graphs/layout/RewardTransferLayout.ts
src/pages/TransactionDetails.vue
src/schemas/HederaSchemas.ts
src/schemas/HederaUtils.ts
src/utils/EntityID.ts
src/utils/TransactionTools.ts
tests/e2e/specs/TransferGraphs.cy.ts
tests/unit/Mocks.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/transfer_graphs/NftTransferGraph.spec.ts
tests/unit/transfer_graphs/RewardTransferGraph.spec.ts
tests/unit/transfer_graphs/TokenTransferGraphF.spec.ts
tests/unit/transfer_graphs/layout/HbarTransferLayout.spec.ts

This PR brings changes to the Transfers section in Transaction details:
1. Show the Staking reward transfers in a new subsection.
2. Display modified amounts in the Hbar transfers by deducing the reward amounts of those, in order to obtain a more intuitive transfer diagram — this allows for instance to distinguish the fee going to 0.0.800
3. Hide empty sub-sections
Fixes #529
Note this is still a draft while we are collecting internal feedback.
Example of display without the change:
Display with the change:
**Checklist**

00529 rewards subsection

---

src/components/staking/ProgressDialog.vue
src/pages/Staking.vue
src/schemas/HederaSchemas.ts
src/utils/analyzer/FunctionCallAnalyzer.ts
tests/unit/Mocks.ts
tests/unit/values/TokenAmount.spec.ts

Changes below fix several typing issues reported by typescript 5.
No semantic changes.

Refactoring: fixed various typing issues reported by typescript 5

---

src/components/allowances/ApproveAllowanceDialog.vue
src/components/contract/ContractResult.vue
src/components/contract/ContractResultTable.vue
src/components/values/BlobValue.vue
src/components/values/ComplexKeyValue.vue
src/components/values/ContractLink.vue
src/components/values/HbarAmount.vue
src/components/values/HexaValue.vue
src/components/values/KeyValue.vue
src/components/values/StringValue.vue
src/components/values/TimestampValue.vue
src/components/values/TokenAmount.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/NodeDetails.vue
src/pages/TransactionDetails.vue

Changes below fixes some typing issues reported by typescript 5.
Most of them follow the same pattern: in props declaration, `default: null` is added to avoid `undefined` warning.

Refactoring: fixed some typing issues reported by typescript 5

---

jest.config.js
package-lock.json
package.json
tests/unit/globalSetup.js
vue.config.js

Changes below fix connection break by moving from blade release 0.9.14 to 1.0.0.
Real root cause of the break is undetermined. 
However experimentation shows that blade connection works fine with 1.0.0 (at least today).
Note: latest version of blade is 1.0.4 however it's no longer compatible with Explorer.
Releases 1.0.1, 1.0.2 and 1.0.3 are also incompatible.
Moving to these releases will require some code update: this will be done later.
Fixes #659

00659 Connection to Blade wallet is broken

---

src/components/node/NodeTable.vue
src/pages/NodeDetails.vue
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts

This PR fixes the NodeTable and NodeDetails views to:
- use stake rather than unclamped stake for everything related to consensus weight
- align number of decimals for consensus weight %
Fixes #662
Deployed on staging. Look at LG node for instance (where stake ≠ rewarded + not rewarded)
**Checklist**

00662 fix discrepancies in stake for consensus (and percentage)

---

src/pages/ContractDetails.vue
src/schemas/HederaSchemas.ts
tests/unit/Mocks.ts
tests/unit/contract/ContractDetails.spec.ts

Display the nonce property when present in the contract. When absent (i.e. in older contracts) do not display anything. 
The name of the property is "Contract Nonce", not just "Nonce", like we have "Transaction Nonce", to avoid any confusion among the various kinds of nonce.
Fixes #633
**Checklist**

00633 Display contract nonce

---

tests/unit/values/HbarAmount.spec.ts

Changes below fix a latent issue in `HbarAmount` unit test causing `RewardTransferGraph` to break randomly.
`HbarAmount` defines a mock for `api/v1/network/exchangerate` at the top level (ie outside of `describe()` function).
This mock remains active during execution of all the tests.
`RewardTransferGraph` does not define any mock for `api/v1/network/exchangerate` and does not expect any dollar values.
When `RewardTransferGraph` unit test is executed before `HbarAmount`, it succeeds.
When `RewardTransferGraph` unit test is executed after, it breaks because `HbarAmount` mock returns some unexpected dollar values.
Change below make sure that `HbarAmount` dismantles its mock after its execution.
Fixes #00672
It's possible to …

00672 RewardTransferGraph unit test randomly fails

---

.env
src/App.vue
src/AppStorage.ts
src/components/CookiesDialog.vue

Get user approval before setting up the google tag to enable google analytics:
- prompt the user for his consent (accept/reject cookies) with modal dialog
- the tag ID is set via VITE_APP_GOOGLE_TAG_ID environment variable
- the global site tag setup is no longer static in (the branded version of) index.html but instead added dynamically to the DOM after consent is given
- keep user choice for 365 days
None

Get user consent for cookies

---

src/assets/styles/explorer.scss
src/components/ModalDialog.vue

Simple change to make the modal dialog responsive, which fixes the issue of cookie consent dialog not showing up properly on a mobile screen.

Make modal dialog responsive.

---

package-lock.json
package.json
vitest.config.ts

Changes below update release of 
- `vitest` from 0.32.4 to 0.34.3.
- `@vitest/coverage-v8` from 0.33.0 to 0.34.3.
Some configuration items in `vitest.config.ts` become obsolete and are removed.
**Checklist**

Moved vitest from 0.32.4 to 0.34.3.

---

src/components/SearchBar.vue
tests/e2e/specs/SearchBar.cy.ts

Changes magnifying glass icon in search bar to an interactable button
Fixes #
**Checklist**

00014: Magnifying glass icon should be a button to trigger the search

---

tests/unit/utils/TableController.spec.ts
vitest.config.ts

Changes below fix test break in `Staking.spec.ts` and `StakingDialog.spec.ts`.
This break happens systematically when tests are executed by GitHub.
In local environment, it happens when `vitest` cache is clean (or setting `cache:false` in `vitest.config.ts`).
Root cause is usage of `vi.useFakeTimer()` in `TableController.spec.ts`
- `vi.useFakeTimer()` is called outside of `describe()` method
- `vi.useRealTimer()` is never called
- when `TableController.spec.ts` is executed first, `vi.useFakeTimer()` is active when `Staking.spec.ts` is executed
- `Staking.spec.ts` and `StakingDialog.spec.ts` breaks when `vi.useFakeTimer()` is active (not clear why)
None
**Checklist**

Fixed test break in Staking.spec.ts and StakingDialog.spec.ts

---

package-lock.json
package.json

Changes below upgrade `@kabuto-sh/ns` from release `0.7.0` to `0.12.0`.
Manually tested:
- query with an existing name works OK
- query with an non existing name breaks on KNS side 
- same issue happens with release 0.7.0
- issue is being investigated by KNS team
_None_

Updated @kabuto-sh/ns to release 0.12.0.

---

src/components/SearchBar.vue
src/utils/SearchRequest.ts
tests/unit/utils/SearchRequest.spec.ts

Changes below fix a regression introduced by #482 and add some additional checks in unit tests.
Fixes #711.
See #711 for testing samples.
**Checklist**

00711 Restored logic which initializes SearchRequest.ethereumAddress and added extra checks in unit tests

---

src/components/contract/ContractResultLogEntry.vue
src/components/contract/ContractResultLogs.vue
src/utils/analyzer/ContractLogAnalyzer.ts
tests/unit/contract/ContractResultLogEntry.spec.ts
tests/unit/utils/analyzer/ContractLogAnalyzer.spec.ts

Changes below implement contract event decoding and add unit tests.
When events are decoded `ContractResultLogEntry` displays event data as below:
When events decoded enabled (ie target contract is verified), `ContractResultLogEntry` displays the following:
Fixes #00669
Contract [0.0.40537](https://hashscan.io/previewnet/contract/0.0.40537) and [0.0.28117](https://hashscan.io/previewnet/contract/0.0.28117) are [TestEvent.sol](https://github.com/ericleponner/hedera-contract-album/blob/main/src/main/java/test_event/TestEvent.sol) instances.
- [0.0.40537](https://hashscan.io/previewnet/contract/0.0.40537) is not verified and contract call [0.0.17590@1695917074.820719243](https://hashscan.io/previewnet/transaction/1695917087.683970 …

00669 ContractResultLogEntry now displays decoded data when contract is verified.

---

src/components/contract/ContractByteCodeSection.vue

Replace the too prominent link to Sourcify docs by a tooltip explaining what a full/partial match means.
This might be later extended if deemed necessary by adding a link to the docs inside the tooltip (we won't be able to use TooltipInfo component as is, though) or perhaps in a popover (not sure about links inside a tooltip...)
Full Match example:
Partial Match example:

Add tooltip to explain full vs. partial match

---

src/schemas/NetworkRegistry.ts

Unit tests currently depend upon this static initialisation.

Bring back sourcifySetup in static initialization of NetworkRegistry.

---

src/components/account/BalanceTable.vue
src/components/account/TokenRelationshipsTableController.ts
src/pages/AccountBalances.vue
tests/unit/Mocks.ts
tests/unit/account/AccountBalances.spec.ts
tests/unit/transfer_graphs/RewardTransferGraph.spec.ts

In this PR, we:
- use the API call api/v1/accounts/{id}/tokens to be able to retrieve the complete list of token associated with an account
- use a TableController instead of a Cache to retrieve the data in a paginated manner.
- fix unrelated unit test issue (was depending upon another test's mock side-effect)
Fixes #720 #706 
**Checklist**

00720 incomplete list of token balances

---

chart/templates/configmap.yaml
chart/values.yaml

This PR allows helm templating for `proxyPass` value so that end-user is able to deploy their chart with any custom release name without hardcoding the `proxyPass` value in their values.yaml file
Fixes #725
I have tested it in FST chart and a relevant fix is here: https://github.com/hashgraph/full-stack-testing/pull/413
**Checklist**

fix: allow Helm templating for proxyPass value

---

public/networks-config.json
src/App.vue
src/components/contract/ContractByteCodeSection.vue
src/utils/RouteManager.ts
tests/unit/contract/ContractDetails.spec.ts

Make the URL of the 'Verify Contract' reactive such that it displays the value read from config.json once the read is completed, which takes a tiny bit longer than the initialisation of the page.
**Checklist**

Fix initialisation of verify contract URL

---

package-lock.json
package.json
src/main.ts

Changes below remove an unused dependency: `vue-axios`.
**Checklist**

Removed vue-axios unused dependency.

---

package-lock.json
package.json

Recent move to crypto-js@4.2.0 breaks hashconnect@0.1.10.
Changes below downgrade crypto-js by adding an explicit dependency to 4.1.1 release.
_None_

Downgrade crypto-js from 4.2.0 to 4.1.1 

---

.gitignore
README.md
docker-compose.yml
networks-config-example.json

This allows to provide a custom `networks-config.json` when running the explorer from a Docker container, for instance to easily:
- use connection to a LocalNode
- use a completely custom (set of) network(s) for testing purposes

Add mount point for networks-config.json when running in Docker

---

src/utils/analyzer/FunctionCallAnalyzer.ts
tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts

Changes below fix false decoding error reported in `Contract Result` section.
They also add a unit test case for asserting this.
Fixes #765
Use mainnet transaction [1700549131.961381389](https://hashscan.io/mainnet/transaction/1700549131.961381389).
**Checklist**

00765 Explorer should not report "Decoding Error" when error is empty in a contract result

---

.env
src/components/contract/ContractByteCodeSection.vue
src/schemas/NetworkRegistry.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/schema/NetworkRegistry.spec.ts

- Remove the `VITE_APP_ENABLE_VERIFICATION_UI_PHASE2` environment variable
- Update the processing of the `networks-config.`json file such that (for each configured network) the SC verification may be disabled in either of the following cases:
- `sourcifySetup` property is omitted from the configuration (this ensures compatibility with `networks-config.json` used before the introduction of SC verification)
- `sourcifySetup = null`
- `sourcifySetup.activate = false`
Fixes #769
In the static networks configuration, we leave the `activate` flag to true with empty verification URLs. The static activation is currently needed by unit tests. In an ideal world, since the static config is the fallback in case a custom …

Clean-up smart contract verification feature flag

---

src/router.ts
tests/e2e/specs/HomePage.cy.ts

Changes below enable the following redirection:
`<explorer_url>/mainnet `=> `<explorer_url>/mainnet/dashboard`
`<explorer_url>/testnet` => `<explorer_url>/testnet/dashboard`
`<explorer_url>/previewnet` => `<explorer_url>/previewnet/dashboard`
They also add a new e2e test case to assert this behavior.
Fixes #450
**Checklist**

00450 Supporting both EIP3091 and human URLs 

---

src/components/values/BlobValue.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
tests/unit/values/BlobValue.spec.ts

In AccountDetails and ContractDetails views, when we find that the memo  is candidate to Base64 decoding, we now show both the raw value and the decoded value. So if the value is, in fact, not encoded, it is still legible.
This happens only in case the value has not been interpreted (as a URL, an IPFS hash...) since that would mean we were indeed not confused about the encoding.
Fixes #694 
Visible on staging server.
Examples:
- actual B64 encoding <img width="928" alt="Screenshot 2023-11-28 at 12 42 37" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/59c28a89-ae1c-4a80-a5c9-b8fdff6f1eef">
- not a B64 encoding <img width="928" alt="Screenshot 2023-11-28 at 12 44 00" …

00694 display both raw and b64-decoded values of memo when relevant

---

src/utils/solc/SolcUtils.ts

Changes below enhance bytecode comparison done by Explorer.
`SolcUtils.compareBytecode()` method now detects when bytecode starts with `0x73` opcode and adjusts its comparison logic.
Fixes #768
**Checklist**

00768 Streamline Hardhat Smart Contract Verification Process Similar to Sourcify

---

src/components/Copyable.vue
src/components/TopNavBar.vue
src/components/wallet/WalletInfo.vue

- Replace the Copyable Account ID in WalletInfo by a navigation link to the AccountDetails view (AccountLink)
- Also dismiss the WalletInfo dialog when the user takes one of the available actions:
- Navigate to one's account
- Copy EVM Address
- Switch accounts
- Bring minor visual adjustments 
In an ideal world, we would dismiss the dialog when the user clicks anywhere outside. This is not covered with this PR.
Fixes #778

00778 replace copy action by a navigation link

---

src/components/contract/ContractByteCodeSection.vue
tests/unit/contract/ContractDetails.spec.ts

Adjust the reactivity of the ContractDetails view such that:
- the (re)loading issue in 784 is fixed
- we avoid the flashing effect: displaying NOT-VERIFIED when page is loaded and VERIFIED once the verification status has been obtained from sourcify.
Fixes #784 
**Checklist**

00784 reactivity problem with the contract verification status

---

src/components/verification/ContractVerificationDialog.vue

Changes below fix `Contract Verification` dialog : `dialogTitle` must be a computed value.
Fixes #786 
See instructions to reproduce and verify from #786
**Checklist**

fix: 00786 ContractVerificationDialog.dialogTitle must be a computed value.

---

src/pages/AccountDetails.vue
src/utils/table/TableController.ts

Correctly unmount table controller and disable refreshes when it is unmounted
Fixes #730 
**Checklist**

fix: disable refreshes when navigating away from account details

---

src/components/contract/ContractActionDetails.vue

Adds `value` to the fields listed in the details of a call trace action.
Implements option2 described in issue #771
Fixes #771 
Deployed on staging.

fix: #771 enhance visibility of transferred value in call trace

---

src/pages/ContractDetails.vue
src/utils/PathParam.ts
src/utils/parser/ContractLocParser.ts
tests/e2e/specs/ContractNavigation.cy.ts
tests/unit/Mocks.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/utils/ContractLocParser.spec.ts

Changes below add support for URL:
`<HEDERA_EXPLORER_URL>/<NETWORK>/contract/<CONTRACT_ADDRESS>`
The also include unit and e2e tests.
Fixes #432 
**Checklist**

feat: contract URL should accept both contract id and evm address (#432)

---

src/pages/ContractDetails.vue
src/utils/analyzer/BalanceAnalyzer.ts
src/utils/parser/AccountLocParser.ts
src/utils/parser/BlockLocParser.ts
src/utils/parser/ContractLocParser.ts
src/utils/parser/TransactionLocParser.ts

Typing cosmetic : some declarations should be ComputedRef<> in place of Ref<>.
None
**Checklist**

chore: replaced Ref<> by ComputedRef<> in some declarations.

---

package-lock.json
package.json
src/utils/wallet/WalletDriver_Blade.ts

Changes below update release of [@blandelabs/blade-web3](https://www.npmjs.com/package/@bladelabs/blade-web3.js) from 1.1.1 to 1.2.2.
Straight move to `1.2.2` release breaks all unit tests.
After investigations, it turns out that `import @blandelabs/blade-web3.js` now executes some code with dependency on `window.matchMedia()`. Although `vitest` is setup to mock `window.matchMedia()` (see `globalSetup.js`), it does not prevent crashing.
To avoid that, `WalletDriver_Blade` class now performs a dynamic import of `@blandelabs/blade-web3.js`.
None
**Checklist**

chore: move to latest release of @bladelabs/blade-web3.js.

---

src/utils/TransactionTools.ts
tests/unit/transfer_graphs/layout/HbarTransferLayout.spec.ts

Fixes the way transfer graph is modified to appear "before reward payment".
Fixes #810 
**Checklist**

fix: 810 missing sender account in graph

---

src/utils/wallet/WalletDriver_Ethereum.ts
src/utils/wallet/WalletDriver_Metamask.ts

Changes below extract generic part of WalletDriver_Metamask in WalletDriver_Ethereum.
WalletDriver class hierarchy becomes:
```
WalletDriver
WalletDriver_Hedera
WalletDriver_Blade
WalletDriver_Hashpack
WalletDriver_Ethereum
WalletDriver_Metamask
```
This should make Brave Wallet support easier (by simply adding WalletDriver_Brave).
_None_
**Checklist**

chore: WalletDriver_Metamask class now extends WalletDriver_Ethereum.

---

src/AppStorage.ts
src/assets/arrow-down.svg
src/assets/arrow-up.svg
src/components/DashboardCard.vue
src/components/allowances/ApproveAllowanceSection.vue
src/components/contract/ContractByteCodeSection.vue
src/components/contract/ContractResult.vue
src/components/contract/ContractResultLogs.vue
src/components/contract/ContractResultStates.vue
src/components/contract/ContractResultTrace.vue
src/components/contracts/ContractResultsSection.vue
src/components/staking/RewardsCalculator.vue
src/components/token/TokenCustomFees.vue
src/components/topic/TopicMessage.vue
src/pages/AccountDetails.vue
src/pages/BlockDetails.vue
src/pages/ContractDetails.vue
src/pages/Nodes.vue
src/pages/Staking.vue
src/pages/TokenDetails.vue
src/pages/TransactionDetails.vue
tests/unit/contract/ContractDetails.spec.ts

- Make sections collapsible per spec. This is done for all pages but main pages which contain a single table (and the Dashboard page)
- Remove navigation links from Staking page
Fixes #822
- Deployed on staging server
- Sample screenshot:  <img width="1479" alt="Screenshot 2023-12-28 at 11 46 55" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/b7b875d2-d7bf-4a6e-997a-122acaf1b55e">

feat: #822 collapsible sections

---

src/assets/styles/explorer.scss
src/components/contract/ContractByteCodeSection.vue
src/components/values/ByteCodeValue.vue
src/components/values/DisassembledCodeValue.vue

Minor tweaks for the code boxes.

fix: tune padding and background in ByteCodeValue and DisassembledCodeValue.

---

package-lock.json
package.json

Try reverting the last 2 axios updates (1.6.2->1.6.3 and 1.6.3->1.6.4) since they are concomitant with the recent regression of the contract verification functionality.
Related to #834

fix: Revert recent axios updates (go back to 1.6.2)

---

src/components/staking/WalletChooser.vue

Allow wallet chooser to properly display more than 3 drivers.

fix: allow wallet chooser to wrap

---

.env
src/components/TopNavBar.vue
src/utils/wallet/WalletDriver.ts
src/utils/wallet/WalletDriver_Ethereum.ts
src/utils/wallet/WalletDriver_Metamask.ts
src/utils/wallet/WalletManager.ts

Changes include some refactoring:
1) `WalletDriver_Metamask.watchToken()` becomes a generic method and moves to `WalletDriver_Ethereum`
2) `WalletDriver_Ethereum.isCancelError()` has now a generic implementation (works on all subclasses)
3) Removed metamask feature flag (now obsolete)
`WalletDriver_Ethereum.connect()` now sends `wallet_requestPermissions` request to force wallet to interact wit user (and let her chooses another account).
**Checklist**

chore: some refactoring in WalletDriver class hierarchy

---

package-lock.json
package.json
src/utils/wallet/WalletDriver_Ethereum.ts
src/utils/wallet/WalletDriver_Metamask.ts

Changes below fix #774.
Root cause of the pb is a limitation in `@metamask/detect-provider` package.
This one breaks when both Metamask and Coinbase wallet extensions are enabled.
Coinbase has published a [note](https://docs.cloud.coinbase.com/wallet-sdk/docs/injected-provider-guidance) about the correct way to detect providers.
`WalletDriver_Ethereum.connect()` now implements behavior specified in this note.
Dependency on `@metamask/detect-provider` is removed
Fixes #774
See #774 for reproduction scenario
**Checklist**

fix: conflict between MetaMask and Coinbase wallet extensions

---

src/components/Property.vue
src/pages/RoutingSpec.vue
src/router.ts

Create routing documentation similar to a swagger doc
Fixes # 445
**Checklist**

create route documentation

---

src/pages/AccountDetails.vue
src/pages/ContractDetails.vue

- Include tokens with a balance=0 when there is enough room in the list of balance displayed inline in  ContractDetails and AccountDetails.
- Display the 'Show all tokens' link when the account/contract owns at least one serial #, such that we can get to the details of that collection.
Needs refactoring to share this code between account and contract. Will add more tests then.
**Checklist**

fix: account and contract inline token balances

---

src/pages/NoSearchResult.vue
src/utils/ComplexKeyLine.ts
src/utils/EntityID.ts
src/utils/EthereumAddress.ts
src/utils/SearchRequest.ts
tests/unit/utils/EntityID.spec.ts

Changes below implements #861.
Explorer `Search Bar` now accepts an entity id with or without its checksum (`0.0.x` or `0.0.x-abcde`).
When specified, Explorer extracts and validates the checksum:
1) if checksum is invalid, explorer displays `No Result` page (and no request is made to mirror node)
2) if checksum is valid, Explorer proceeds to the usual search operation.
Fixes #861 
**Checklist**

feat: support HIP-15 address checksum in search field

---

src/components/values/EVMAddress.vue
tests/unit/contract/ContractResultLogEntry.spec.ts

EVMAddress is now able to display the name of the contract when the address is a verified contract.
This reflects on the `Call Trace` and `Contract States` sections.
Fixes #873
Note this PR depends upon PR #871 which should be integrated first. 
**Checklist**

fix: display verified contract name in call trace section

---

src/utils/wallet/WalletDriver.ts
src/utils/wallet/WalletDriver_Metamask.ts

In the context of the Brave Ethereum object, the addition of the .isMetamask = true attribute is necessary. Without this extra condition, clicking on the Metamask wallet could inadvertently trigger calls to the Brave wallet, leading to potential confusion. This modification ensures that Metamask functions seamlessly, preventing any unintended interactions with the Brave wallet. Specifically, it introduces a safeguard that triggers a 'Wallet not found' error if the wallet setting is configured to point to the Brave wallet. This enhancement enhances the overall user experience and maintains the expected behavior of Metamask.
Fixes #
**Checklist**

fix: adjusted Metamask wallet discovery logic

---

src/components/allowances/ApproveAllowanceSection.vue
src/components/contract/ContractResult.vue
src/components/topic/TopicMessage.vue

A couple purely cosmetic changes:
- `accountAllowances` -> `Account Allowances` in `ApproveAllowanceSection`
- Suppress unwanted `<div>` elements which break the CSS spacing for `DashboardCard`

fix: misc cosmetic fixes

---

src/components/dashboard/MarketDataCache.ts
src/utils/loader/AutoRefreshLoader.ts

Changes below fix `MetadataCache.clear()` : this is suspected to be root cause of random breaks in unit tests.
**Checklist**

chore: tentative fix for random break in unit tests

---

src/utils/RouteManager.ts
src/utils/SearchRequest.ts
src/utils/name_service/KNS.ts

Changes below perform a few renamings around naming service in `SearchRequest.ts`.
Goal is to make easier integration of other name services (next to KNS).
_None_
**Checklist**

chore: refactoring around name services

---

src/components/values/ByteCodeValue.vue
src/components/values/FunctionInput.vue
src/components/values/FunctionResult.vue

In Contract Result section, the properties Input - Function & Args and Output Result sometimes contain the whole contract bytecode or runtime bytecode which can make the section extremely long.
With this PR, we use ByteCodeValue instead of HexaValue for these properties to make them scrollable.
**Checklist**

fix: make Input and Output scrollable in Contract Result section

---

src/components/account/AccountTable.vue
tests/unit/account/Accounts.spec.ts

- Column `Account` renamed `ID`
- Column `Expiry` replaced by column `Created`
- Fix the underlying API property name used to get the memo
**Checklist**

Fix: Better align contents of AccountTable and ContractTable.

---

src/components/values/InlineBalancesValue.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/utils/analyzer/BalanceAnalyzer.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/values/InlineBalancesValue.spec.ts

Refactoring of the display of inline balances (+ age of balance state) by means of `InlineBalancesValue` component, used by `AccountDetails` and `ContractDetails` views. 
**Checklist**

chore: Refactor inline balances

---

src/pages/TokenDetails.vue

Use `DashboardCard's` `subtitle` slot for the Token ID/addresse so the control(s) are correctly positioned at the top right of the title section.
**Checklist**

fix: top level controls layout on TokenDetails

---

src/components/values/SourceCodeValue.vue

Currently on Hashscan, we utilize an external library `prismjs` to display the solidity smart contract. This `prismjs` component wraps around the source solidity file as its child component. However, the `prismjs` component does not update its child components on re-renders. Therefore, this PR pushes in a fix that forces the prism component to refresh by supplying it with a dynamic unique `key` attribute.
Fixes #894 
**Checklist**

fix: provided a key attribute to force refresh prism component on re-renders (#894)

---

src/components/values/FunctionError.vue
src/schemas/HederaUtils.ts

This PR removes UTF-8 decoding from the hex error message string to allow Hashscan to display the original hex value of the error message, rather than a non-human-readable string.
Fixes #904
**UI update:
Fix from 
to
**Checklist**

fix: removed UTF-8 decoding from hex error message string processing (#904)

---

src/AppStorage.ts
src/assets/styles/explorer-oruga.scss
src/components/EmptyTable.vue
src/components/PlayPauseButton.vue
src/components/Tabs.vue
src/components/account/AccountCreatedContractsTable.vue
src/components/account/AccountVerifiedContractsTable.vue
src/components/contract/ContractTable.vue
src/components/contract/VerifiedContractsController.ts
src/components/staking/StakingRewardsTable.vue
src/components/transaction/TransactionTable.vue
src/components/transaction/TransactionTableController.ts
src/components/values/ContractName.vue
src/pages/AccountDetails.vue
src/pages/Contracts.vue
src/schemas/NetworkRegistry.ts
src/utils/cache/CacheUtils.ts
src/utils/cache/SourcifyCache.ts
src/utils/cache/VerifiedContractsByAccountCache.ts
src/utils/cache/VerifiedContractsByAccountIdCache.ts
src/utils/table/TableController.ts
tests/e2e/specs/AccountNavigation.cy.ts
tests/unit/contract/Contracts.spec.ts

This PR add a table of contracts recently created by an account on its AccountDetails page. A toggle allows to choose to display only the verified contracts.
To avoid cluttering the AccountDetails page, the following sections are now regrouped as tabs in a single section named 'Recent Account Operations':
- Transactions
- Created Contracts
- Staking Rewards
Fixes #901
Deployed on the staging server.
**Checklist**

feat: display contracts created by account in AccountDetails

---

src/pages/TransactionDetails.vue
src/utils/TransactionTools.ts
tests/e2e/specs/TransactionNavigation.cy.ts
tests/unit/Mocks.ts
tests/unit/transaction/TransactionDetails.spec.ts

This PR brings 2 changes:
- add token symbol(s) to any child transaction listed in the TransactionDetails, when relevant (i.e. for a `CRYPTO TRANSFER` including token/nft transfer, or any other token-related transaction type like `TOKEN MINT`)
- always list the first 10 child transactions, followed when necessary by the link `Show all N child transactions`.
- 
Fixes #540
Deploying on staging server.
**Checklist**

feat: show token symbol with child transactions

---

src/components/values/InlineBalancesValue.vue
src/utils/Timestamp.ts
src/utils/analyzer/BalanceAnalyzer.ts
tests/unit/utils/analyzer/BalanceAnalyzer.spec.ts
tests/unit/values/InlineBalancesValue.spec.ts

Fix test breaking when balance was exactly 2 year old, which should not happen outside of the context of the test...
InlineBalanceValue now processes years separately from days.
**Checklist**

fix: InlineBalanceValue unit test break

---

src/components/allowances/ApproveAllowanceSection.vue
src/components/wallet/WalletInfo.vue
src/pages/AccountDetails.vue
src/pages/Staking.vue
src/router.ts
src/utils/RouteManager.ts

Remove dead code (this was once used to open the ApproveAllowanceDialog directly from the Staking page).

chore: remove use of 'app' query parameter in AccountDetails

---

src/pages/TopicDetails.vue

Changes below remove `Show Raw Data `link from topic details.
Mirror node does not expose `topic` entity (it only provides `topic message`).
Thus there is no way to provide `Show Raw Data` action like in other detail pages.
**Checklist**

fix: removed "Show Raw Data" link from topic details view

---

src/components/contract/ContractResult.vue
src/schemas/HederaSchemas.ts

This PR adds a new field `Gas Consumed` under contract result information section to introduce the support for [HIP-859](https://hips.hedera.com/hip/hip-859)
Fixes #856 
**Checklist**

00856 add hip 859 support for gasconsumed

---

src/components/InfoTooltip.vue
src/components/Property.vue
src/components/allowances/ApproveAllowanceDialog.vue
src/components/allowances/TokenAllowanceTable.vue
src/components/contract/ContractByteCodeSection.vue
src/components/values/TokenAmount.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/TokenDetails.vue
src/pages/TransactionDetails.vue
src/schemas/HederaSchemas.ts

- Display (i) icon and tooltip instead of edit icon in the `Token Allowances` table when the token is not associated (any more) with the account.
- Fix display of token amount in the `ApproveAllowanceDialog` when the token has decimals.
- Display token symbol in dialog confirmation messages
- Clarify confirmation messages when the edit is in fact a suppression (amount set to 0)
Fixes #584
See screen captures in associated issue #584

fix: prevent editing allowance when token is not associated

---

src/components/contract/ContractByteCodeSection.vue

Changes below add an action for downloading ABI to `Contract Details` page (in ABI tab).
This button is currently visible on `previewnet` only.
It will be enabled on `testnet` and `mainnet` later.
Fixes #934 

feat: action for downloading ABI of a verified contract

---

src/components/AlertDialog.vue
src/components/dialog/Dialog.vue
src/components/token/TokenActions.vue
src/components/token/TokenInfoAnalyzer.ts

Clicking on the DISSOCIATE action when the connected account is treasury for the token will now bring up an alert dialog explaining why it is not possible.
Fixes #942 

fix: prevent dissociate token from treasury account

---

src/components/values/abi/ContractAbiEntry.vue

With changes below, `ABI` tab (in `Contract Details` page) now displays function selectors:
Fixes #943
Have a look to contract `testnet/0.0.3580249`
**Checklist**

feat: ABI tab now displays function selectors

---

src/components/values/abi/ContractAbiEntry.vue
src/components/values/abi/ContractAbiValue.vue

With changes below, `ABI` tab now displays an index before each function of the ABI:
Fixes #946
Have a look to contract `testnet/0.0.3580249`
**Checklist**

feat: ABI tab should display index for each function

---

src/components/TopNavBar.vue
src/components/dialog/DialogStatus.vue
src/components/wallet/ConnectWalletDialog.vue
src/utils/wallet/WalletDriver.ts
tests/unit/App.spec.ts
tests/unit/TopNavBar.spec.ts

- Adresses the issue by adding a couple hints for the user, to the existing error message.
- Also refactors the dialog implementation to use the new dialog components.
Fixes #895
- See related issue for reproducing the issue.
- New dialog with hints:

fix: display hint when wallet is silent

---

src/components/contract/ContractActionsLoader.ts

Truncate the call trace depth path when nesting level > 20.
Fixes #916 

fix: too many nested calls break call trace depth path.

---

src/components/values/SignatureValue.vue
src/utils/analyzer/FunctionCallAnalyzer.ts
tests/unit/App.spec.ts

Changes below add a "4byte" pills in `Call Result` and `Call Trace` sections when a signature has been resolved using `4byte.directory` database.
**Checklist**

feat: flag call signature decoded with 4byte.directory

---

src/schemas/HederaUtils.ts
src/utils/analyzer/ContractResultAnalyzer.ts
src/utils/cache/ContractResultByTsCache.ts
tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts

Changes fix `ContractResultAnalyzer` class when target contract is HTS system contract.
They also a unit test case for validating `ContractResultAnalyzer` behavior in this situation.
Fixes #952 
Use [1711559858.799271379](https://hashscan.io/testnet/transaction/1711559858.799271379) transaction to see fix in action.
**Checklist**

fix: `ContractResultAnalyzer` now correctly works when target contract is HTS

---

src/AppStorage.ts
src/components/contract/ContractByteCodeSection.vue
src/components/values/abi/ContractAbiValue.vue

Modify the ABI tab of ContractDetails page:
- show read-only functions and read-write functions as distinct sections
- allow to select the type of fragment definitions displayed:
-  All definitions
- Read-only functions
- Read-write functions
- Events
- Errors
- Other definitions
Fixes #948 
**Checklist**

feat: separate readonly functions from readwrite and add selection of fragment type displayed

---

src/schemas/SystemContractRegistry.ts
src/utils/analyzer/ContractResultAnalyzer.ts
src/utils/analyzer/FunctionCallAnalyzer.ts
tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts

Root cause is that `ContractResultAnalyzer.updateToId()` attempts (and fails) to call `ContractByAddressCache.lookup()` with contract address `0x00000000000000000167`.
With changes below, `updateToId()` now checks if target is a system contract and derives contract id from the address.
Changes also include some unit test improvements to validate this situation.
Fixes #994 
Use transaction to see fix in action: [1713967052.604875873](https://hashscan.io/previewnet/transaction/1713967052.604875873) (see #994 for details)
**Checklist**

fix: call to HTS wrongly decoded using 4byte directory

---

src/components/transfer_graphs/NftDetailsTransferGraph.vue

Fix layout issue in the transfer graph of the Recent Transactions table in NftDetails view.
None.
Before:
After:

fix: line-height in NftDetailsTransferGraph.

---

src/pages/NftDetails.vue
src/pages/TokenDetails.vue
tests/e2e/specs/TokenNavigation.cy.ts
tests/unit/token/TokenDetails.spec.ts

Similar to what exists already in `AccountDetails` and `ContractDetails`, this adds:
- a `Create Transaction` property to the `TokenDetails` view, with a link to the transaction which created that token.
- a `Mint Transaction` property to the `NftDetails` view, with a link to the transaction which minted that NFT.
Fixes #1010 
**Checklist**

feat: add `Create Transaction` link to `TokenDetails`

---

.github/workflows/flow-pull-request-checks.yaml

Decouple sonar analysis from unit tests execution in CI. This will allow to check the result of unit tests more easily when the PR comes from a different repository (in that case the sonar analysis step always fails by lack of Sonar token).
Fixes #606

chore: Decouple sonar analysis from unit tests in CI

---

src/utils/cache/NetworkCache.ts
src/utils/cache/NftCollectionCache.ts

Almost everything is in the title. We also bump the limit to 100 in these calls to reduce the number of calls to mirror-node since the goal is to get an exhaustive list of entities.
Fix can be observed on mainnet contract: 0.0.5060536

fix: duplication of 'limit' query parameter in axios calls located inside a loop.

---

.eslintrc.cjs
src/components/Tabs.vue
src/components/values/InlineBalancesValue.vue
src/components/values/SourceCodeValue.vue
src/components/values/abi/ContractAbiDialog.vue
src/components/values/abi/ContractAbiValue.vue
src/components/values/abi/ParamTypeEditor.vue
src/components/values/link/EntityIOL.vue
src/components/verification/ContractVerificationDialog.vue
src/components/verification/FileList.vue
src/pages/AccountDetails.vue
src/pages/ContractDetails.vue
src/pages/TopicDetails.vue
src/pages/Transactions.vue

Changes below:
1) update `eslint` configuration to ignore some vue warning (multi-word, reserved html name …).
2) fix another bunch of warnings (mostly unused imports).
**Checklist**

chore: improved ESLint setup and fixed another bunch of warnings

---

src/utils/analyzer/BalanceAnalyzer.ts

`BalanceAnalyzer` now extends `EntityLoaderV2`.
Theses changes do not change semantic but should fix random breaking  observed when unit tests are executed by GitHub.
> ReferenceError: window is not defined
> \> BalanceAnalyzer.scheduleNextLookup src/utils/analyzer/BalanceAnalyzer.ts:105:9
> \> BalanceAnalyzer.accountIdDidChange src/utils/analyzer/BalanceAnalyzer.ts:95:22
**Checklist**

chore: BalanceAnalyzer now extends EntityLoaderV2.

---

src/utils/RouteManager.ts
src/utils/SearchRequest.ts
src/utils/name_service/NameService.ts
src/utils/name_service/provider/AllProviders.ts
src/utils/name_service/provider/HNSProvider.ts
src/utils/name_service/provider/KNSProvider.ts
src/utils/name_service/provider/NameServiceProvider.ts
tests/unit/utils/name_service/NameService.spec.ts

Changes below refactor name service part of explorer. Goal is twofold:
1) make addition  of a new name service easier
2) ease further work on name display (see #972).
Changes summary:
1) new abstract `NameServiceProvider` is introduced with two implementations `KNSProvider` and `HNSProvider`.
2) `NameService` class singleton is now the interface used by the rest of explorer code
3) `SearchRequest` class now delegates name resolution to `NameService.resolve()`
4) `NameService` has its own unit test
**Checklist**

chore: name service refactoring

---

src/components/account/CollectionTableController.ts
src/components/token/NftHolderTableController.ts
src/components/token/TokenBalanceTableController.ts
src/components/values/TokenAmount.vue
src/pages/AccountCollection.vue
src/pages/TokenDetails.vue

- Use ascending order in the following tables:
* `NFTs` table in `TokenDetails` (for NFT collection)
* `Balances` table in `TokenDetails` (for Fungible)
Other (unrelated) fixes:
- Adds a link to the NFT Collection from the `AccountCollection` view
- Put the `NFTs`/`Balances` tables as top section in `TokenDetails` view.
- Fix alignment of token amounts in `Balances` table.
Changes visible on staging server, although mixed to more substantial NFT changes.

Fix: use ascending order in token tables

---

src/utils/SearchRequest.ts
src/utils/TransactionID.ts
tests/unit/utils/TransactionID.spec.ts

Changes below implement #1065. They also extend unit tests for `TransactionID` class.
Fixes #1065 
Transaction for testing on `mainnet`: [0.0.1280@1716576300.000000000](https://hashscan.io/testnet/transaction/1716576305.279219003)
**Checklist**

feat: enabling search with partial transaction id

---

src/components/values/BlobValue.vue

Changes below rewrite `BlobValue.decodedValue` computed to avoid side-effect on `b64EncodingFound` ref.
This is an issue flagged by `eslint`.
**Checklist**

chore: BlobValue.decodedValue rewrite to avoid side-effect in computed (eslint warning)

---

tests/unit/utils/EVMAddress.spec.ts

Changes below add some missing mock in `EVMAddress` unit test.
**Checklist**

chore: added missing mock in `EVMAddress` unit tests.

---

src/components/DashboardCard.vue
tests/unit/values/DashboardCard.spec.ts

Slightly refactor `DashboardCard`:
* avoid inserting div for content slot when empty.
* add 2 new slots for further use (`mediaContent` & `mediaDescription`)
**Checklist**

chore: add new slots in DashboardCard

---

src/components/contract/ContractActionDetails.vue
src/utils/analyzer/ContractActionAnalyzer.ts
tests/unit/MockUtils.ts
tests/unit/utils/analyzer/ABIAnalyzer.spec.ts
tests/unit/utils/analyzer/ContractActionAnalyzer.spec.ts
tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts

This is a regression introduced in #1000.
Change below restore (wrongly removed) `ContractActionAnalyzer` class and add unit tests to avoid regression.
Fixes #1117 
Use [1718213391.883698003](https://hashscan.io/mainnet/transaction/1718213391.883698003) to see fix in action.
See #1117 for additional details.
Fix is deployed on staging server.
**Checklist**

fix: `Call Trace` entries contain the same parameters for each call

---

src/components/SearchBar.vue
src/utils/SearchRequest.ts
tests/unit/utils/SearchRequest.spec.ts

Changes below refactor `SearchRequest` class. They don't include any semantic changes.
`SearchRequest` is now pass current network as a `constructor` parameter.
This will ease some upcoming unit tests with multiple networks.
**Checklist**

chore: pass network as parameter to SearchRequest constructor 

---

tests/unit/utils/SearchRequest.spec.ts

Changes below improve unit tests for `SearchRequest` class.
They don't include any semantic changes.
Each test now verifies REST urls invoked by `SearchRequest`.
**Checklist**

chore: unit tests for `SearchRequest` now validates `MockAdaptor` history.

---

src/components/SearchBar.vue
src/utils/SearchRequest.ts
tests/unit/utils/SearchRequest.spec.ts

Changes below alter `SearchRequest` class so that it uses `api/v1/topics/{topicId}` when `previewnet`.
For `mainnet` and `testnet`, behavior is unchanged (use of `api/v1/topics/{topicId}/messages`).
Changes also include unit tests adaptation to this new logic.
Fixes #1109 
**Checklist**

feat: `Search Bar` now uses `api/v1/topics` new REST call when `previewnet` is selected

---

src/components/allowances/AllowancesSection.vue
src/components/allowances/ApproveAllowanceDialog.vue
src/pages/AccountDetails.vue
src/schemas/HederaUtils.ts
src/utils/InputUtils.ts

Refactoring and fixing of the ApproveAllowanceDialog.
The AccountDetails sections are renamed:
- `Recent Account Operations` -> `Recent Operations`
- `Account Allowances` -> `Allowances`

chore: refactor allowance approval dialog

---

src/components/token/NftCell.vue

One-line change as a follow-up to PR #1013 to make media place-holder appear in NFT tables.

chore: follow up to PR #1013

---

src/components/SearchBar.vue
src/pages/MobileSearch.vue
src/pages/NoSearchResult.vue

Modify the search prompt and message displayed when the search fails, to explain that the search can be done by domain name.
Fixes #975 

feat: display that you can search by domain name

---

src/components/account/BalanceTable.vue
src/components/account/NftsTable.vue
src/components/account/TokenRelationshipsTableController.ts
src/components/token/TokenCell.vue
src/utils/cache/NftCollectionCache.ts
tests/unit/account/AccountBalances.spec.ts
tests/unit/token/NftCell.spec.ts
tests/unit/token/TokenCell.spec.ts

- Improve `NftsTable` to display as separate columns:
-  Name
- Symbol
- List of serial numbers 
- Improve `BalanceTable` to display as separate columns:
- Name
- Symbol
- Type
- Balance (for fungibles)
- Nb. of NFTs
- Also sort both tables in ASC instead of DESC order
Fixes #1085 
**Checklist**

feature: improve tables on the AccountBalances page

---

src/components/dialog/DialogStatus.vue

Fix for #949 added a new props to `DialogStatus`:
```
isSuccess: Boolean as PropType<boolean|undefined>
```
For some reason, when `isSuccess` is not specified, its value in `DialogStatus.setup()` is not `undefined` but `false`.
However everything works when `isSuccess` is declared like this:
```
isSuccess: {
type: Boolean as PropType<boolean | undefined>,
default: undefined
}
```
Fixes #1129
Go to [0.0.4419770](https://hashscan.io/testnet/contract/0.0.4419770) and run `update()` function.
**Checklist**

fix: confusing message when interacting with Smart Contract

---

src/App.vue
src/components/dashboard/MessageTransactionTable.vue
src/components/topic/TopicMessageCell.vue
src/pages/MainDashboard.vue
tests/unit/Mocks.ts
tests/unit/dashboard/MainDashboard.spec.ts
tests/unit/topic/TopicMessageCell.spec.ts

Replaces the memo column by a column providing the (possibly abridged) topic message in the `HCS Messages` table shown on the MainDashboard view.
Fixes #1053
**Checklist**

feat: show abridged message field on the home page

---

src/components/allowances/AllowancesSection.vue

Refresh tables controllers when switching from one to another type of allowance.
SearchBar e2e test is failing right now because KNS does not respond.

chore: follow-up to PR #1161

---

.github/workflows/comp-compile-explorer-code.yaml

This PR migrates the `vitest-coverage-report-action` action to the step-security maintained version
Fixes #1213 
**Checklist**

chore: migrate vitest-coverage-report-action to step-security maintained version

---

package-lock.json
package.json
tests/unit/contract/ContractResult.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/transaction/TransactionTableControllerXL.spec.ts
tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
tests/unit/utils/cache/ContractResultByTsCache.spec.ts

Bumps [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter) from 1.22.0 to 2.0.0.
Supersedes dependabot PR #1252 by including the changes needed in the tests due to breaking mock API changes (release notes linked from that PR).

chore: bump axios-mock-adapter from 1.22.0 to 2.0.0.

---

src/components/node/NetworkDashboardItem.vue
src/pages/NodeDetails.vue

No longer display Current Stake value when Stake for Consensus is 0. Instead show an info tooltip explaining why the value is 0.
Fixes #1231 
See screenshot in issue #1231

fix: current stake appears in node details when stake for consensus is 0

---

src/pages/BlockDetails.vue

All is in the title.
Fixes #1240 

Fix: reduce text of prev./next buttons in BlockDetails when on mobile screen

---

src/components/token/MetadataSection.vue
src/components/token/TokenMetadataAnalyzer.ts
tests/unit/token/MetadataSection.spec.ts

- Always display the `Metadata Details` section in NFT details view (collapsed by default).
- Always display the `Raw Metadata` property from the NFT.
- When the metadata content is retrieved, always display the `Raw Metadata` and `Content Location` properties, even if user chooses to display the content in raw form.
- Do not display metadata content properties when `None`
- A bit of `TokenMetadataAnalyzer` refactoring.
Fixes #1269 
On staging server.
**Checklist**

fix: nft metadata not visible

---

.github/workflows/comp-compile-explorer-code.yaml
.github/workflows/xflow-release-docker-image.yaml

This pull request changes the following:
- Updates the CI workflows `runs-on` labels to use the new Latitude.sh based runners.
- Closes #1313

ci: update workflows to use latitude.sh based runners

---

package.json
src/schemas/HederaUtils.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/account/AdminKeyDetails.spec.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/node/NodeDetails.spec.ts

- Added missing mocks in unit tests for `AccountDetails`, `ContractDetails`, `NodeDetails` and `AdminKeyDetails` vue (to avoid `404` warnings during test executions)
- Removed debug trace from `HederaUtils.labelForAutomaticTokenAssociation()`
- Added `--sequence.setupFiles list` to `vitest run` (it seems to fix the `window undefined` error breaking the tests in GitHub env)

chore: attempt to fix `window undefined` error, added missing mocks 

---

package.json
tests/unit/values/InlineBalancesValue.spec.ts

Changes below add some missing calls to `BalanceAnalyzer.unmount()` in `InlineBalancesValue.spec.ts`.
May be the root cause of the `window undefined` errors that are reported when unit tests are run in GitHub env…
Changes also remove use of the `--sequence.setupFiles` option in `vitest run` (a tentative fix for the pb above … that does not fix the pb above).

chore: may be a fix for window undefined error reported by unit tests in CI env

---

src/assets/styles/explorer.scss
src/pages/AccountDetails.vue
src/pages/Transactions.vue

Banner added to _Transactions_ and _AccountDetails_ view.

chore: add temporary banner related to 60-day transactions history limitation.

---

src/utils/EntityDescriptor.ts
src/utils/TransactionTools.ts

Interpret Entity ID from TOKENREJECT as Account ID instead of Token ID
Before:
After:
Fixes #1369

Fix: entity ID in TOKENREJECT

---

src/components/Tabs.vue
src/components/allowances/AllowancesSection.vue
src/components/contract/ContractByteCodeSection.vue
src/components/token/TokensSection.vue
src/pages/AccountDetails.vue
tests/unit/Tabs.spec.ts

Integrate the refactoring brought to the Tabs component as part of the work in the branch 00033_search_token_by_name.

chore: Tabs refactoring

---

src/utils/cache/ContractResultByTsCache.ts
tests/unit/contract/ContractResult.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
tests/unit/utils/cache/ContractResultByTsCache.spec.ts

Changes below add an explicit `limit=1` to in `ContractResultBtCache.load()` and update unit tests accordingly.
**Checklist**

chore: added limit=1 to ContractResultByTsCache

---

src/utils/analyzer/ContractResultsLogsAnalyzer.ts
src/utils/cache/ContractResultsLogsByContractIdCache.ts

Change below update `ContractResultsLogsByContractIdCache` class: it now returns `ContractLog[]` in place of `ContractResultsLogResponse`. No semantic change.
**Checklist**

ContractResultsLogsByContractIdCache now returns ContractLog[]

---

src/components/account/AccountTableController.ts
src/components/search/SearchAgent.ts
src/components/transaction/TransactionTableController.ts
src/components/transaction/TransactionTableControllerXL.ts
src/schemas/HederaUtils.ts
src/utils/cache/ContractResultByTsCache.ts
src/utils/cache/ContractResultsLogsByContractIdCache.ts
src/utils/cache/TransactionGroupByBlockCache.ts

Change below add logic to handle 60-day horizon enforced by mirror node on the following APIs:
- `/api/v1/accounts/{id}`
- `/api/v1/contracts/results`
- `/api/v1/contracts/results/logs`
- `/api/v1/transactions`
New logic compares response size to `limit` parameter, checks `links.next` and decide if another request must be submitted to fetch the expected result.
**Checklist**

chore: handling 60-day horizon enforced by mirror node

---

src/utils/table/RowBuffer.ts

This one-line-fix below avoid `TableController` to make one unnecessary call to `load()` method.
They don't change semantic but they make life easier when mocking in unit tests.
**Checklist**

chore: optimization in TableController

---

src/utils/analyzer/ContractAnalyzer.ts
src/utils/analyzer/FunctionCallAnalyzer.ts

Changes below updates `FunctionCallAnalyzer` class to take the case of token target into account.
Fixes #1408
User transaction `1727966148.616576069` on `testnet` to see the fix in action.
**Checklist**

feat: display responseCode symbol when call target is a token

---

.github/workflows/chart-release.yaml
chart/Chart.yaml

New CI workflow to publish helm chart to ghcr registry and github pages
closes https://github.com/hashgraph/hedera-mirror-node-explorer/issues/877

ci: new workflow to release helm chart

---

src/components/search/SearchController.ts
src/utils/AccountAlias.ts
tests/unit/search/SearchController.spec.ts

When user types `SAU` is `Search Bar`, current searching logic tries to call `api/v1/accounts/SAU` because `SAU` represents a valid `base32` encoding. Changes below fix this logic by checking the size of the `base32` decoding.
Fixes #1419 
See #1419  for testing procedure.
**Checklist**

fix: some search patterns trigger unexpected calls to api/v1/account/{accountAlias}

---

src/components/token/TokenCell.vue
tests/unit/Mocks.ts
tests/unit/account/TokensSection.spec.ts

This PR fixes missing fungible token balances for accounts with large amount of tokens. It replaces the endpoint `api/v1/balances?account.id={id}` (the call returns a max of 50 token balances per account) with  `/api/v1/accounts/{id}/tokens` to retrieve the token balances of an account. 
Fixes #1413 
**Checklist**

fix: missing fungible token balances

---

src/components/Tabs.vue

Refactor the Tab component to avoid VTU warning `Error: Not implemented: navigation (except hash changes)`.
This was caused apparently by triggering a click event on an anchor element. The onClick is now defined on the `<li>` element instead.

chore: refactor Tab component to avoid VTU warning

---

src/components/account/RejectTokenDialog.vue
src/components/token/TokenActions.vue
src/components/token/TokenCell.vue
src/pages/TokenDetails.vue
tests/unit/Mocks.ts
tests/unit/account/TokensSection.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

- As a follow-up to #1448, fixes several issues related to Token Actions:
- activation of REJECT only if connected to Hedera wallet and balance > 0
- refresh tables after token actions are completed
- Replace use of (soon to be retired) TokenRelationshipCache by TokenAssociationCache

fix: token actions activation and table refresh

---

src/utils/RouteManager.ts

`RouteManager.updateSelectedNetworkSilently()` now uses `this.router` in place of `router` global var (like everywhere else in this class). Removed some dead code too. No semantic changes.
**Checklist**

chore: fix router reference in RouteManager (and removed dead code)

---

src/pages/AccountDetails.vue

Changes below fix a regression in `Recent Operations` table of `Account Details` page.
Transaction type filter became inoperative when enabling `<script setup>` in `AccountDetails.vue`.
**Checklist**

fix: transaction type filter is broken in Recent Operations section

---

src/components/account/UpdateAccountDialog.vue
src/components/allowances/ApproveAllowanceDialog.vue
src/components/dashboard/HbarMarketDashboard.vue
src/components/staking/StakingDialog.vue
src/components/token/TokenInfoAnalyzer.ts
src/pages/ContractDetails.vue
src/pages/MobileSearch.vue
src/pages/TopicDetails.vue
src/utils/parser/AccountLocParser.ts
tests/unit/App.spec.ts
tests/unit/utils/AccountLocParser.spec.ts
tests/unit/utils/analyzer/TokenInfoAnalyzer.spec.ts

Changes below make sure that `RouteManager.currentNetwork` and `RouteManager.currentNetworkEntr`y are used in all the places where they should be.
**Checklist**

chore: generalized usage of RouteManager.currentNetwork and currentNetworkEntry

---

src/components/account/UpdateAccountDialog.vue
src/components/allowances/ApproveAllowanceDialog.vue
src/components/staking/StakingDialog.vue
src/schemas/HederaUtils.ts
src/schemas/NetworkRegistry.ts
src/utils/InputUtils.ts
src/utils/parser/AccountLocParser.ts

Changes below move `checksum()`, `extractChecksum()` and `stripChecksum()` methods from `NetworkManager` to `HederaUtils` (those methods don't rely on `NetworkManager.this`).
**Checklist**

chore: moved some routines from NetworkManager to HederaUtils

---

src/pages/MobileMenu.vue

Changes below migrate `MobileMenu` view to `<script setup>`.
They also remove unused `MobileMenu.searchedId` props.
**Checklist**

chore: migrate MobileMenu view to <script setup>

---

networks-config-example.json
src/components/account/UpdateAccountDialog.vue
tests/unit/Mocks.ts
tests/unit/node/NodeDetails.spec.ts

- follow-up to PR #1485: disable editing properties related to staking when the current network configuration does not have enableStaking = true.
- (unrelated:) fix NodeDetails unit test (abusively copy-pasted from AccountDetails unit test)

chore: update account without staking

---

CONFIGURATION.md
public/core-config.json
src/components/token/NftCell.vue
src/components/token/TokenMetadataAnalyzer.ts
src/components/values/BlobValue.vue
src/config/CoreConfig.ts
src/pages/NftDetails.vue
src/pages/TokenDetails.vue
src/utils/URLUtils.ts
tests/unit/values/BlobValue.spec.ts

- rename `CoreConfig.ipfsGatewayUrlPrefix` to `CoreConfig.ipfsGatewayURL` 
- Although the implementation now checks for `CoreConfig.ipfsGatewayURL = null`, the default value for this parameter remains `https://gateway.pinata.cloud/ipfs/` for the time being.
- refactor `TokenMetadataAnalyzer` such that logic to retrieve assets from attributes values is a bit more modular and shared.
- refactor BlobValue to reuse some of the above.
**Checklist**

chore: refactor ipfs config and metadata retrieval

---

CONFIGURATION.md
public/core-config.json
src/components/MediaContent.vue
src/components/token/NftCell.vue
src/components/token/NftPreview.vue
src/components/token/TokenMetadataAnalyzer.ts
src/components/values/BlobValue.vue
src/config/CoreConfig.ts
src/pages/NftDetails.vue
src/pages/TokenDetails.vue
src/utils/URLUtils.ts
tests/unit/Mocks.ts
tests/unit/utils/analyzer/TokenMetadataAnalyzer.spec.ts

Add support for NFT metadata and related assets stored on Airwaves -- i.e. identified either by an URI of type `ar://` or by a 43-byte CID.
Also fix autoplay of video content -- current implementation never auto-plays videos.
Fixes #1396 
Example of such NFT: 
**Checklist**

feat: support NFT metadata stored on Arweave

---

src/components/values/abi/ContractAbiDialog.vue

`ContractAbiDialog` view now uses `<script setup>` syntax.
**Checklist**

chore: ContractAbiDialog view now uses <script setup> syntax.

---

src/components/search/SearchController.ts
src/components/utils/InputChangeController.ts

Changes below move `InputChangeController` class from `SearchController.ts` to a separate file.
**Checklist**

chore: moved InputChangeController class from SearchController to its separate file

---

src/components/values/abi/ContractCallBuilder.ts
src/schemas/MirrorNodeSchemas.ts
src/utils/JSUtils.ts

Changes below extract message available in error response returned by api/v1/contracts/call.
Fixes #1531 
See call to name() in contract [0.0.5198819](https://hashscan.io/testnet/contract/0.0.5198819?ps=1) on testnet.
With changes below, ABI looks like this:
**Checklist**

feat: Contract Details / Contract Bytecode / ABI tab now exposes error message available in api/v1/contracts/call response

---

src/components/contract/ContractByteCodeSection.vue
src/utils/analyzer/ContractAnalyzer.ts
tests/unit/utils/ContractAnalyzer.spec.ts

With changes below, `Contract Details` page now displays EVM version when contract is verified.
ContractAnalyzer unit test is also updated.
Fixes #1538 
On testnet, contract [0.0.5204343](https://hashscan.io/previewnet/contract/0.0.5204343) has `EVM version` `shanghai`.
On previewnet, contract  [0.0.12287](https://hashscan.io/previewnet/contract/0.0.12287) has `EVM version` `cancun`.
**Checklist**

feat: contract detail page now displays EVM version for verified contract

---

README.md
chart/Chart.yaml
chart/templates/NOTES.txt
chart/templates/_helpers.tpl
chart/templates/cert-manager/certificate-requests.yaml
chart/templates/configmap.yaml
chart/templates/deployment.yaml
chart/templates/hpa.yaml
chart/templates/ingress.yaml
chart/templates/poddisruptionbudget.yaml
chart/templates/service.yaml
chart/templates/serviceaccount.yaml
chart/values.yaml
docker-compose.yml
package-lock.json
package.json
public/site.webmanifest

- These changes rename (hopefully) most of the remaining occurrences of (Hedera, Hashgraph, Swirlds) to Hiero.
- Notable exceptions, perhaps not exhaustive:
- copyright notices in all source files, to be addressed later
- paths for files, repositories, etc...  to be addressed later
- CookiesDialog.vue component, which will be taken care of in a separate PR.
Related to #1430

chore: renaming (Hedera, Hashgraph, Swirlds) -> Hiero

---

CONFIGURATION.md
public/core-config.json
src/App.vue
src/components/CookiesDialog.vue
src/config/CoreConfig.ts

The changes below introduce a new `CoreConfig.cookiesDialogContent` configuration parameter to control the content and appearance of the cookies dialog. 
Note that if not set, the value of the `googleTagID` parameter is ignored.
On the other hand, if `cookiesDialogContent` is set, and `googleTagID` is not, the dialog will be show but will have no other effect (for the time being). This will allow us to use cookies for other features if needed later.
Related to #1430

chore: add configuration for cookies acceptance dialog

---

src/assets/branding/install-branding.sh

Fix install-branding.sh, which was broken in PR #1543. Its execution left the repository in a complete mess.

chore: fix install-branding.sh.

---

chart/templates/configmap.yaml
chart/values.yaml

This PR adds support for core.config.json within the mirror node explorer helm chart. 
The default values used were copied from https://github.com/hashgraph/hedera-mirror-node-explorer/blob/main/public/core-config.json

Add support for core-config.json

---

src/pages/AccountDetails.vue
tests/unit/account/AccountDetails.spec.ts

Changes below remove the `Key Alias` field from `Account Details` page and adapt unit tests.
Fixes #1550 
**Checklist**

feat: remove "Key Alias" from account view

---

tests/e2e/specs/SearchBar.cy.ts

Change below temporarily disable e2e test related to KNS in SearchBar.cy.ts.
This test regularly fails because on KNS deployment issue and pollutes PR review checks.
**Checklist**

chore: temporarily disable KNS test in SearchBar.cy.ts.

---

src/components/token/TokenMetadataAnalyzer.ts
src/components/values/BlobValue.vue
src/utils/HCSURI.ts
src/utils/URLUtils.ts
tests/unit/Mocks.ts
tests/unit/utils/analyzer/TokenMetadataAnalyzer.spec.ts

These changes
- build upon the recently added support for HCS-1 content in topics, to enhance TokenMetadataAnalyzer and hence allow interpretation of NFT metadata (and related assets) stored as HCS-1 topics.
- display HCS-1 URIs (e.g. `hcs://1/0.0.5016824` ) as hyperlinks to the corresponding TopicDetails view.
Relates to #1523 

feat: add HCS-1 support for NFT metadata

---

src/components/page/NavMenuItem.vue
src/components/page/TopNavBar.vue
src/pages/MobileMenu.vue
src/utils/RouteManager.ts

Changes below introduce new `NavMenuItem` view and use it in `TopNavBar` and `MobileMenu` views.
Fixes #1560 
**Checklist**

chore: introduced NavMenuItem and used it in TopNavBar and MobileMenu.

---

src/schemas/MirrorNodeUtils.ts
src/utils/EntityID.ts
tests/unit/transfer_graphs/layout/HbarTransferLayout.spec.ts

With these trivial changes:
- account 801 is identified as `Node reward account` in the transfer graphs
- transfers to 801 are treated as fees similar to the transfers to 800
Fixes #1562 
Before:
After:

feat: label account 0.0.801 as the node reward account 

---

src/components/contract/ContractResult.vue
src/pages/TransactionDetails.vue
src/schemas/MirrorNodeSchemas.ts
src/schemas/MirrorNodeUtils.ts
src/utils/cache/NetworkFeesCache.ts

With the changes below:
- we use script setup syntax in ContractResult and do a tiny bit of refactoring
- we always display the Gas Price in the Contract Result and get its value from `/api/v1/network/fees` at the corresponding timestamp. 
[See detailed analysis of the issue in #1559]
Fixes #1559 
Before: 
After:

fix: wrong hbar values assigned to Gas Limit, Gas Used, and Gas Consumed

---

chart/values.yaml

Add the `ingress` in values as it is required
This PR modifies
* adds back the `ingress` value in the values file
**Related issue**: https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1570

fix: Add the `ingress` in values as it is required

---

src/components/page/PageFrame.vue

Trivial. Fix erroneous path for `block-chain-bg.png` in `PageFrame.vue`

fix: block-chain-bg.png does not show up in top navigation bar.

---

src/utils/B64Utils.ts
src/utils/parser/AccountLocParser.ts
tests/unit/utils/AccountLocParser.spec.ts

Changes below re-implement `byteToHex()` and `hexToByte()` routines using `etherjs` library.
They also remove unused `AccountParser.aliasByteString()`.
**Checklist**

chore: re-implement hex utils using etherjs library

---

.github/workflows/flow-pull-request-formatting.yaml

This pull request changes the following:
- Updates the `flow-pull-request-formatting.yaml` workflow to use the correct runner group
- Closes #1604

ci: update the formatting workflow to use the correct runner group

---

package-lock.json
package.json

Changes below move Explorer to release `2.0.12` of `@hedera-name-service/hns-resolution-sdk`.
Note: this latest release has no dependency on `web3` library anymore which removes a blocker for Hiero migration process.
**Checklist**

chore: moving @hedera-name-service/hns-resolution-sdk to 2.0.12.

---

cypress.config.js
src/pages/AccountDetails.vue
src/pages/Staking.vue
src/pages/Transactions.vue
tests/e2e/specs/AccountNavigation.cy.ts
tests/e2e/specs/MobileSearch.cy.ts
tests/e2e/specs/SearchBar.cy.ts

- put temporary banner only on Staking page
- add InfoTooltip on `Pending Reward` property
This will only be activated once .env VARIABLE is set in the deployment repository.

chore: add warning banner + info tooltip related to the possible pending reward calculation inaccuracy

---

src/utils/table/RowBuffer.ts
src/utils/table/TableController.ts
tests/unit/utils/TableController.spec.ts

Changes below fix auto refresh logic in two ways:
- `RowBuffer` class now manages a single abort flag (`RowBuffer.abortCounter` replaces `refreshCounter` and `moveToPageCounter`).
- `TableController.refreshBuffer()` now checks `autoRefresh` value (which might have changed in-between) before restarting the next refresh.
Fixes #1634 
See #1634 for reproducing issue.
**Checklist**

fix: auto refresh stops and restarts immediately when clicking on Pause in Transactions table

---

src/components/contract/ContractResult.vue

All is said in the title.
Note this is in no way a breaking change, but marked with `fix!` in order to trigger the switch to version numbers 25.x.y moving forward.
Fixes #1621 

fix!: Add info-tooltips for Gas Used and Gas Consumed in ContractResult.

---

src/charts/hgraph/NetworkFeeController.ts

This is a one-line change to fix tbar to hbar conversion in `NetworkFeeController.transformMetrics`() method.
None
Go to `Dashboard` tab and look at `Network Fees` chart in `Network` section : value for Feb 2024 should be `20_000_000` (not `200_000_000`).
**Checklist**

fix: fixed tinybar to hbar conversion in NetworkFeeController

---

src/pages/MainDashboard.vue
tests/unit/dashboard/MainDashboard.spec.ts

Changes below remove some unused code: `MainDashboard` vue creates a `TPSMetricLoader` instance which is not used but generates some useless calls to `api/v1/blocks`.
None
1) Go https://hashscan.io
2) Open `Network` tab in `Developer` panel
=> without the fix, periodic calls to `api/v1/blocks` are executed
=> with the fix, those calls no longer exist
**Checklist**

chore: removing unused code from MainDashboard vue

---

src/components/ArrowLink.vue
src/components/token/TokensSection.vue
src/pages/TransactionDetails.vue
tests/e2e/specs/TransactionNavigation.cy.ts
tests/unit/transaction/TransactionDetails.spec.ts

In TransactionDetails view:
- Add link `Transactions with same ID ->`
- Align style of the following links:
- `Scheduled transaction ->`
- `Schedule create transaction ->`
- `All nn child transactions ->`
Fixes #1645 
-----
-----
-----

fix: bring back link to all transactions with same ID

---

src/dialogs/download/TransactionDownloadDialog.vue
src/pages/AccountDetails.vue

Fix for https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1185

fix: download Button name and tooltip added

---

src/components/InfoTooltip.vue
tests/unit/infoTooltip.spec.ts

Bring back the use of a triangle alert icon (vs. info icon) in InfoTooltip in case of warning message (was lost during UI revamp).

chore:  different icon in InfoTooltip for warning message

---

src/pages/NftDetails.vue
tests/unit/token/NftDetails.spec.ts

- Add property to display metadata name of the NFT. This used to be displayed at the title of the card and disappeared during the UI revamp.
- Re-enable the corresponding unit test.

fix: bring back (metadata) name of NFT in NftDetails.

---

src/components/search/SearchBar.vue

1-line change to use 16px font size in SearchBar input field. With a smaller font, certain browsers (incl. Safari) automatically zoom in to ease the input and never zoom back.

fix: boost font size in SearchBar input field to avoid auto zoom.

---

tests/e2e/specs/SearchBar.cy.ts
tests/e2e/specs/local/NameServiceSearch.cy.ts

Extract the tests querying KNS and HNS (as `NameServiceSearch`) and move under `local/` directory to exclude from CI testing.

chore: exclude SearchBar e2e tests which query name services from CI tests.

---

src/components/values/ComplexKeyValue.vue
src/components/values/KeyValue.vue
src/pages/AdminKeyDetails.vue
src/pages/NodeAdminKeyDetails.vue
src/pages/NodeDetails.vue
src/schemas/MirrorNodeSchemas.ts
src/utils/RouteManager.ts
src/utils/analyzer/NodeAnalyzer.ts
tests/unit/Mocks.ts
tests/unit/account/AccountDetails.spec.ts
tests/unit/account/NodeAdminKeyDetails.spec.ts
tests/unit/node/NodeDetails.spec.ts

This PR handles the new admin_key property for nodes:
- displays the property inline in NodeDetails when the key is simple, and a link to a dedicated page when complex (similar to what is done for accounts.
- adds a NodeAdminKeyDetails page to display the details of a node admin_key, similar to AdminKeyDetails for account key.
Fixes #1720
- deployed on staging server
- screenshots below:
____
____

feat: Add the admin_key for nodes

---

src/utils/wallet/client/WalletClient_Ethereum.ts

Changes below add missing implementation for `WalletClient_Ethereum.callContract()`.
Fixes #1735
See #1735 for reproducing the issue.
**Checklist**

fix: ABI tab unable to call a function when connected through Metamask extension

---

src/components/page/header/MainDashboardHeader.vue
src/pages/MainDashboard.vue
tests/e2e/specs/TopNavigationBar.cy.ts
tests/unit/App.spec.ts

Change the design of the `MainDashboard` page when chart data is not available on a network:
- remove the empty charts
- make the header take all available vertical space, with the search bar in the middle.
On staging server.

chore: remove empty charts from home page when not supported.

---

src/charts/core/ChartController.ts
src/charts/hgraph/ActiveAccountController.ts
src/charts/hgraph/HgraphChartController.ts
src/charts/hgraph/NetworkFeeController.ts
src/charts/hgraph/TPSController.ts
src/charts/hgraph/TxOverTimeController.ts
src/components/ThemeController.ts
src/styles/explorer.css

Changes below turn `Network Fees` chart as a linear chart with the gradient and colors specified in UI design.
**Checklist**

chore: Network Fees chart now becomes linear chart and uses gradient and colors from UI design spec

---

src/charts/core/ChartController.ts
src/charts/core/ChartView.vue
tests/unit/globalSetup.js

`ChartController` now triggers data load only when its HTML container element intersects viewport.
This enables to avoid useless queries to Hgraph data server.
**Checklist**

chore: ChartController now triggers data load when its HTML container intersects viewport

---

src/dialogs/wallet_chooser/WalletChooserDialog.vue
src/utils/wallet/WalletConnectAgent.ts
src/utils/wallet/WalletManagerV4.ts

When `cookies` are fully disabled, Explorer crashes at load time and displays a blank page.
Root cause is the following `import` line in `WalletConnectAgent` class:
```
import SignClient from "@walletconnect/sign-client";
```
=> `@walletconnect/sign-client` does not work when `cookies` are fully disabled.
Changes below make sure that Explorer starts correctly whether cookies are disabled or not.
Import line above is replaced by a dynamic import (which also reports an error but at connection time only).
In that case, Explorer reports issue with a specific message:
Additional change: when there is no wallet at all, Wallet Chooser dialog now displays the following message (in place of an empty list of wallets):
**Checklist**

fix: explorer gives a blank page when cookie are fully disabled

---

src/components/search/SearchAgent.ts
src/utils/TransactionID.ts
tests/unit/search/SearchController.spec.ts
tests/unit/utils/TransactionID.spec.ts

Changes below enables `Search Bar` to handle transaction id with its `scheduled` flag and directly navigate to `Transaction Details` of the scheduled transaction (in place of the `Transaction By ID` page).
Fixes #1746 
1) Go to Explorer
2) Type `0.0.4609960@1742840362.066682661?scheduled` in `Search Bar`
=> direct link to scheduled transaction details is proposed
**Checklist**

feat: search by scheduled transaction ID

---

src/charts/core/ChartRange.ts
src/charts/core/RangeSelectView.vue
src/charts/hgraph/TxOverTimeController.ts

Changes below add `30d` to `Chart Range Selector`.
**Checklist**

feat: adding 30d chart range

---

src/components/node/NodeTable.vue

Changes below update pagination setup in `Node Table` view.
This enables to fix the truncated list of  network nodes observed recently.
It seems that, in latest release of Oruga, default value `o-table.per-page` is now 20 (and no longer the number of items in data array).  Fix consists to set `per-page` with item count.
**Checklist**

fix: fixing pagination in Node Table

---

src/components/values/link/ScheduleLink.vue
src/components/values/link/SmartLink.vue
src/pages/ScheduleDetails.vue
src/pages/TopicDetails.vue
src/pages/TransactionDetails.vue
src/schemas/MirrorNodeSchemas.ts
src/styles/explorer.css
src/utils/EntityDescriptor.ts
src/utils/RouteManager.ts
src/utils/cache/CacheUtils.ts
src/utils/cache/ScheduleByIdCache.ts
tests/e2e/specs/TransactionNavigation.cy.ts
tests/unit/Mocks.ts
tests/unit/transaction/ScheduleDetails.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

Add proper support for schedule entities by adding a ScheduleDetails page and populating it by leveraging the data provided by the `api/v1/schedules/{scheduleId}` end-point of the Mirror Node.
Also slightly improve the related properties in TransactionDetails page.
Fixes #1747 
**Checklist**

feat: support for schedule entities

---

src/components/search/SearchAgent.ts
src/components/search/SearchController.ts
tests/unit/search/SearchController.spec.ts

Changes below enable `Search Bar` to search schedules by id.
Fixes #1747 
Sample schedule on `mainnet`: `0.0.1754091`
**Checklist**

feat: Search Bar now supports schedule search by id

---

src/components/node/NetworkDashboardItemV2.vue
src/pages/NodeDetails.vue
src/utils/analyzer/NodeAnalyzer.ts
tests/unit/node/NodeDetails.spec.ts
tests/unit/transaction/ScheduleDetails.spec.ts

Miscellaneous fixes on the NodeDetails page when the Node ID is unknown:
- display notification banner
- display None values for all properties
- no info tooltip, or extra information in NetworkDashboardItemV2 elements
- ...
Before:
After:

fix: miscellaneous NodeDetails fixes

---

src/components/token/TokenMetadataAnalyzer.ts
src/components/topic/HCSContentSection.vue
src/components/transaction/TransactionAnalyzer.ts
src/components/values/BlobValue.vue
src/pages/ScheduleDetails.vue
src/utils/B64Utils.ts
src/utils/TransactionHash.ts
src/utils/analyzer/NodeAnalyzer.ts
src/utils/bytecode_tools/disassembler/utils/helpers.ts
src/utils/cache/HCSAsset.ts
src/utils/wallet/client/WalletClient_Hiero.ts
tests/unit/search/SearchController.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

Changes below replace calls to `Buffer.from()` and `Buffer.toString()` by their browser equivalent.
`Buffer` class is part of `nodejs` environment and is not natively available in `browser` environment.
With those changes, Explorer source code no longer depends on `Buffer`/`nodejs`. 
It relies on `ethers` library (which has browser compatible functions for base64, hex and utf8 encoding).
**Checklist**

chore: removing dependencies on Buffer class

---

src/utils/downloader/EntityDownloader.ts

Changes below update cvs generator so that `#date` column includes both `date` and `time`.
Fixes #1764 
**Checklist**

feat: include transaction timestamps (HH:MM:SS) in exported CSV output

---

public/style-config.css
src/styles/explorer.css

[Follow-up to PR https://github.com/hiero-ledger/hiero-mirror-node-explorer/pull/1790]
CSS font directives (`@import` and `@font-face`) need to be in `explorer.css` since the fonts are located inside the repo.
These have been unduly moved to `public/style-config.css` alongside the CSS variables in the PR above.

chore: move CSS font directives back to explorer.css

---

src/utils/ERCUtils.ts

Use a private axios instance in `ERCUtils` to make calls to `api/v1/contracts/call`. These contract calls return CONTRACT_REVERT_EXECUTED when the contract does not support the interface, causing MN to return an HTTP 400 error, which is by default highlighted in the page header by `AxiosMonitor`.

fix: mask HTTP 400 errors in ContractDetails

---

package-lock.json
package.json

Remove direct dependency on `sass` module, since SASS/SCSS preprocessing is no longer used.
Note an indirect dependency on `sass` remains.

chore: remove dependency on sass module.

---

public/mainnet/erc-1155.json
public/mainnet/erc-20.json
public/mainnet/erc-721.json

This PR updates the ERC Registry to include the most recent ERC-20, ERC-721, and ERC-1155 tokens.
**Registry Update Summary**:
- **Hedera Network**: mainnet
- **New ERC-20 Records Added**: 45
- **New ERC-721 Records Added**: 8
- **New ERC-1155 Records Added**: 1
- **Indexing Duration**: 10 seconds
- **Last Indexed Time**: 04-07-2025

chore: update ERC Registry with latest ERC-20, ERC-721, and ERC-1155 tokens on Hedera mainnet

---

tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts

Changes below improved `FunctionCallAnalyzer` unit tests.
Tests now checks expected `REST` calls using `fetchGetURLs()`.
**Checklist**

chore: improving FunctionCallAnalyzer unit tests

---

src/utils/analyzer/FunctionCallAnalyzer.ts
tests/unit/contract/ContractResult.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/utils/analyzer/ContractActionAnalyzer.spec.ts
tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts

Changes below make sure that `FunctionCallAnalyzer` calls `4byte` directory only when no ABI has been found in `SystemContractRegistry` or in `sourcify`.
Unit tests are updated accordingly.
**Checklist**

chore: avoid unneeded calls to 4byte directory in FunctionCallAnalyzer

---

src/schemas/MirrorNodeUtils.ts
tests/unit/contract/ContractResult.spec.ts
tests/unit/schemas/MirrorNodeUtils.spec.ts

Changes below fix `decodeSolidityErrorMessage()` in `MirrorNodeUtils.ts` and add some unit tests.
Fixes #1878
See [1745842640.274210000](https://hashscan.io/mainnet/transaction/1745842640.274210000).
See contract calls in [0.0.5924913](https://localhost:5173/testnet/contract/0.0.5924913) for various error cases.
**Checklist**

fix: some error messages are not decoded in Call Trace section

---

tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts

Changes below add a test case for `HTS.redirectForTaken()` to `FunctionCallAnalyzer` unit tests.
It validates singular encoding rules used by this call.
**Checklist**

chore: adding test case for redirectForToken() to FunctionCallAnalyzer unit tests

---

eslint.config.mjs
src/components/allowances/AllowancesSection.vue
src/components/transaction/TransactionAnalyzer.ts
src/components/transaction/TransactionSummary.vue
tests/unit/contract/ContractResultLogEntry.spec.ts
tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts
tests/unit/utils/bytecode_tools/bytecodeDisassembler.spec.ts

Changes below re-enable `@typescript-eslint/no-unused-expressions` in `eslint.config.mjs` and fix the reported warnings.
**Checklist**

chore: re-enabling @typescript-eslint/no-unused-expressions in eslint.config.mjs

---

public/networks-config.json
src/components/contract/ContractERCSection.vue
src/config/NetworkConfig.ts
src/pages/ContractDetails.vue
src/utils/analyzer/ERCAnalyzer.ts
src/utils/cache/CacheUtils.ts
src/utils/cache/ERC1155Cache.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/search/SearchController.spec.ts

Leverage the information collected in `erc-1155.json` to flag ERC-1155 contracts in the ContractDetails view.
Given the current infrastructure at hand, the explorer is not able to display more information about these.
#1500

feat: flag ERC-1155 contracts

---

vite.config.ts

Changes below fix `resolveVersion()` function in `vite.config.ts`.
This function contains an unused operand that is reported by `eslint`:
```
/WS/hiero-mirror-node-explorer/vite.config.ts
18:12  error  Unexpected constant truthiness on the left-hand side of a `||` expression  no-constant-binary-expression
```
**Checklist**

chore: fixing resolveVersion() in vite.config.ts

---

src/components/transaction/TransactionSummary.vue
src/utils/TransactionTools.ts
tests/unit/block/BlockDetails.spec.ts

Refactor TransactionSummary to use EntityIOL rather than plain entity ID strings in the summary.
This is in preparation of supporting public labels and being ready to display those in place of the corresponding ID.

chore: refactor TransactionSummary

---

src/components/Tooltip.vue
src/components/node/NodeTable.vue

Refactor `Tooltip component` and add a `#content` slot so it can be leveraged instead of using directly o-tooltip when the tooltip content is structured. Apply to NodeTable.

chore: refactor Tooltip component

---

tests/unit/values/BlobValue.spec.ts

Changes below update unit tests for `BlobValue` vue:
1. a new test case validates `BlobValue` with a custom IPFS gateway
2. `globals.plugins: [router]` option (blindly) passed to `mount()` are removed
**Checklist**

chore: updating unit tests for BlobValue view

---

src/components/MirrorLink.vue
src/config/NetworkConfig.ts
src/utils/RouteManager.ts

Change below rename `NetworkEntry.mirrorNodeURL` field as `url` to be consistent with `networks-config.json`.
This will also ease unit test writing.
**Checklist**

chore: renaming NetworkEntry.mirrorNodeURL as url

---

src/components/values/DomainLabel.vue
src/components/values/EntityLabel.vue
src/components/values/PublicLabel.vue
src/styles/explorer.css

- Make EntityLabel slightly bigger
- Include navigation icon (when url field defined) instead of shy icon outside of label
**Before:**
**After:**

chore: make labels bigger and include navigation icon

---

src/components/account/AccountCreatedContractsTable.vue
src/components/account/AccountTable.vue
src/components/account/FungibleTable.vue
src/components/account/NftsTable.vue
src/components/account/PendingFungibleAirdropTable.vue
src/components/account/PendingNftAirdropTable.vue
src/components/account/VerifiedContractsTable.vue
src/components/block/BlockTable.vue
src/components/block/BlockTransactionTable.vue
src/components/contract/ContractResultTable.vue
src/components/contract/ContractTable.vue
src/components/contract/ERC20ByNameTable.vue
src/components/contract/ERC721ByNameTable.vue
src/components/node/NodeTable.vue
src/components/staking/StakingRewardsTable.vue
src/components/token/NftHolderTable.vue
src/components/token/TokenBalanceTable.vue
src/components/token/TokenTable.vue
src/components/token/TokensByNameTable.vue
src/components/token/TokensByPopularityTable.vue
src/components/topic/TopicMessageTable.vue
src/components/topic/TopicTable.vue
src/components/transaction/NftTransactionTable.vue
src/components/transaction/TransactionBatchTable.vue
src/components/transaction/TransactionByIdTable.vue
src/components/transaction/TransactionTable.vue
src/utils/RouteManager.ts

Change below fix type declarations of `@cell-click` callbacks passed to `o-table` views.
These callbacks should expect an `Event` (not a `MouseEvent`).
This is preparatory work before re-enabling type checking in `oruga-ui` component (currently broken).
**Checklist**

chore: fixing typing of handleClick() methods 

---

src/components/allowances/AllowancesSection.vue
src/components/contract/ContractByteCodeSection.vue
src/components/contract/ContractResultTrace.vue
src/components/token/TokensSection.vue
src/pages/Staking.vue

Action buttons (in details pages) are no longer using network color (like default button in dialog).
The only remaining exception is on the Staking page.
Unrelated: remove display of checksum in title of MyStaking section (a label may be displayed in place of the ID here). Furthermore the checksum is useful here since this is by definition the account of the user (account from the connected wallet), so there is no ambiguity.

chore: homogenise action buttons

---

src/components/values/FunctionError.vue
src/components/values/FunctionInput.vue
src/components/values/FunctionResult.vue
src/components/values/SignatureValue.vue
src/utils/analyzer/ContractResultAnalyzer.ts
src/utils/analyzer/FunctionCallAnalyzer.ts
tests/unit/contract/ContractResult.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts

Changes below enhance contract decoding logic to decode constructors parameters (when contract is verified).
They also include unit test updates.
Before:
After:
Use testnet transaction [1708535265.079646164](https://hashscan.io/testnet/transaction/1708535265.079646164).
**Checklist**

feat: Contract Details now decodes constructor when contract is verified

---

src/pages/TransactionDetails.vue

Fix spacing between items when there are several tokens associated in the same transaction.
**Before**:
**After**:

fix: layout of ASSOCIATED TOKENS value in the details of a TOKEN ASSOCIATE transaction

---

src/components/values/ByteCodeValue.vue
src/components/values/HexaDumpValue.vue

Add prop to HexaDumpValue allowing to suppress its scrollbar when used in a code box context which already provides one.
Fixes #1939

fix: double scroll bar in Contract Bytecode section

---

src/components/DashboardCardV2.vue
tests/unit/values/DashboardCard.spec.ts

- Restore ability for `DashboardCardV2` to be non-collapsible -- which is requested by the absence of prop `collapsibleKey`.
- Add unit test cases for this.

fix: ability for sections to be non-collapsible

---

src/components/contract/ContractResult.vue
src/utils/analyzer/ContractResultAnalyzer.ts
tests/unit/contract/ContractResult.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts
tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts

Change below refactor `ContractResultAnalyzer` class : this is now passed a `Transaction` object in place of a timestamp.
This avoids one extra call to `api/v1/transactions`.
Unit tests are updated accordingly.
**Checklist**

chore: ContractResultAnalyzer is now passed a Transaction object

---

tests/e2e/specs/ContractNavigation.cy.ts

Fix ContractNavigation.cy.ts e2e which is intermittently failing on CI. The test logic is in fact wrong and the surprising thing is actually that it was not always failing.

chore: fix ContractNavigation e2e test.

---

src/components/contract/ContractActionDetails.vue
src/components/values/FunctionError.vue
src/components/values/FunctionValue.vue
src/components/values/SignatureValue.vue
src/schemas/MirrorNodeUtils.ts
src/utils/analyzer/ContractActionAnalyzer.ts
src/utils/analyzer/ContractLogAnalyzer.ts
src/utils/analyzer/ContractResultAnalyzer.ts
src/utils/analyzer/FunctionCallAnalyzer.ts
src/utils/analyzer/call/FourByteAnalyzer.ts
src/utils/analyzer/call/FunctionCallDecoder.ts
tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts

Changes below:
- refactor `FunctionCallAnalyzer` (it now delegates some tasks to `FunctionCallDecoder` and `FourByteAnalyzer`)
- add logic for decoding call embedded in `redirectForToken()`(which fixes #2005)
- update unit tests
- fix a styling issue in `SignatureValue` view
Fixes #2005
- Open transaction [1748689276.438110000 ](https://hashscan.io/testnet/transaction/1748689276.438110000 )
- Go to `Call Trace` section
- Expand last call trace item
Before:
After:
**Checklist**

feat: better decoding of calls to redirectForToken()

---

src/components/allowances/HbarAllowanceTable.vue
src/components/allowances/TokenAllowanceTable.vue
src/schemas/MirrorNodeSchemas.ts
tests/unit/account/HbarAllowanceTable.spec.ts
tests/unit/account/NftAllSerialsAllowanceTable.spec.ts
tests/unit/account/NftAllowanceTable.spec.ts
tests/unit/account/TokenAllowanceTable.spec.ts

For HBAR and Fungible Token allowances, display the (remaining) amount available in addition to the granted amount since both values are now available in the API.
Add unit tests for the various allowance tables: 
`HbarAllowanceTable, TokenAllowanceTable, NftAllowanceTable, NftAllSerialsAllowanceTable`
Fixes #2031 

feat: display remaining allowance

---

eslint.config.mjs
src/utils/wallet/WalletConnectAgent.ts

Changes below fix a warning reported by `eslint` when `no-async-promise-executor` flag is on.
They re-write `WalletConnectAgent.waitForApprovalOrModalClose()` to avoid passing an `async` function to `Promise` constructor. And they switch  `no-async-promise-executor` flag on.
**Checklist**

chore: WalletConnectAgent class no longer use async promise executor

---

eslint.config.mjs
src/gtag.ts

Changes below enable `@typescript-eslint/no-unsafe-function-type` flag in `eslint` and fix reported warning.
**Checklist**

chore: enabling @typescript-eslint/no-unsafe-function-type flag in eslint config

---

eslint.config.mjs

Changes re-enable `no-require-imports` and `no-this-alias flags` in `eslint` config.
Current code does not trigger any warning for those flags.
**Checklist**

chore: re-enabled no-require-imports and no-this-alias flags in eslint config.

---

src/components/transaction/TransactionByIdTable.vue
src/components/transaction/TransactionGroupAnalyzer.ts
src/pages/TransactionDetails.vue
src/schemas/MirrorNodeSchemas.ts
tests/unit/Mocks.ts
tests/unit/transaction/TransactionByIdTable.spec.ts
tests/unit/transaction/TransactionDetails.spec.ts

When we get a set of transactions with the same ID, we currently assumes that once we find child (i.e. tx with a non-null parent_consensus_timestamp which are not in a batch), we determine that the parent is the tx with a nonce of 0, and from that we assume that all other transactions are children.
This is wrong since there might be unrelated transactions among this set, i.e. tx with a nonce > 0 and parent_consensus_timestamp === null.
An example of that can be obtained with this query to MN:
https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.4419734-1722372182-141436565
The first tx returned as a nonce of 1 and a null parent_consensus_timestamp. It is hence not a child of the transaction of nonce 0.
**Before the fix:**
**With the fix:** …

fix: interpretation of parent/child relationship between transactions

---

src/utils/EntityID.ts

Do not encode shard/realm in EntityID.toAddress(). 
The resulting EVM address will always have the first 12 bytes set to 0.
Fixes #2004

fix: don't encode shard and realm in EVM address

---

package-lock.json
package.json

Changes below move `vite` to release 7.0.0 (and `@vitejs/plugin-basic-ssl` to 2.1.0 for compatibility reason)
**Checklist**

chore: bump vite from 6.3.5 to 7.0.0

---

package-lock.json
package.json
tests/unit/account/Accounts.spec.ts
tests/unit/account/HbarAllowanceTable.spec.ts
tests/unit/account/NftAllSerialsAllowanceTable.spec.ts
tests/unit/account/NftAllowanceTable.spec.ts
tests/unit/account/TokenAllowanceTable.spec.ts
tests/unit/account/TokensSection.spec.ts
tests/unit/block/BlockDetails.spec.ts
tests/unit/block/Blocks.spec.ts
tests/unit/contract/ContractDetails.spec.ts
tests/unit/contract/Contracts.spec.ts
tests/unit/node/NodeTable.spec.ts
tests/unit/node/Nodes.spec.ts
tests/unit/token/TokenDetails.spec.ts
tests/unit/token/Tokens.spec.ts
tests/unit/topic/TopicDetails.spec.ts
tests/unit/topic/Topics.spec.ts
tests/unit/transaction/TransactionByIdTable.spec.ts
tests/unit/transaction/Transactions.spec.ts

Bump Oruga and adjust unit tests accordingly (comparison with static strings for table column headers)

chore: bump @oruga-ui/oruga-next from 0.11.2 to 0.11.4

---

eslint.config.mjs
src/pages/ContractDetails_Summary.vue
src/pages/Nodes_Network.vue
src/utils/analyzer/ContractAnalyzer.ts
tests/e2e/specs/AccountNavigation.cy.ts
tests/e2e/specs/BlockNavigation.cy.ts
tests/e2e/specs/ContractNavigation.cy.ts
tests/e2e/specs/NodeNavigation.cy.ts
tests/e2e/specs/TokenNavigation.cy.ts
tests/e2e/specs/TopNavigationBar.cy.ts
tests/e2e/specs/TopicNavigation.cy.ts
tests/e2e/specs/TransactionNavigation.cy.ts
tests/e2e/specs/TransferGraphs.cy.ts

Re-activate "_unsafe-to-chain-command_" checks in `eslint.config.mjs` and refactor e2e tests to suppress related errors.

chore: fix "unsafe-to-chain-command" lint errors in e2e tests.

---

src/utils/TransactionTools.ts
tests/unit/transfer_graphs/layout/HbarTransferLayout.spec.ts

Changes below fix a display issue in `Hbar Transfers` section.
Without these changes, `Hbar Transfers` for [this transaction](https://hashscan.io/mainnet/transaction/1677120502.107531752) are displayed like this:
Destination 0.0.800 (with 0 hbar) should not be displayed.
With the changes, `Hbar Transfers` is now correctly displayed:
**Checklist**

fix: removed useless 0.0.800 branch in hbar transfer graph

---

eslint.config.mjs

Changes below separate configuration `src/` and `tests/` sources in `eslint.config.mjs`.
For `src/` sources, the following checks are enabled (aligned on setup of Static Code analysis GH action):
- `complexity: ["error", 8]`
- `max-lines-per-function: ["error", 50]`
For `tests/` sources,  the following checks are disabled:
- `max-lines-per-function`
- `@typescript-eslint/no-explicit-any`
**Checklist**

chore: separate config for src/ and tests/ in eslint.config.mjs

---

src/components/AxiosStatus.vue
src/components/allowances/HbarAllowanceTable.vue
src/components/allowances/NftAllSerialsAllowanceTable.vue
src/components/allowances/NftAllowanceTable.vue
src/components/allowances/TokenAllowanceTable.vue
src/components/page/header/wallet/WalletStatusButton.vue
src/components/token/NftFile.vue
src/components/transaction/NftTransactionSummary.vue
src/components/transaction/TransactionSummary.vue
src/components/values/FunctionError.vue
src/components/values/FunctionInput.vue
src/components/values/FunctionResult.vue
src/components/values/TimestampValue.vue
src/dialogs/abi/ContractAbiEntry.vue
src/dialogs/core/ModalDialog.vue
src/dialogs/verification/FileList.vue
src/styles/explorer.css
tests/unit/token/NftFile.spec.ts

- Replace remaining fontawesome icons.
- Fontawesome icons used indirectly (i.e. those included by the Oruga components we use) are still there.

chore: replace fontawesome icons by lucide icons

---

_frontend/package-lock.json
_frontend/package.json
_frontend/src/utils/cache/HCSAsset.ts

This bumps typescript from 5.8.3 to 5.9.2 and fixes the induced build error in `HCSAsset.ts` (which caused the related dependabot PR to fail).

chore: bump typescript from 5.8.3 to 5.9.2

---

_frontend/src/components/node/NodeTable.vue
_frontend/src/components/node/StakeRange.vue
_frontend/tests/unit/node/NodeTable.spec.ts
_frontend/tests/unit/node/Nodes.spec.ts

Display account ID in node table unconditionally (it was present only when staking was not activated).
Make table more dense and staking diagram more compact.
Display staking weight % in the tooltip of STAKE FOR CONSENSUS.

fix: display node account ID in node table

---

_frontend/src/utils/bytecode_tools/disassembler/utils/evm_opcodes.ts

Update Opcodes definitions to align with _Cancun_ EVM Opcodes specification: https://www.evm.codes/?fork=cancun
Fixes #2224
This contract for instance has an opcode (**5e**) which was considered invalid previously:
https://hashscan.io/mainnet/contract/0.0.9968249/bytecode

fix: update cancun opcode definition
