- src/App.vue
- src/assets/styles/explorer.scss
- src/pages/AccountDetails.vue
- src/pages/ContractDetails.vue
- src/pages/TransactionDetails.vue
This PR addresses some of the layout issues on mobile.
Related to #35
**Checklist**
> 00035 improve mobile

- src/pages/AccountDetails.vue
Signed-off-by: Simon Viénot <simon.vienot@icloud.com>
This PR is a pretty trivial, single file, improvement which applies the exact same template and logic used for the type selector already present on the Transactions page.
As opposed to my original plan, the type selector is initially empty (i.e. 'ALL TRANSACTIONS') when landing on the page, to be consistent with the previous behavior (and not break the tests...). 
We'll see whether we get feedback and want to change this. 
Fixes #44
You may squash and get rid of the branch.
**Checklist**
> Added transaction type selector to AccountDetails page

- tests/e2e/specs/TransactionNavigation.spec.ts
Signed-off-by: Simon Viénot <simon.vienot@icloud.com>
PR title says it all!
Related to #46
**Checklist**
> Add E2E test for ETHEREUMTRANSACTION type.

- src/App.vue
- src/components/TopNavBar.vue
- src/components/dashboard/DashboardItem.vue
- src/components/dashboard/HbarMarketDashboard.vue
- src/schemas/HederaSchemas.ts
- tests/unit/App.spec.ts
- tests/unit/Mocks.ts
- tests/unit/dashboard/HbarMarketDashboard.spec.ts
- tests/unit/dashboard/MainDashboard.spec.ts
This PR brings the following changes:
* add the Hbar released supply and total supply to the HbarMarketDashboard. These are obtained from the recent /api/v1/network/supply REST API.
* remove remaining code related to the display fallback on mobile screens.
Fixes #13
PR may be squashed and branch deleted.
**Checklist**
> 00013 Display network's released and total supply of hbars

- .env
Reset VUE_APP_ENABLE_STAKING=false
> Reset VUE_APP_ENABLE_STAKING=false

- package-lock.json
- package.json
- src/components/staking/WalletChooser.vue
- src/pages/Staking.vue
- src/utils/wallet/WalletDriver.ts
- src/utils/wallet/WalletDriver_Blade.ts
- src/utils/wallet/WalletDriver_Hashpack.ts
- src/utils/wallet/WalletManager.ts
- tests/unit/staking/Staking.spec.ts
- tests/unit/staking/WalletDriver_Mock.ts
The changes below add Staking.spec.ts.
This unit test verifies that Staking page correctly executes the following sequence:
1) Connect Wallet
2) Stake to Account
3) Stake to Node
4) Accept Reward
5) Stop Staking
6) Disconnect Wallet
Fixes #129 
Can be squash-merged. Branch can be deleted.
**Checklist**
> Unit testing for Staking page (#00129)

- src/components/account/AccountLoader.ts
- src/components/block/BlockLoader.ts
- src/components/block/BlockTransactionsLoader.ts
- src/components/contract/ContractLoader.ts
- src/components/contract/ContractResultDetailsLoader.ts
- src/components/node/NodeLoader.ts
- src/components/staking/StakeLoader.ts
- src/components/token/TokenInfoLoader.ts
- src/pages/AccountDetails.vue
- src/pages/BlockDetails.vue
- src/pages/ContractDetails.vue
- src/pages/ContractResultDetails.vue
- src/pages/NodeDetails.vue
- src/pages/Staking.vue
- src/pages/TokenDetails.vue
- src/router.ts
- src/schemas/HederaSchemas.ts
- src/utils/EntityLoader.ts
- src/utils/PathParam.ts
- tests/e2e/specs/AccountNavigation.spec.ts
- tests/unit/staking/Staking.spec.ts
This PR includes two main set of changes:
- some work related to EIP 3091 support
- some refactoring using the EntityLoader abstract class
It also fixes #189 (as a benefit of EntityLoader re-use) and adds unit test for it.
Fixes #189
**Checklist**
> Support EIP 3091 and refactoring

- src/utils/EntityCacheV2.ts
The changes below fix issue #201.
#201
Fixes #
See #201 for steps to reproduce the issue and validate this fix.
**Checklist**
> 00201 Account details displays wrong list of recent transactions

- src/components/transaction/TransactionByIdTable.vue
- src/components/transfer_graphs/layout/TokenTransferLayout.ts
- src/schemas/HederaSchemas.ts
- tests/unit/Mocks.ts
- tests/unit/transaction/TransactionByIdTable.spec.ts
This PR adds a 'Nonce' column to the TransactionByIdTable and a unit test for this component.
Fixes #206
E.g. <url>/#/mainnet/transactionsById/0.0.1137450-1662474805-341772780
**Checklist**
> 00206 nonce in transaction by id table

- .env
- src/components/TopNavBar.vue
- src/pages/TransactionDetails.vue
Minor refactoring of systemContract as a computed.
Clean-up variables which should have been const.
Activate Blocks pages by default in .env
Fix small spacing issue in top menu bar.
**Checklist**
> Follow-up of 00215 system contract name

- src/components/staking/RewardsCalculator.vue
- src/pages/Staking.vue
Trivial wording changes in Staking and RewardsCalculator components.
Fixes #240
Visible on staging server.
**Checklist**
> Fix #240 - wording of Staking page

- .env
- src/components/transaction/ContractResultAndLogs.vue
- src/pages/TransactionDetails.vue
- tests/e2e/specs/BlockNavigation.spec.ts
- tests/e2e/specs/TransactionNavigation.spec.ts
Couple trivial cosmetic changes and additional E2E tests.
**Checklist**
> Misc fixes and tests

- src/schemas/OperatorRegistry.ts
Hardcoded node descriptions are off for several nodes. This aligns them on the list at: https://status.hedera.com
> Update node descriptions.

- src/pages/AccountDetails.vue
- src/pages/Tokens.vue
Fix regression caused by a missing '<' in template of Tokens component...
**Checklist**
> Fix regression in play/pause button on Tokens page

- src/schemas/OperatorRegistry.ts
Fix description of Node 8, per: http://status.hedera.com/
> Fix description of Node 8.

- src/assets/styles/explorer.scss
- src/components/token/FractionalFeeTable.vue
- src/components/token/RoyaltyFeeTable.vue
- src/components/token/TokenCustomFees.vue
- src/components/token/TokenInfoLoader.ts
- src/components/values/PlainAmount.vue
- src/components/values/TokenLink.vue
- src/pages/Staking.vue
- tests/unit/Mocks.ts
- tests/unit/node/NodeTable.spec.ts
- tests/unit/token/TokenDetails.spec.ts
- tests/unit/transaction/ContractResultAndLogs.spec.ts
- tests/unit/transaction/TransactionDetails.spec.ts
- tests/unit/values/TokenLink.spec.ts
This is a follow-up for PR #254 which improves the layout of the Custom Fees section in TokenDetails and adds unit tests.
There are also a few tweaks to get rid of unit test warnings (which I thought were gone, but that must be in another branch...)
Relates to #15 
**Checklist**
> Follow-up for: 00015 show custom token fees

- src/components/AxiosStatus.vue
- src/components/staking/RewardsCalculator.vue
- src/pages/NodeDetails.vue
- src/pages/Nodes.vue
- src/pages/Staking.vue
- src/pages/TokenDetails.vue
Trivial changes to avoid using v-bind when passing constant props to components.
None.
**Checklist**
> Remove bind for const props.

- src/pages/TokenDetails.vue
- tests/e2e/specs/TokenNavigation.spec.ts
Change below include a commit that should have been part of [PR262](https://github.com/hashgraph/hedera-mirror-node-explorer/pull/267) ... :/
They also add an extra test case to Token Details e2e navigation.
Fixes #62 
See [PR262](https://github.com/hashgraph/hedera-mirror-node-explorer/pull/267)
**Checklist**
> 00062 Add EIP 3091 Support (take #2)

- src/components/values/BlobValue.vue
Fixed problems with encoding of UTF8 chars in blob values
Opened in Slack channel (https://swirldslabs.slack.com/archives/C02F8HZBBCN/p1668734144786059), thanks Ken!
N/A
**Checklist**
> Fixed problems with encoding of UTF8 chars in blob values

- README.md
- package.json
- src/components/account/AccountLoader.ts
- src/pages/AccountDetails.vue
- src/pages/Staking.vue
- tests/unit/Mocks.ts
- tests/unit/account/AccountDetails.spec.ts
- tests/unit/staking/Staking.spec.ts
- tests/unit/staking/WalletDriver_Mock.ts
This PR applies a couple of very simple (but unrelated) changes:
- adjust docker target and README following recent DevOps changes
- move checksum and stakePeriodStart processing to AccountLoader
- add display of checksum to Staking view
- adjust mock of stakePeriodStart logic in unit tests
**Checklist**
> Miscellaneous fixes and refactoring

- src/components/values/FunctionInput.vue
- src/components/values/FunctionResult.vue
- src/components/values/FunctionValue.vue
All is in the title. This gets rid of related console warning.
> FunctionValue takes NameTypeValue as prop instead of unknown.

- src/components/node/NodeCursor.ts
- src/components/node/NodeRegistry.ts
- src/components/node/NodesLoader.ts
- src/components/staking/RewardsCalculator.vue
- src/components/staking/StakingDialog.vue
- src/pages/NodeDetails.vue
- src/pages/Nodes.vue
- src/pages/Staking.vue
- src/router.ts
- src/utils/RouteManager.ts
- tests/unit/Mocks.ts
- tests/unit/node/NodeDetails.spec.ts
- tests/unit/node/Nodes.spec.ts
- tests/unit/staking/RewardsCalculator.spec.ts
- tests/unit/staking/Staking.spec.ts
- tests/unit/transaction/TransactionByIdTable.spec.ts
With the following changes:
- a singleton NodeRegistry component is introduced to provides a NodesLoader shared across the product
- the logic related to axios initialization and network switching is centralized in RouteManager.
There is no issue associated to this refactoring, which is a pre-requisite to fixing #370, and done in a separate PR for the sake of clarity.
**Checklist**
> Use singleton node registry

- src/pages/NodeDetails.vue
Changes below improved url param check in NodeDetails page.
Fixes #392
See #392 for test url.
> 00392 (nodeId check).

- src/pages/AccountDetails.vue
- src/pages/BlockDetails.vue
- src/pages/NodeDetails.vue
- src/pages/TokenDetails.vue
- src/pages/TransactionDetails.vue
- tests/e2e/specs/SearchBar.spec.ts
Miscellaneous changes which do not change the logic:
- additional 2e2 tests for search bar
- typo in account details
- code formatting
None
**Checklist**
> Misc fixes

- package-lock.json
- package.json
- src/utils/NameService.ts
- src/utils/RouteManager.ts
- src/utils/SearchRequest.ts
Signed-off-by: Ryan Leckey <ryan@launchbadge.com>
This PR allows looking up accounts by their domain registered on KNS via https://kabuto.sh.
> feat: resolve accounts via kabuto name service (kns)

- src/utils/ComplexKeyLine.ts
- tests/unit/utils/ComplexKeyLine.spec.ts
Changes below include fix and unit test for issue #423.
Fixes #423
Use account 0.0.49058639 (on testnet) to see issue and fix effect.
**Checklist**
> 00423 some protobuf-encoded keys are incorrectly displayed

- tests/e2e/specs/TransactionNavigation.spec.ts
All is in title. Test-only change.
None.
> Fix TransactionNavigation e2e test.

- README.md
Update README to mention Node.js 16 prerequisite.
None.
> Update README to require Node 16.

- src/components/contract/ContractResultDetailsLoader.ts
Trivial 1-line fix to use correct error string selector value for contract result
Relates to  #434
Sorry for the noise...
**Checklist**
> Follow-up to PR #462

- src/components/transfer_graphs/TokenTransferGraphC.vue
- src/components/values/TokenAmount.vue
- src/components/values/TokenExtra.vue
- tests/unit/block/BlockDetails.spec.ts
- tests/unit/dashboard/MainDashboard.spec.ts
- tests/unit/transaction/Transactions.spec.ts
- tests/unit/transfer_graphs/TokenTransferGraphC.spec.ts
This simple PR adds the token extra information (symbol or name) next to the amount in compact transfer graphs.
Fixes #457
Currently deploying on staging server.
**Checklist**
> 00457 token symbol in transfer graph

- package-lock.json
- package.json
- src/utils/wallet/WalletDriver_Blade.ts
- tests/e2e/specs/SearchBar.spec.ts
Changes below moves `blade-web3` component from `0.9.11` to `0.9.14`.
They also fix `SearchBar.spec.ts` e2e test (0.0.1753997 public key has changed recently)
> Moving to blade 0 9 14

- src/components/allowances/ApproveAllowanceDialog.vue
- src/components/allowances/ApproveAllowanceSection.vue
- src/components/allowances/HbarAllowanceTable.vue
- src/components/allowances/HbarAllowanceTableController.ts
- src/components/allowances/TokenAllowanceTable.vue
- src/components/allowances/TokenAllowanceTableController.ts
- src/components/values/AccountLink.vue
- src/pages/AccountDetails.vue
- src/utils/table/TableController.ts
- tests/unit/values/AccountLink.spec.ts
This is a follow-up to PR #504 for enhancement #499 (support for approving allowances) which essentially brings:
- support for editing existing allowances
- improved input validation in the ApproveAllowanceDialog.
#499
Actions for approving/editing allowances are still disabled in production.
**Checklist**
> 00499 approve allowances

- src/components/TopNavBar.vue
- src/pages/AddressDetails.vue
- src/utils/RouteManager.ts
- tests/e2e/specs/ContractNavigation.spec.ts
- tests/unit/contract/ContractDetails.spec.ts
These changes make sure routes to main pages include a 'network' param.
Also includes unrelated fixes to one unit test and one e2e test.
None
**Checklist**
> Suppress router-link warnings

- src/components/TopNavBar.vue
- tests/e2e/specs/MobileMenu.spec.ts
- tests/e2e/specs/MobileSearch.spec.ts
Add e2e tests for areas specific to small screen (mobile menu and mobile search pages).
**Checklist**
> Mobile menu e2e tests

- package-lock.json
- package.json
- src/App.vue
- src/components/Footer.vue
- vue.config.js
This PR shows build release in the footer, as specified in [this comment](https://github.com/hashgraph/hedera-mirror-node-explorer/pull/171#issuecomment-1553432264).
Fixes #137 #585 
This PR replaces #171 
**Checklist**
> Show build release

- package-lock.json
- package.json
> Upgrade @fortawesome/* dependencies to 6.3.0

- src/components/account/AccountTable.vue
- src/components/account/BalanceTable.vue
- src/components/block/BlockTable.vue
- src/components/block/BlockTransactionTable.vue
- src/components/contract/ContractResultTable.vue
- src/components/contract/ContractTable.vue
- src/components/contract/ContractTransactionTable.vue
- src/components/dashboard/ContractCallTransactionTable.vue
- src/components/dashboard/CryptoTransactionTable.vue
- src/components/dashboard/MessageTransactionTable.vue
- src/components/node/NodeTable.vue
- src/components/staking/StakingRewardsTable.vue
- src/components/token/TokenBalanceTable.vue
- src/components/token/TokenTable.vue
- src/components/topic/TopicTable.vue
- src/components/transaction/TransactionByIdTable.vue
- src/components/transaction/TransactionTable.vue
- src/utils/RouteManager.ts
- tests/e2e/specs/NodeNavigation.cy.ts
With these changes, navigation from all tables, by doing a Cmd-Click or a Ctrl-Click on a row, will open a new tab.
Related to #447 
Currently deploying on staging server.
> 00447 navigate from table to new tab

- package-lock.json
- package.json
Upgrading @hashgraph/sdk component to latest release.
> Moving @hashgraph/sdk from 2.18.0 to 2.27.0.

- .github/workflows/comp-compile-explorer-code.yaml
Update node version in GH workflow.
> Bump node version to 20.

- package-lock.json
- package.json
Changes below move vitest from v0.34.3 to v0.34.5.
> Bump vitest to v0.34.5.

- tests/unit/utils/SearchRequest.spec.ts
one-line change to remove test workaround for Kabuto search returning 503 instead of 404.
> Remove test workaround for kabuto bug.

- src/components/transaction/TransactionAnalyzer.ts
- src/components/values/TransactionLabel.vue
- src/pages/TransactionDetails.vue
- src/schemas/HederaSchemas.ts
- src/utils/TransactionTools.ts
- src/utils/parser/TransactionLocParser.ts
- tests/unit/Mocks.ts
- tests/unit/transaction/TransactionDetails.spec.ts
Consider the following transaction results as successful:
- FEE_SCHEDULE_FILE_PART_UPLOADED
- SUCCESS_BUT_MISSING_EXPECTED_OPERATION
In such cases, add the `Result` property to make the information available (in case of failure, the result is shown in red banner).
Fixes #690
**Checklist**
> 00690 tx returning FEE_SCHEDULE_FILE_PART_UPLOADED is marked as failed

- package-lock.json
- package.json
Changes below update package dependencies as suggested by `npm update --save`.
> Updated package dependencies using npm update.

- src/components/values/BlockLink.vue
- src/pages/TransactionDetails.vue
- tests/unit/Mocks.ts
- tests/unit/transaction/TransactionDetails.spec.ts
Makes sure block number is displayed when ==0 in TransactionDetails.
Fixes #714
**Checklist**
> 00714 block number zero not displayed

- public/networks-config.json
- src/components/contract/ContractByteCodeSection.vue
- src/schemas/NetworkRegistry.ts
Point to contract verification staging server in default network-config.json, and remove static init of sourcify setup.
PR #717 needs to be merged before this one.
> Point to verification staging

- .env
- public/networks-config.json
- src/components/contract/ContractByteCodeSection.vue
- src/schemas/NetworkRegistry.ts
- src/utils/cache/SourcifyCache.ts
- tests/unit/contract/ContractDetails.spec.ts
Add an `activate` field inside `sourcifySetup` for each network as a feature flag for contract verification.
This replaces the `VITE_APP_ENABLE_VERIFICATION` environment variable used previously.
> Put feature flag for contract verification in networks-config.json

- package-lock.json
- package.json
Changes below update package.json and package-lock.json with `npm update --save` output.
_None_
**Checklist**
> Updated dependencies using "npm update --save"

- package-lock.json
- package.json
- src/utils/AxiosMonitor.ts
- src/utils/table/TableController.ts
Changes below upgrade axios release from 0.27.2 to 1.6.0.
**Checklist**
> Moved axios from 0.27.2 to 1.6.0.

- src/components/contract/ContractByteCodeSection.vue
Verify button does not show up on contracts not verified.
> fix: resolve issue with verify button now showing up

- src/components/values/BlobValue.vue
Make JSON contents in BlobValue wrap.
Fixes #745
> fix: #745 HCS text overflow

- package-lock.json
- package.json
Upgraded `@metamask/providers` from release 13.0.1 to 14.0.2.
_None_
**Checklist**
> Upgraded @metamask/providers from release 13.0.1 to 14.0.2.

- package-lock.json
- package.json
Changes below update package dependencies using npm update --save command.
**Checklist**
> chore: updated package dependencies using npm update --save.

- src/components/contract/ContractResultLogEntry.vue
- tests/unit/contract/ContractResultLogEntry.spec.ts
Everything is in the title.
Fixes #808 
**Checklist**
> feat: show block as hlink in events section

- package-lock.json
- package.json
Changes below update package dependencies.
**Checklist**
> chore: update package dependencies using npm update --save.

- sourcify-setup/.env
- sourcify-setup/docker-compose.yaml
- src/pages/AccountBalances.vue
- tests/e2e/specs/AccountNavigation.cy.ts
- Align sourcify setup to latest path configuration changes
- Change one section title in AccountBalances
> chore: adjust sourcify setup for testing

- src/components/contract/ContractTable.vue
- src/components/values/ContractName.vue
- tests/unit/contract/Contracts.spec.ts
Add new column (`Contract Name`) in `Recent Contract` table. Displays contract name when contract is verified.
Fixes #871 
Deployed on staging.
> feat: display contract names in Recent Contracts section

- package-lock.json
- package.json
- tests/e2e/specs/SearchBar.cy.ts
Changes below migrate KNS api to 0.13.2.
They also add a e2e test case to `SearchBar.cy.ts` to validate KNS integration.
**Checklist**
> chore: migrating @kabuto-sh/ns release to 0.13.2

- src/components/DashboardCard.vue
- src/components/values/ByteCodeValue.vue
- src/pages/Transactions.vue
- Take into account '0x' values meaning null (in EVM related REST API) in ByteCodeValue
- Fix spacing of control slot when DashboardCard is not collapsible
- Display 15 transactions in main Transactions page (aligns on other main pages)
**Checklist**
> fix: miscellaneous cosmetic fixes

- src/components/values/FunctionValue.vue
- src/schemas/HederaUtils.ts
- src/utils/analyzer/ContractAnalyzer.ts
- src/utils/analyzer/ContractLogAnalyzer.ts
- src/utils/analyzer/FunctionCallAnalyzer.ts
- tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts
This PR improved the explanation for response codes returned from system contracts.
Fixes #903 
**Checklist**
> fix: improved explanation for the response codes returned from system contracts (#903)

- src/components/account/AccountVerifiedContractsTable.vue
One-line fix. 
Deployed on staging right now.
> fix: navigation from AccountVerifiedContractsTable to ContractDetails is broken

- src/AppStorage.ts
- src/components/Tabs.vue
- src/pages/AccountDetails.vue
- tests/e2e/specs/AccountNavigation.cy.ts
- tests/unit/Tabs.spec.ts
- tests/unit/values/InlineBalancesValue.spec.ts
Simple changes to identify tabs by a string instead of their index, and guard against wrong value obtained from user prefs.
**Checklist**
> chore: improve Tabs component

- package-lock.json
- package.json
> chore: add component @vuepic/vue-datepicker.

- package-lock.json
- package.json
- src/utils/RouteManager.ts
- src/utils/SearchRequest.ts
- src/utils/name_service/HNS.ts
Changes below add HNS support.
When user types a name in search bar, Explorer now tries to resolve it using both KNS and HNS.
Fixes #748 
Explorer resolves "example.hbar" as account 0.0.3856455.
This matches the result obtained using https://app.hashgraph.name.
**Checklist**
> feat: add HNS support

- src/components/staking/StakingRewardsTableController.ts
- src/components/transaction/TransactionFilterSelect.vue
- src/components/transaction/TransactionTable.vue
- src/components/transaction/TransactionTableController.ts
- src/components/transaction/TransactionTableControllerXL.ts
- src/components/transaction/TransactionTablePageSize.vue
- src/pages/AccountDetails.vue
- src/pages/Transactions.vue
- src/utils/table/TableController.ts
- tests/e2e/specs/TransactionNavigation.cy.ts
Allows account transaction row length to be alterable
#908 
Fixes #
Adds row count modifier
**Checklist**
> 00908 transaction page size selector

- src/AppStorage.ts
- src/components/contract/ContractByteCodeSection.vue
- src/components/dialog/Dialog.vue
- src/components/dialog/DialogButton.vue
- src/components/values/abi/ContractAbiDialog.vue
- src/components/values/abi/ContractAbiEntry.vue
- src/components/values/abi/ContractAbiValue.vue
- src/components/values/abi/ContractCallBuilder.ts
- src/components/values/abi/JsonEditorDialog.vue
- src/components/values/abi/ParamBooleanEditor.vue
- src/components/values/abi/ParamJsonEditor.vue
- src/components/values/abi/ParamTextEditor.vue
- src/components/values/abi/ParamTypeEditor.vue
- src/schemas/HederaSchemas.ts
- src/utils/analyzer/ContractResultAnalyzer.ts
- src/utils/analyzer/FunctionCallAnalyzer.ts
- src/utils/wallet/WalletDriver.ts
- src/utils/wallet/WalletDriver_Ethereum.ts
- src/utils/wallet/WalletDriver_Hedera.ts
- src/utils/wallet/WalletManager.ts
- tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
Changes below add `ABI` tab to `Contract Detail` page.
This tab is visible when contract is verified and enables to:
- display functions, events and errors composing the ABI of the contract
- run interactively functions of the contract using wallet connection
Fixes #782
Use the following contract to make some basic experiments on the staging server: 
{staging-url}/testnet/contract/0.0.3580227
**Checklist**
> feat: added ABI tab to Contract Details page

- src/components/dialog/Dialog.vue
- src/components/download/DownloadDialog.vue
- src/components/download/TransactionDownloadDialog.vue
- src/components/transaction/TransactionFilterSelect.vue
- src/components/values/InlineBalancesValue.vue
- src/pages/AccountDetails.vue
- src/pages/NftDetails.vue
- src/pages/Transactions.vue
- src/schemas/HederaSchemas.ts
- src/schemas/HederaUtils.ts
- src/utils/downloader/AbstractTransationDownloader.ts
- src/utils/downloader/EntityDownloader.ts
- src/utils/downloader/HBarTransferDownloader.ts
- src/utils/downloader/NFTTransferDownloader.ts
- src/utils/downloader/RewardDownloader.ts
- src/utils/downloader/TokenTransferDownloader.ts
- src/utils/downloader/TransactionDownloader.ts
- tests/unit/utils/downloader/TransactionDownloader.spec.ts
Add download action on the `Transactions` tab of AccountDetails view. Allows to filter transaction by:
- HBAR transfers
- Token transfers (all or by Id)
- NFT transfers (all or by Id)
- transaction type
Fixes #32 
> feat: export account transactions as CSV

- src/components/contract/ContractByteCodeSection.vue
ABI download is no longer experimental (limited to previewnet)
> chore: enable ABI download to mainnet/testnet

- package-lock.json
- package.json
- src/components/allowances/ApproveAllowanceSection.vue
Changes below upgrade `@kabuto/ns` release from 0.13.2 to 0.14.2.
They also fix `ApproveAllowanceSection` vue: `editHbarAllowance()` and `editTokenAllowance()` now check `WalletManager.isHederaWallet()` to produce a better user feedback.
**Checklist**
> chore: upgrading @kanuto/ns to 0.14.2

- ANALYTICS.md
- src/App.vue
- src/components/SearchBar.vue
- src/components/TopNavBar.vue
- src/components/token/TokenActions.vue
- src/components/values/abi/ContractAbiDialog.vue
- src/components/verification/ContractVerificationDialog.vue
- src/gtag.ts
- src/pages/Staking.vue
- src/router.ts
Changes below enable Google Analytics custom events.
See `ANALYTICS.md` for details.
> chore: adding GA custom events

- src/AppStorage.ts
- src/components/AlertDialog.vue
- src/components/DateTimePicker.vue
- src/components/MirrorLink.vue
- src/components/account/AccountCreatedContractsTable.vue
- src/components/account/CollectionTable.vue
- src/components/account/VerifiedContractsTable.vue
- src/components/contract/ContractByteCodeSection.vue
- src/components/contract/ContractResultLogEntry.vue
- src/components/download/DownloadDialog.vue
- src/components/staking/StakingRewardsTableController.ts
- src/components/transaction/NftTransactionTable.vue
- src/components/transaction/TransactionTableController.ts
- src/components/values/DisassembledCodeValue.vue
- src/components/values/abi/ContractCallBuilder.ts
- src/utils/SearchRequest.ts
- src/utils/analyzer/ContractAnalyzer.ts
- src/utils/analyzer/FunctionCallAnalyzer.ts
- src/utils/bytecode_tools/disassembler/utils/helpers.ts
- src/utils/cache/NftCollectionCache.ts
- src/utils/cache/TokenAssociationCache.ts
- src/utils/wallet/WalletDriver_Coinbase.ts
- src/utils/wallet/WalletDriver_Ethereum.ts
- src/utils/wallet/WalletDriver_Hedera.ts
- tests/unit/utils/analyzer/ContractLogAnalyzer.spec.ts
- tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
Changes below fix some warnings reported by `eslint`.
**Checklist**
> chore: fixed some warnings reported by eslint

- tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
Changes below remove some debug traces in unit test for `ContractResultAnalyzer` class.
**Checklist**
> chore: remove debug traces

- package.json
- src/components/DashboardCard.vue
- src/components/values/BlobValue.vue
- src/components/values/link/EntityIOL.vue
- src/pages/NftDetails.vue
- src/schemas/HederaSchemas.ts
A few unrelated small refactoring or cosmetic changes, with no impact on the functionality, except for those 2 items:
- use Cloudflare public IPFS gateway instead of ipfs.io (usually responds more reliably)
- add `Show raw data` link in NftDetails view
Should not have any impact on tests.
> chore: Miscellaneous refactoring/cosmetic changes

- src/pages/TopicDetails.vue
- src/utils/name_service/NameService.ts
Changes below removed some unused imports. No semantic changes.
**Checklist**
> chore: removed some unused import in vues

- tests/unit/transaction/TransactionDetails.spec.ts
Changes below fix some mocks in `TransactionDetails` unit tests.
**Checklist**
> chore: fixed some mocks in TransactionDetails unit tests.

- .env
- src/components/values/BlobValue.vue
- tests/unit/values/BlobValue.spec.ts
* Refactor BlobValue component: Remove prop `limitingFactor` and add prop `noAnchor`.
* Configure IPFS Gateway with .env variable
* Use _Pinata_ public IPFS gateway by default
**Checklist**
> chore: Refactor BlobValue.

- src/pages/AccountCollection.vue
Trivial (everything is in the title).
> chore: Remove unused components from AccountCollection

- src/components/InfoTooltip.vue
- tests/unit/infoTooltip.spec.ts
Allow InfoTooltip to display either info or warning message.
**Checklist**
> chore:  improve InfoTooltip

- src/assets/hedera-hashgraph-hbar.svg
- src/components/MediaContent.vue
- src/components/token/NftFile.vue
- src/components/token/NftPreview.vue
- tests/unit/token/NftFile.spec.ts
- tests/unit/token/NftPreview.spec.ts
These components are for further use.
Note that MediaContent is currently indirectly covered by units tests for the other 2 (derived) components.
**Checklist**
> chore: Add MediaContent, NftPreview and NftFile components

- src/components/InfoTooltip.vue
- tests/unit/Mocks.ts
- tests/unit/token/NftFile.spec.ts
- tests/unit/token/NftPreview.spec.ts
- trivial fix in unit test using Oruga component 
- silence debug trace.
> chore: Fix unit tests.

- src/utils/name_service/provider/AllProviders.ts
All in the title. Trivial one line change.
> chore: change order of name resolution results

- src/AppStorage.ts
- src/components/allowances/ApproveAllowanceDialog.vue
- src/components/allowances/DeleteNftAllowanceDialog.vue
- src/components/staking/ProgressDialog.vue
- src/components/transaction/NftTransactionAnalyzer.ts
- src/components/transaction/TransactionAnalyzer.ts
- src/components/values/TransactionId.vue
- src/components/values/TransactionIdValue.vue
- src/components/values/TransactionLabel.vue
- src/components/values/TransactionLink.vue
- src/pages/Staking.vue
- src/pages/TransactionDetails.vue
- src/pages/TransactionsById.vue
- src/utils/TransactionID.ts
- src/utils/wallet/WalletDriver_Hedera.ts
- tests/e2e/TestUtils.ts
- tests/e2e/specs/AccountNavigation.cy.ts
- tests/e2e/specs/ContractResultDetails.cy.ts
- tests/e2e/specs/MobileSearch.cy.ts
- tests/e2e/specs/SearchBar.cy.ts
- tests/e2e/specs/TransactionNavigation.cy.ts
- tests/unit/account/AccountDetails.spec.ts
- tests/unit/contract/ContractDetails.spec.ts
- tests/unit/token/TokenDetails.spec.ts
- tests/unit/transaction/TransactionDetails.spec.ts
- tests/unit/utils/TransactionID.spec.ts
- tests/unit/values/TransactionIdValue.spec.ts
Add pull-down menu to select format of ID in TransactionDetails.
Fixes #1128 
**Checklist**
> feat: selector of transaction ID format

- src/components/account/AccountTableController.ts
- src/components/account/CollectionTableController.ts
- src/components/account/TokenRelationshipsTableController.ts
- src/components/block/BlockTableController.ts
- src/components/contract/ContractResultTableController.ts
- src/components/contract/ContractTableController.ts
- src/components/token/NftHolderTableController.ts
- src/components/token/TokenBalanceTableController.ts
- src/components/token/TokenTableController.ts
- src/components/topic/TopicMessageTableController.ts
- src/components/transaction/NftTransactionTableController.ts
- src/components/transaction/TransactionTableController.ts
- src/components/transaction/TransactionTableControllerXL.ts
- src/utils/table/TableController.ts
Update  refresh configuration for TableControllers:
- those needing a fast refresh rate (transactions, topic messages and blocks)
- those needing a slow refresh (rest of the world)
Fixes #981
> feat: extend time for play button

- src/components/account/AccountCreatedContractsTable.vue
- src/components/account/AccountTable.vue
- src/components/account/BalanceTable.vue
- src/components/account/CollectionTable.vue
- src/components/account/NftsTable.vue
- src/components/account/VerifiedContractsTable.vue
- src/components/block/BlockTable.vue
- src/components/block/BlockTransactionTable.vue
- src/components/contract/ContractResultTable.vue
- src/components/contract/ContractTable.vue
- src/components/contract/ContractTransactionTable.vue
- src/components/dashboard/ContractCallTransactionTable.vue
- src/components/dashboard/CryptoTransactionTable.vue
- src/components/dashboard/MessageTransactionTable.vue
- src/components/node/NodeTable.vue
- src/components/staking/StakingRewardsTable.vue
- src/components/token/NftHolderTable.vue
- src/components/token/TokenBalanceTable.vue
- src/components/token/TokenTable.vue
- src/components/topic/TopicTable.vue
- src/components/transaction/NftTransactionTable.vue
- src/components/transaction/TransactionByIdTable.vue
- src/components/transaction/TransactionTable.vue
In addition to Ctrl-click, detect wheel-click (middle button click) in tables on windows to navigate to a new tab.
Fixes #982
> fix: use wheel-click (on windows) to navigate to a new tab.

- src/components/account/AccountCreatedContractsTable.vue
- src/components/account/AccountTable.vue
- src/components/account/BalanceTable.vue
- src/components/account/CollectionTable.vue
- src/components/account/NftsTable.vue
- src/components/account/VerifiedContractsTable.vue
- src/components/block/BlockTable.vue
- src/components/block/BlockTransactionTable.vue
- src/components/contract/ContractResultTable.vue
- src/components/contract/ContractTable.vue
- src/components/contract/ContractTransactionTable.vue
- src/components/dashboard/ContractCallTransactionTable.vue
- src/components/dashboard/CryptoTransactionTable.vue
- src/components/dashboard/MessageTransactionTable.vue
- src/components/node/NodeTable.vue
- src/components/staking/StakingRewardsTable.vue
- src/components/token/NftHolderTable.vue
- src/components/token/TokenBalanceTable.vue
- src/components/token/TokenTable.vue
- src/components/topic/TopicMessageTable.vue
- src/components/topic/TopicTable.vue
- src/components/transaction/NftTransactionTable.vue
- src/components/transaction/TransactionByIdTable.vue
- src/components/transaction/TransactionTable.vue
- src/pages/TokenDetails.vue
- src/utils/RouteManager.ts
> chore: pass MouseEvent instead of boolean to RouteManager.routeToXXX() methods.

- src/utils/table/TableController.ts
Add `getNonStrictOperator()` for further use.
Adjust return type of `invertSortOrder()`, `invertKeyOperator()`
> chore: misc changes in TableController.

- src/AppStorage.ts
- src/components/account/BalanceTable.vue
- src/components/account/NftsTable.vue
- src/components/account/TokenRelationshipsTableController.ts
- src/components/staking/StakingRewardsTableController.ts
- src/components/token/TokensSection.vue
- src/components/transaction/TablePageSize.vue
- src/components/transaction/TransactionTableController.ts
- src/components/transaction/TransactionTableControllerXL.ts
- src/pages/AccountDetails.vue
- src/pages/Topics.vue
- src/utils/table/TableController.ts
- tests/unit/utils/TableController.spec.ts
Fixes inconsistencies in the use of local storage keys (for preferred page size of various tables).
Specify missing params (p, k) for TokenRelationshipsTableController.
Causes an unexplained regression in SearchBar e2e test...
> chore: refactor table controllers

- src/components/allowances/ApproveAllowanceDialog.vue
- src/components/token/TokenCell.vue
- src/components/token/TokenInfoAnalyzer.ts
- src/pages/Tokens.vue
- src/schemas/HederaSchemas.ts
- src/utils/analyzer/ContractAnalyzer.ts
Get rid of corresponding string constants in the code.
> chore: define and make use of TokenType enum.

- index.html
This one line change updates fontawesome key.
This will make icons visible again.
> chore: update fontawesome expired key

- src/assets/pause.svg
- src/assets/play.svg
- src/components/PlayPauseButton.vue
- tests/unit/App.spec.ts
Start getting rid of font awesome icons....
> chore: replace icons by SVGs in PlayPauseButton

- src/components/PlayPauseButton.vue
- tests/e2e/specs/TransactionNavigation.cy.ts
...follow-up to icon removal in PlayPauseButton.
> chore: fix TransactionNavigation e2e test

- src/components/Tabs.vue
Add 'compact' and 'subTabs' modes to the Tabs component (for further use by upcoming Search and Airdrops related features).
> chore: update Tabs component

- src/components/TopNavBar.vue
- src/pages/AccountDetails.vue
- tests/unit/account/AccountDetails.spec.ts
- tests/unit/account/AdminKeyDetails.spec.ts
- tests/unit/node/NodeDetails.spec.ts
- indicate "My Account" and display wallet logo
- navigate to account once wallet connected and when switching wallet accounts.
> feat: highlight my account once wallet connected.

- src/components/account/AccountTableController.ts
- src/components/transaction/TransactionTableControllerXL.ts
- src/components/values/InlineBalancesValue.vue
- src/pages/Staking.vue
Changes below:
- remove some dead code from `Staking` vue
- fix a couple of unused imports
**Checklist**
> chore: removed dead code from Staking vue

- src/components/search/SearchController.ts
- tests/unit/search/SearchController.spec.ts
> fix: trim whitespaces of search input text

- .env
- src/components/token/TokensSection.vue
Enable CLAIM action only when the following .env variable is set: 
` VITE_APP_ENABLE_CLAIM_ACTION=true
`
> chore: add feature flag for CLAIM action

- src/components/token/TokensSection.vue
Fixes 2 issues with CLAIM action:
- reset selected airdrops after 'CLAIM ALL' and 'CANCEL'
- do not display CLAIM button when current airdrop table is empty
> fix: CLAIM action

- .github/workflows/chart-release.yaml
Updating github actions to fully pinned commit sha.
Fixes #1456
**Checklist**
> ci: Updating github actions to fully pinned commit sha.

- chart/Chart.yaml
- chart/templates/cert-manager/certificate-requests.yaml
- chart/templates/cert-manager/cluster-issuer.yaml
- chart/values.yaml
Move certificate related template from solo-charts to hedera explorer own repo
Fixes #1465
> feat: move certificate template from solo-charts

- .github/workflows/chart-release.yaml
- chart/Chart.yaml
- chart/templates/cert-manager/certificate-requests.yaml
- chart/templates/cert-manager/cluster-issuer.yaml
- chart/templates/ingress.yaml
- chart/templates/ingress/ingress-class.yaml
- chart/values.yaml
- Fixed the helm release workflow to update dependencies before packaging the cart
- Fixed certificate issuer templates
Fixes #1470
> 01470 d update dependency

- .github/CODEOWNERS
Update per Q3 audit findings
Related to #1200 
**Checklist**
> ci: Update per Q3 audit findings

- src/components/TopNavBar.vue
Changes below migrate `TopNavBar` view to `<script setup>`.
**Checklist**
> chore: migrate TopNavBar view to <script setup>

- src/components/MediaContent.vue
1-line change to enable rendering of SVG in MediaContent component.
> fix: make sure SVG image is rendered in NFT preview.

- .env
- src/components/token/TokensSection.vue
- src/pages/AccountDetails.vue
> chore: remove VITE_APP_ENABLE_AIRDROP feature flag.

- src/components/TopNavBar.vue
- src/pages/MobileMenu.vue
- src/utils/RouteManager.ts
Change below simplify and move `RouteManger.selectedNetwork` `Ref` in `TopNavBar` and `MobileMenu`.
**Checklist**
> chore: moved RouteManager.selectedNetwork ref in TopNavBar and MobileMenu

- src/components/contract/ContractByteCodeSection.vue
Change below migrate `ContractByteCodeSection` view to `<script setup>` syntax.
**Checklist**
> chore: migrate ContractByteCodeSection view to <script setup>.

- .env
- index.html
- Update index.html
- Turn 'Claim Airdrops' OFF by default.
> chore: update index html

- src/config/ConfigUtils.ts
- tests/unit/contract/ContractDetails.spec.ts
- tests/unit/utils/analyzer/ABIAnalyzer.spec.ts
- tests/unit/utils/analyzer/ContractResultAnalyzer.spec.ts
- tests/unit/utils/analyzer/FunctionCallAnalyzer.spec.ts
This PR fixes `ConfigUtils.fetchURL()` method
**Checklist**
> fix: fixed ConfigUtils.fetchURL() routine

- src/components/dashboard/metrics/NetworkMetricsLoader.ts
- src/utils/wallet/WalletDriver_Blade.ts
- tests/unit/node/NodeTable.spec.ts
- tests/unit/staking/WalletDriver_Mock.ts
- tests/unit/transaction/TransactionByIdTable.spec.ts
- tests/unit/transfer_graphs/NftTransferGraph.spec.ts
- tests/unit/transfer_graphs/RewardTransferGraph.spec.ts
- tests/unit/transfer_graphs/TokenTransferGraphC.spec.ts
- tests/unit/transfer_graphs/TokenTransferGraphF.spec.ts
- tests/unit/transfer_graphs/layout/HbarTransferLayout.spec.ts
- tests/unit/transfer_graphs/layout/TokenTransferLayout.spec.ts
- tests/unit/utils/analyzer/ContractActionAnalyzer.spec.ts
- tests/unit/utils/analyzer/ContractLogAnalyzer.spec.ts
- tests/unit/utils/analyzer/TokenInfoAnalyzer.spec.ts
- tests/unit/utils/downloader/TransactionDownloader.spec.ts
- tests/unit/values/Endpoints.spec.ts
- Replace remaining imports of `HederaSchemas` by `MirrorNodeSchemas`
- `WalletDriver_Blade.makeHederaNetwork()` -> `makeHieroNetwork()`
- `HederaMetrics` -> `NetworksMetrics`
> chore: more renaming

- src/components/page/header/MobileMenuButton.vue
- src/components/page/header/NetworkSelector.vue
- src/components/page/header/PageHeader.vue
- src/components/search/SearchDropdown.vue
- src/utils/RouteManager.ts
- tests/e2e/specs/AccountNavigation.cy.ts
- tests/e2e/specs/AdminKeyDetailsNavigation.cy.ts
- tests/e2e/specs/BlockNavigation.cy.ts
- tests/e2e/specs/ContractNavigation.cy.ts
- tests/e2e/specs/CopyHexaToClipboard.cy.ts
- tests/e2e/specs/HomePage.cy.ts
- tests/e2e/specs/LegalNotices.cy.ts
- tests/e2e/specs/MobileMenu.cy.ts
- tests/e2e/specs/MobileSearch.cy.ts
- tests/e2e/specs/NodeNavigation.cy.ts
- tests/e2e/specs/SearchBar.cy.ts
- tests/e2e/specs/TokenNavigation.cy.ts
- tests/e2e/specs/TopNavigationBar.cy.ts
- tests/e2e/specs/TransactionNavigation.cy.ts
- tests/e2e/specs/TransferGraphs.cy.ts
Changes below re-enabled `e2e` tests after UI revamp.
**Checklist**
> chore: e2e test adaptation to new UI

- package-lock.json
- package.json
Changes below force elliptic package to release 6.6.1.
**Checklist**
> chore: force elliptic package to release 6.6.1

- public/testnet/erc-20.json
- public/testnet/erc-721.json
This PR updates ERC Registry with latest ERC-20 and ERC-721 tokens on Hedera testnet
> chore: update ERC Registry with latest ERC-20 and ERC-721 tokens on Hedera testnet

- public/mainnet/erc-20.json
- public/mainnet/erc-721.json
This PR updates ERC Registry with latest ERC-20 and ERC-721 tokens on Hedera mainnet
> chore: update ERC Registry with latest ERC-20 and ERC-721 tokens on Hedera mainnet

- public/mainnet/erc-1155.json
- public/testnet/erc-1155.json
Including initial version of these such that the automated process from smart-contracts repository can then keep them up-to-date.
> chore: add initial erc-1155.json registry files for mainnet and testnet.

- src/charts/core/RangeSelectView.vue
Change below renamed YTD chart range as 1Y.
**Checklist**
> fix:  YTD chart range should be rename 1Y 

- src/charts/core/ChartView.vue
- src/components/ArrowLink.vue
- src/components/DashboardCardV2.vue
- src/components/MirrorLink.vue
- src/components/NotificationBanner.vue
- src/components/contract/ContractResultStates.vue
- src/components/dashboard/MarketDashboardItem.vue
- src/components/node/NetworkDashboardItemV2.vue
- src/components/page/header/MainDashboardHeader.vue
- src/components/page/header/PageHeader.vue
- src/components/page/header/TabBar.vue
- src/components/page/header/wallet/WalletStatusButton.vue
- src/dialogs/core/task/TaskPanel.vue
- src/elements/ButtonView.vue
- src/elements/GroupBoxView.vue
- src/pages/Contracts.vue
- src/pages/MainDashboard.vue
- src/pages/PageNotFound.vue
- src/pages/SearchHelp.vue
- src/pages/Staking.vue
- src/styles/explorer.css
- Make sure all CSS font definitions use CSS variables.
- Light refactoring of SearchHelp layout and CSS.
No visual change.
> chore: miscellaneous CSS refactoring

- tests/e2e/specs/SearchBar.cy.ts
- fix SearchBar e2e tests
- re-enable skipped test for KNS name search
- add test for HNS name search
> chore: fix SearchBar e2e tests

- src/pages/AccountDetails.vue
- src/styles/explorer.css
Attempt to align labels on design.
Compact form:
Non-compact form:
> fix: aspect of domain labels.

- src/components/token/TokensSection.vue
- tests/e2e/specs/AccountNavigation.cy.ts
Update AccountNavigation e2e test and re-enable skipped tests.
> chore: update AccountNavigation e2e test.

- eslint.config.mjs
- src/App.vue
- src/charts/core/ChartController.ts
- src/charts/hgraph/TxOverTimeController.ts
- src/components/MirrorLink.vue
- src/components/account/CollectionTable.vue
- src/components/allowances/NftAllSerialsAllowanceTable.vue
- src/components/allowances/TokenAllowanceTable.vue
- src/components/block/BlockTransactionTable.vue
- src/components/contract/ContractResultStates.vue
- src/components/page/header/wallet/AccountSelector.vue
- src/components/search/SearchAgent.ts
- src/components/token/NftCell.vue
- src/components/transaction/TransactionByIdTable.vue
- src/dialogs/abi/ParamTypeEditor.vue
- src/dialogs/verification/FileList.vue
- src/utils/cache/LabelByIdCache.ts
- src/utils/name_service/provider/NameServiceProvider.ts
- src/utils/wallet/WalletSession.ts
- src/utils/wallet/client/WalletClient.ts
- src/utils/wallet/client/WalletClient_Ethereum.ts
- tests/e2e/plugins/index.js
- tests/unit/utils/EntityLoader.spec.ts
Changes below make some `eslint` tuning and apply recommended fixes.
**Checklist**
> chore: applying changes recommended by eslint 

- src/components/transaction/TablePageSize.vue
Changes below migrate `TablePageSize` vue to `<script setup>` syntax.
**Checklist**
> chore: migrated TablePageSize to <script setup> syntax.

- src/components/transaction/TransactionSummary.vue
Changes migrate `TransactionSummary` view to `<script setup>` syntax.
**Checklist**
> chore: migrated TransactionSummary vue to <script setup> syntax.

- src/components/transaction/TransactionTableControllerXL.ts
- src/utils/table/TableController.ts
- tests/unit/account/AccountDetails.spec.ts
Changes below implement an optimization in `TableController` class which avoids a duplicate update of `vue-router `in some cases (which is slow and can cause visual artifacts). 
`TransactionTableControllerXL` class needs an update to implement the same behavior. 
Unit tests also need update because optimization modifies mirror node queries order.
**Checklist**
> chore: TableController.updateRouteQuery() now updates route only when needed.

- vite.config.ts
Restore resolveVersion() in vite.config.ts
> chore: revert PR #1702 -- resolveVersion

- .github/workflows/flow-pull-request-checks.yaml
- .github/workflows/zxc-compile-explorer-code.yaml
- .github/workflows/zxc-release-docker-container.yaml
- .github/workflows/zxc-release-helm-chart.yaml
- README.md
- chart/Chart.yaml
- chart/templates/NOTES.txt
- chart/templates/_helpers.tpl
- chart/templates/configmap.yaml
- chart/templates/deployment.yaml
- chart/templates/hpa.yaml
- chart/templates/ingress.yaml
- chart/templates/poddisruptionbudget.yaml
- chart/templates/service.yaml
- chart/templates/serviceaccount.yaml
- chart/values.yaml
- docker-compose.yml
- package.json
- sonar-project.properties
- Updates the deployment values and registries for GHCR to point at hiero-ledger/hiero-mirror-node
- Updates docker config
- Updates helm chart config
- Updates helm templates
**Related Issue(s)**:
Relates to #1581
> chore: Update workflows and deployments for MNE

- .github/CODEOWNERS
Add 3 new files to CODEOWNERS file.
**Related Issue(s)**:
Fixes #1741
> chore: add new files to CODEOWNERS

- package-lock.json
Changes below update `package-lock.json` file after `hiero-ledger` migration.
**Checklist**
> chore: updating package-lock.json after hiero-ledger migration.

- src/utils/wallet/EIP6963Agent.ts
- src/utils/wallet/client/WalletClient_Ethereum.ts
Changes below re-enable automatic setup of Hedera `mainnet` and `testnet` chains in Metamask.
Dedicated logic was moved to `WalletClient_Ethereum` class: that is too late and must be done in `EIP6964Agent.requestSession()`.
**Checklist**
> fix: re-enabled automatic chain setup in Metamask

- MAINTAINERS.md
Maintainers file added as described at https://lf-decentralized-trust.github.io/governance/governing-documents/MAINTAINERS-file.html
> chore: Create MAINTAINERS.md

- CONFIGURATION.md
Update `CONFIGURATION.md` file to reflect recent changes in `core-config.json`, `networks-config.json`, as well as `style-config.css`.
> chore: update documentation of configuration files.

- CONFIGURATION.md
- public/style-config.css
- src/styles/explorer.css
- Make sure all CSS variables used to defined colors are exposed in `style-config.css`  -- and only that.
- Update `CONFIGURATION.md` readme file to cover `style-config.`css
Fixes #1516
> chore: update css config and doc

- src/pages/NodeDetails.vue
- src/schemas/MirrorNodeSchemas.ts
- src/utils/analyzer/NodeAnalyzer.ts
- tests/unit/Mocks.ts
- tests/unit/node/NodeDetails.spec.ts
Add support for decline_reward property in NodeDetails.
Fixes #1818
This won't display the _Decline Property_ at all until MN returns a value for this field.
**Checklist**
> feat: HIP-1064: Display decline_reward field for nodes

- src/dialogs/abi/ContractAbiValue.vue
Changes below migrate `ContractAbiValue` view to `<script setup>` syntax.
**Checklist**
> chore: migrating ContractAbiValue view to <script setup> syntax.

- package-lock.json
- package.json
- src/utils/EntityDescriptor.ts
- tests/e2e/specs/ContractNavigation.cy.ts
- Run `npm update --save`
- Harden EntityDescriptor.makeEntityDescriptor to avoid frequent failures in ContractNavigation e2e test
- Complete ContractNavigation e2e test
> chore: update dependencies and fix ContractNavigation e2e test failure

- chart/values.yaml
> chore: fix typo in chart/values.yaml

- src/components/values/EntityLabel.vue
- src/components/values/link/AccountIOL.vue
- src/components/values/link/ContractIOL.vue
- src/components/values/link/EntityIOL.vue
- src/components/values/link/TokenIOL.vue
- src/components/values/link/TopicIOL.vue
Convert the following classes: `EntityLabel`, `EntityIOL`, `AccountIOL`, `ContractIOL`, `TokenIOL`, `TopicIOL`
> chore: convert EntityLabel and xxxIOL classes to script setup syntax

- src/utils/analyzer/ERCAnalyzer.ts
- src/utils/cache/ERC1155Cache.ts
- tests/unit/contract/ContractDetails.spec.ts
These changes turn ERC1155Cache into a SingletonCache instead of an EntityCache.
> chore: refactor ERC1155Cache

- package-lock.json
- package.json
- src/utils/cache/HCSAsset.ts
- src/utils/cache/HCSAssetCache.ts
- tests/unit/topic/HCSContentSection.spec.ts
Support brotli in addition to zstd in HCSAsset implementation.
Fixes #1948 
> feat: support for brotli compression algorithm in HCS-1 content

- src/components/contract/ContractResult.vue
All is said in the title...
Fixes #1966 
> fix: swap tooltip descriptions for GAS USED and GAS CONSUMED

- src/components/account/AccountCreatedContractsTable.vue
- src/components/account/FungibleTable.vue
- src/components/account/PendingFungibleAirdropTable.vue
- src/components/account/PendingNftAirdropTable.vue
- src/components/account/VerifiedContractsTable.vue
- src/components/block/BlockTable.vue
- src/components/block/BlockTransactionTable.vue
- src/components/contract/ContractResultStateChangeEntry.vue
- src/components/contract/ERC20ByNameTable.vue
- src/components/contract/ERC721ByNameTable.vue
- src/components/node/NodeTable.vue
- src/components/token/NftHolderTable.vue
- src/components/token/TokenBalanceTable.vue
- src/components/token/TokenTable.vue
- src/components/token/TokensByNameTable.vue
- src/components/token/TokensByPopularityTable.vue
- src/components/topic/TopicMessageTable.vue
- src/components/topic/TopicTable.vue
- src/components/values/FunctionInput.vue
- src/components/values/FunctionResult.vue
- src/dialogs/CookiesDialog.vue
- src/pages/NftDetails.vue
- tsconfig.app.json
Changes below set `vueCompilerOptions.strictTemplates: true` in `tsconfig.app.json`.
This enables stronger type checking in `*.vue` files.
Changes also include fixes for some errors reported by type checker (mainly obsolete props).
**Checklist**
> chore: enabling vueCompilerOptions.strictTemplates

- src/pages/AddressDetails.vue
Changes below update `AddressDetails` view to use `<script setup>` syntax
**Checklist**
> chore: AddressDetails view now uses <script setup> syntax

- src/components/home/DashboardItemView.vue
- src/components/home/MarketDashboard.vue
- src/styles/explorer.css
Light refactoring to prepare for a bit of re-use by upcoming Metrics page.
> chore: refactor MarketDashboard

- eslint.config.mjs
- src/charts/core/ChartController.ts
- src/charts/hgraph/ActiveAccountController.ts
- src/charts/hgraph/HgraphChartController.ts
- src/charts/hgraph/TPSController.ts
- src/charts/hgraph/TxOverTimeController.ts
- src/components/node/NodeTable.vue
- src/components/search/SearchAgent.ts
- src/components/values/BlobValue.vue
- src/pages/Staking.vue
- src/schemas/MirrorNodeUtils.ts
- src/utils/PathParam.ts
- src/utils/TransactionHash.ts
- src/utils/cache/TopicMessageCache.ts
- src/utils/name_service/provider/NameServiceProvider.ts
- src/utils/parser/AccountLocParser.ts
- src/utils/parser/BlockLocParser.ts
- src/utils/parser/ContractLocParser.ts
- src/utils/wallet/EIP6963Agent.ts
- src/utils/wallet/WalletManagerV4.ts
- src/utils/wallet/WalletSession.ts
- src/utils/wallet/client/WalletClient.ts
- src/utils/wallet/client/WalletClient_Hiero.ts
- vite.config.ts
Changes below enable `@typescript-eslint/no-unused-vars` flag in `eslint` and fix reported warnings.
**Checklist**
> chore:  enabling @typescript-eslint/no-unused-vars flag in eslint config

- _frontend/README.md
link to configuration file broken
> fix: Update README.md - broken link to config file
